Forum efficient removal
Joystream/joystream pull request #1059
Opened 2020-07-24 15:52 UTC by ondratra

Solves subtask of #766
- introduce limits on storage maps to prevent block gas exhaustion

To minimize merge conflict potential, this PR assumes #1003 will be merged first.

2020-08-04 13:43 UTC, bedeho requested changes
Looks good.

Can add a comment to each limit to explain which one of them must be small enough to allow safe iteration in a single extrinsic? This will help the runtime developer provide sane values. I think the upper bound on the size of a thread is at least one case.

2020-08-04 13:43 UTC, bedeho commented on runtime-modules/forum/src/lib.rs
> +        pub CategoryCounter get(category_counter) config(): T::CategoryId;
This comment is incorrect.

2020-08-05 12:49 UTC, ondratra commented on runtime-modules/forum/src/lib.rs
> +        pub CategoryCounter get(category_counter) config(): T::CategoryId;
Fixed.

2020-08-05 12:50 UTC, ondratra commented
You are right. I added extra commentary to limits.

2020-08-05 13:49 UTC, merged