Cont dir substrate 2 0
Joystream/joystream pull request #1072
Opened 2020-07-28 15:50 UTC by iorveth

This PR aims to upgrade content directory to substrate 2.0.

Closes: https://github.com/Joystream/joystream/issues/1054

2020-08-04 13:36 UTC, bedeho commented
I think I will just leave this review to Shamil

2020-08-04 13:36 UTC, bedeho approved these changes

2020-08-05 11:06 UTC, shamil-gadelshin requested changes
We don't have a strict rule for that but I recommend to comment all public methods or type definitions (for example in the storage definition): it could be done with temporary enabling this code line: `#![warn(missing_docs)]` .

Also, I like that for such a complex module it's very clean and understandable. Good work!

2020-08-05 11:06 UTC, shamil-gadelshin commented on runtime-modules/content-directory/Cargo.toml
Let's have a common format for dependencies: single line based similar to parity's format.

2020-08-05 11:06 UTC, shamil-gadelshin commented on runtime-modules/content-directory/Cargo.toml
>  [features]
Could you sort feature-definitions similar to dependencies order: it's easier to check them.

2020-08-05 11:06 UTC, shamil-gadelshin commented on runtime-modules/content-directory/Cargo.toml
>  	'rstd/std',
Could you rename rstd to sp-std - similar to the new format in the Substrate?

2020-08-05 11:06 UTC, shamil-gadelshin commented on runtime-modules/content-directory/Cargo.toml
>  name = 'substrate-content-directory-module'
Please rename it to 'pallet-content-directory'.

2020-08-05 11:06 UTC, shamil-gadelshin commented on runtime-modules/content-directory/src/lib.rs
If it's not too far out your current scope could you perform actual error conversion to the Substrate decl_error! macro?

2020-08-11 14:28 UTC, iorveth commented on runtime-modules/content-directory/Cargo.toml
>  name = 'substrate-content-directory-module'
Done here https://github.com/Joystream/joystream/pull/1072/commits/0e4cfb15c7a0d866f490a5ccae9fcd472b9df295

2020-08-11 14:28 UTC, iorveth commented on runtime-modules/content-directory/Cargo.toml
>  	'rstd/std',
Done https://github.com/Joystream/joystream/pull/1072/commits/0e4cfb15c7a0d866f490a5ccae9fcd472b9df295

2020-08-11 14:28 UTC, iorveth commented on runtime-modules/content-directory/Cargo.toml
>  [features]
Good point, https://github.com/Joystream/joystream/pull/1072/commits/0e4cfb15c7a0d866f490a5ccae9fcd472b9df295

2020-08-11 14:29 UTC, iorveth commented on runtime-modules/content-directory/Cargo.toml
Done https://github.com/Joystream/joystream/pull/1072/commits/0e4cfb15c7a0d866f490a5ccae9fcd472b9df295

2020-08-11 14:31 UTC, iorveth commented
_We don't have a strict rule for that but I recommend to comment all public methods or type definitions (for example in the storage definition): it could be done with temporary enabling this code line: #![warn(missing_docs)] ._

Thanks for pointing that feature. Added missing comments for the all public functions, traits and structure fields. 
https://github.com/Joystream/joystream/pull/1072/commits/b570a9a91758f578937d3f87316621ef3c003e99

2020-08-17 12:10 UTC, iorveth commented on runtime-modules/content-directory/src/lib.rs
Done here https://github.com/Joystream/joystream/pull/1072/commits/0ed9ecd9b5958aeeaa032451e1579d35cda22d35,
https://github.com/Joystream/joystream/pull/1072/commits/65cdabbfec7ce1803a4f7cc7768f9f491b73baf5

2020-08-24 09:22 UTC, shamil-gadelshin approved these changes
LGTM. Nice work on error conversion!

2020-08-24 09:22 UTC, merged