readme updates for alexandria
Joystream/joystream pull request #1417
Opened 2020-09-20 05:32 UTC by mnaamani

Removing reference to rome.json in readme

2020-09-20 05:38 UTC, bwhm requested changes
Not sure if if we can (or should) merge this before the `joy-testnet-4.json` is added?

2020-09-20 05:38 UTC, bwhm commented on node/README.md
> +./target/release/joystream-node --chain testnets/joy-tesnet-4.json
```suggestion
./target/release/joystream-node --chain testnets/joy-testnet-4.json
```

2020-09-20 05:44 UTC, mnaamani commented
okay lets wait to merge it until I add the chainspec to the repo, then will merge this into master

2020-09-21 05:56 UTC, bwhm approved these changes
LGTM!

2020-09-21 05:56 UTC, merged