Working team pallet. Stakes and extra hiring flow extrinsics.
Joystream/joystream pull request #1434
Opened 2020-09-21 16:29 UTC by shamil-gadelshin

2020-09-23 18:02 UTC, bedeho requested changes
- I know this is not from this PR, but: Why does `JobOpening` have `created` field?

2020-09-23 18:02 UTC, bedeho commented on runtime-modules/working-team/src/lib.rs
> +            // Ensure the source_account is either the controller or root account of member with given id.
1. Why are we checking the root account?
2. Why are we coupled to the membership module? 

There should just be a simple `is_member` check on the runtime trait.

2020-09-23 18:02 UTC, bedeho commented on runtime-modules/working-team/src/types.rs
> +    fn decrease_stake(
Why do decrease and increase return dispatchable results, they should not be able to fail - just like slash, as they just set a lock on the given account. It resulting in possible errors _MUTATION SAFE_ markers.

2020-09-23 18:02 UTC, bedeho commented on runtime-modules/working-team/src/types.rs
> +    fn lock(lock_id: LockIdentifier, account_id: &T::AccountId, amount: BalanceOfCurrency<T>);
Can we drop these lock_ids ? I know you wanted to post pone, but it really does not make sense to me to have them even now

2020-09-23 18:02 UTC, bedeho commented on runtime-modules/working-team/src/types.rs
> +    fn ensure_can_make_stake(
The semantics of this call is too vague, the name is overly broad. A consequence appears to be that no check is made that the staker is providing an account that is actually under their control. The signature of this interface could not check this even in principle, as it does not have the identity of the staker.

I suggest we make things crystal clear by having two distinct calls
- `is_member_staking_account(member_id, account_id) -> bool`
- `is_account_free_of_conflicting_staking(account_id) -> bool`

2020-09-23 18:02 UTC, bedeho commented on runtime-modules/working-team/src/types.rs
> +    fn decrease_stake(
Let me add to that: why are there even checkers and mutators even here?

I don't see a need for either.

2020-09-24 15:53 UTC, shamil-gadelshin commented on runtime-modules/working-team/src/types.rs
> +    fn lock(lock_id: LockIdentifier, account_id: &T::AccountId, amount: BalanceOfCurrency<T>);
Ok.

2020-09-24 15:53 UTC, shamil-gadelshin commented on runtime-modules/working-team/src/types.rs
> +    fn ensure_can_make_stake(
Ok.

2020-09-24 15:54 UTC, shamil-gadelshin commented on runtime-modules/working-team/src/lib.rs
> +            // Ensure the source_account is either the controller or root account of member with given id.
Fixed.

2020-09-24 15:54 UTC, shamil-gadelshin commented on runtime-modules/working-team/src/types.rs
> +    fn decrease_stake(
I changed the semantics.

2020-09-24 15:55 UTC, shamil-gadelshin commented
Among other fixes I remove abstract `ensure_* `methods from the `StakingHandler` trait and introduced fine grained methods. Also,` decrease_stake()` is infallible now.

2020-09-24 19:33 UTC, bedeho approved these changes
LGTM.

2020-09-24 19:34 UTC, merged