Implement total stake in staking overview
Joystream/joystream pull request #1459
Opened 2020-09-24 11:01 UTC by DzhideX

This PR addresses issue #1454 

Note:

- I am not sure if `stakeOwn` and `stakeOther` will ever really be undefined, but I put checks in place. If anyone thinks these might not be necessary, I'm happy to take them out.

2020-09-29 07:13 UTC, bwhm approved these changes
Tested, and works fine :)

2020-10-14 07:06 UTC, Lezek123 requested changes

2020-10-14 07:06 UTC, Lezek123 commented on pioneer/packages/page-staking/src/Overview/Address/index.tsx
> +        {(stakeOwn && stakeOther)
`stakeOther` seems to be calculated based on `stakeTotal`, so perhaps we can just use the latter here and avoid too many unnecessary checks (only leaving one `stakeTotal ? /* ... */ : null`)

2020-10-14 11:50 UTC, Lezek123 approved these changes
Seems to work well. Doesn't make responsiveness much worse, as there similar problems with it before anyway, so I think it's good to go!

2020-10-22 14:02 UTC, bwhm commented
@mnaamani 
Can we merge this?

2020-10-22 14:06 UTC, mnaamani commented
LGTM go for it @bwhm

2020-10-22 14:08 UTC, merged