council - candidacy note
Joystream/joystream pull request #1656
Opened 2020-11-06 20:47 UTC by ondratra

This PR adds the possibility to council candidates to add a short description about their candidacy.

2020-11-07 10:01 UTC, bedeho requested changes
Looks good, just a minor cosmetic change needed.

2020-11-07 10:01 UTC, bedeho commented on runtime-modules/council/src/lib.rs
> +            // == MUTATION SAFE ==
I think this note can be a bit higher up, right after `can_set_candidacy_note`.

2020-11-09 14:20 UTC, ondratra commented on runtime-modules/council/src/lib.rs
> +            // == MUTATION SAFE ==
Done

2020-11-09 14:39 UTC, bedeho approved these changes

2020-11-09 14:39 UTC, merged