Working group weights
Joystream/joystream pull request #1858
Opened 2020-12-03 10:45 UTC by conectado

This PR includes:

* Fix `working_group` benchmark in Olympia
* Add `working_group` pallet to benchmark
  * **Note:** I used `ForumWorkingGroup` but for what I've seen which instance we should use to benchmark is arbitrary
* Add weight annotations for `working_group` pallet

2020-12-03 16:09 UTC, iorveth commented
Just one comment here. 
Wouldn`t it be safer to have separate benchmarks for all working group instances on node runtime level?
My primarily concern is that we can probably have individual constraint limits for working group instances and that can result in different worst-case scenarios. https://github.com/Joystream/joystream/blob/olympia/runtime/src/lib.rs#L620

2020-12-03 17:00 UTC, conectado commented
> Just one comment here.
> Wouldn`t it be safer to have separate benchmarks for all working group instances on node runtime level?
> My primarily concern is that we can probably have individual constraint limits for working group instances and that can result in different worst-case scenarios. https://github.com/Joystream/joystream/blob/olympia/runtime/src/lib.rs#L620

I agree. I don't know if it's possible however to run multiple benchmarks for the same pallet. I will try.

2020-12-03 17:12 UTC, conectado commented
> > Just one comment here.
> > Wouldn`t it be safer to have separate benchmarks for all working group instances on node runtime level?
> > My primarily concern is that we can probably have individual constraint limits for working group instances and that can result in different worst-case scenarios. https://github.com/Joystream/joystream/blob/olympia/runtime/src/lib.rs#L620
> 
> I agree. I don't know if it's possible however to run multiple benchmarks for the same pallet. I will try.

Can be done, will upload the changes ASAP.

2020-12-03 17:25 UTC, bedeho commented
Nice observation @iorveth .

2020-12-03 18:08 UTC, conectado commented
> > > Just one comment here.
> > > Wouldn`t it be safer to have separate benchmarks for all working group instances on node runtime level?
> > > My primarily concern is that we can probably have individual constraint limits for working group instances and that can result in different worst-case scenarios. https://github.com/Joystream/joystream/blob/olympia/runtime/src/lib.rs#L620
> > 
> > 
> > I agree. I don't know if it's possible however to run multiple benchmarks for the same pallet. I will try.
> 
> Can be done, will upload the changes ASAP.

After implementing the way I found to do it, I found a problem where the weight-generated files can't be used without manually modifying them I will research more.

2020-12-04 09:33 UTC, conectado commented
> > > > Just one comment here.
> > > > Wouldn`t it be safer to have separate benchmarks for all working group instances on node runtime level?
> > > > My primarily concern is that we can probably have individual constraint limits for working group instances and that can result in different worst-case scenarios. https://github.com/Joystream/joystream/blob/olympia/runtime/src/lib.rs#L620
> > > 
> > > 
> > > I agree. I don't know if it's possible however to run multiple benchmarks for the same pallet. I will try.
> > 
> > 
> > Can be done, will upload the changes ASAP.
> 
> After implementing the way I found to do it, I found a problem where the weight-generated files can't be used without manually modifying them I will research more.

Until [this PR](https://github.com/paritytech/substrate/pull/7669) which solves this problem lands in substrate and we migrate to a version that includes it, we will either use the worst-case instance for benchmarking and if there's no such obvious instance we will include a mock instance representing the worst-case.

For this PR the worst-case instance is `ContentDirectoryWorkingGroup`

2020-12-04 15:48 UTC, shamil-gadelshin requested changes

2020-12-04 15:48 UTC, shamil-gadelshin commented on runtime-modules/working-group/src/lib.rs
> +        #[weight = WeightInfoWorkingGroup::<T, I>::terminate_role_lead(
Consider moving the weight-code to a separate function.

2020-12-04 15:48 UTC, shamil-gadelshin commented on runtime-modules/working-group/src/lib.rs
> +            if let Some(status_text) = status_text {
Consider changing this snippet to a functional style: using Option.map with unwrap_or_default().

2020-12-04 15:48 UTC, shamil-gadelshin commented on runtime-modules/working-group/src/lib.rs
> +/// working_group WeightInfo
Please, change this auto-generated comment to `Working group WeightInfo`.

2020-12-04 15:48 UTC, shamil-gadelshin commented on runtime-modules/working-group/src/lib.rs
> +                    .unwrap_or_else(|| 0)
Please, change to unwrap_or_default()

2020-12-04 15:48 UTC, shamil-gadelshin commented on runtime-modules/working-group/src/lib.rs
> +                            .unwrap_or_else(|| 0)
Please, change to unwrap_or_default()

2020-12-04 17:01 UTC, shamil-gadelshin approved these changes
LGTM

2020-12-07 08:59 UTC, merged