Cancel active and pending proposals on runtime upgrade.
Joystream/joystream pull request #2020
Opened 2021-01-14 12:04 UTC by shamil-gadelshin

[Main issue](https://github.com/Joystream/joystream/issues/2008)

2021-01-15 15:26 UTC, conectado requested changes
Look good. Just a couple of minor comments also please fix the compilation with `cargo test --all --feature runtime-benchmarks`

2021-01-15 15:26 UTC, conectado commented on runtime-modules/proposals/engine/src/tests/mod.rs
> +        let proposal_id2 = dummy_proposal.create_proposal_and_assert(Ok(2)).unwrap();
We could use more descriptive names for these proposals ids such as `proposal_id_pending_execution` and `proposal_id_active`.

2021-01-15 15:26 UTC, conectado commented on runtime-modules/proposals/engine/src/tests/mod.rs
> +        assert_eq!(
Shouldn't we do the same check for the other proposal?

2021-01-15 15:26 UTC, conectado commented on runtime-modules/proposals/engine/src/tests/mod.rs
> +
Can we add a check here to be sure that the proposal is pending constitutionality?

2021-01-18 13:31 UTC, shamil-gadelshin commented on runtime-modules/proposals/engine/src/tests/mod.rs
> +        let proposal_id2 = dummy_proposal.create_proposal_and_assert(Ok(2)).unwrap();
Sure.

2021-01-18 13:31 UTC, shamil-gadelshin commented on runtime-modules/proposals/engine/src/tests/mod.rs
> +        assert_eq!(
Sure.

2021-01-18 13:31 UTC, shamil-gadelshin commented on runtime-modules/proposals/engine/src/tests/mod.rs
> +
Sure.

2021-01-19 12:23 UTC, conectado approved these changes
LGTM

2021-01-19 15:35 UTC, merged