Membership benchmarking
Joystream/joystream pull request #2024
Opened 2021-01-14 22:27 UTC by iorveth

2021-01-21 18:09 UTC, conectado requested changes
Great work!

Just a couple of comments. 

But more importantly, we could do without introducing the trait in general, we can create a trait only within the benchmarking features. [See this example(the tests aren't fixed here)](https://github.com/conectado/joystream/commit/271a6b7df4c37b472fffe5283f7e1d556286fb6b).

2021-01-21 18:09 UTC, conectado commented on runtime-modules/membership/src/lib.rs
> +        #[weight = if params.referrer_id.is_some() {
I think it'd be better to move the weight calculation to a separate function

2021-01-21 18:09 UTC, conectado commented on runtime-modules/membership/src/benchmarking.rs
> +    update_profile{
Please test for all parameters possible length(name, handle, avatar_uri, about)

2021-01-21 18:09 UTC, conectado commented on runtime-modules/membership/src/lib.rs
> +        #[weight = match (new_root_account.is_some(), new_controller_account.is_some()) {
Please move weight calculation to a separate function

2021-01-21 18:09 UTC, conectado commented on runtime-modules/membership/src/benchmarking.rs
> +        let member_id = 0;
Please benchmark with all different parameters length in `InviteMembershipParameters`

2021-01-22 12:48 UTC, iorveth commented on runtime-modules/membership/src/benchmarking.rs
> +    update_profile{
It seems, that they do not affect benchmarking weight at all.
`	// WARNING! Some components were not used: ["j"]`
Only `handle` possible lengths affects benchmarking. 
We do not perform any computations/db operations with these parameters.

2021-01-22 12:49 UTC, iorveth commented on runtime-modules/membership/src/benchmarking.rs
> +        let member_id = 0;
It seems, that they do not affect benchmarking weight at all.
// WARNING! Some components were not used: ["j"]
Only handle possible lengths affects benchmarking.
We do not perform any computations/db operations with these parameters.

2021-01-22 13:15 UTC, iorveth commented on runtime-modules/membership/src/lib.rs
> +        #[weight = match (new_root_account.is_some(), new_controller_account.is_some()) {
Done https://github.com/Joystream/joystream/pull/2024/commits/187fa9e4ba17abd5e1c97dd2fc8db253f282dd7f

2021-01-22 13:15 UTC, iorveth commented on runtime-modules/membership/src/lib.rs
> +        #[weight = if params.referrer_id.is_some() {
Done https://github.com/Joystream/joystream/pull/2024/commits/187fa9e4ba17abd5e1c97dd2fc8db253f282dd7f

2021-01-22 14:31 UTC, iorveth commented
`But more importantly, we could do without introducing the trait in general, we can create a trait only within the benchmarking features. See this example(the tests aren't fixed here).
`

Thanks for the helpful suggestion!

2021-01-22 14:38 UTC, conectado commented on runtime-modules/membership/src/benchmarking.rs
> +    update_profile{
I think it's better if we leave the benchmarking for those parameters on and we manually modify the trait(this won't be neccesary with the next Substrate update). It's how we have handle it in the other pallets and sometimes unexpectedly these parameters have some footprint in processing time.

2021-01-22 14:38 UTC, conectado commented on runtime-modules/membership/src/benchmarking.rs
> +        let member_id = 0;
I think it's better if we leave the benchmarking for those parameters on and we manually modify the trait(this won't be neccesary with the next Substrate update). It's how we have handle it in the other pallets and sometimes unexpectedly these parameters have some footprint in processing time.

2021-01-22 15:05 UTC, conectado requested changes
I just recommend that we would benchmark unused parameters even if they don't affect the results.

2021-01-22 15:13 UTC, merged