Charge for thread and post creation
Joystream/joystream pull request #2210
Opened 2021-02-26 14:38 UTC by conectado

# Fix `forum_pallet` for #2196 

In #2196 we found that thread/post creation has a low cost and can be used to fill up the storage.

To prevent this we add a cost to creating a thread or post and then pay the sum of those costs to the deleted of the thread to incentivize deletion.

Furthermore, we move the posts from their own storage to within the thread storage as part of the `Thread` struct to improve deletion times.

2021-03-01 11:12 UTC, shamil-gadelshin requested changes
Adding to upcoming Bedeho's review:
- Is it the case that we could have a non-zero thread account balance if we delete a thread without previously deleting posts?
- You didn't change the AccountId type from the u64 to u128 as in Parity's recommendation. Are you sure that you get different account ids for different threads in the test environment?

2021-03-01 12:06 UTC, bedeho requested changes
First, off excellent work, looks correct.

- `Post` no longer needs `thread_id` when inlined.
- Could you create an issue about dropping archiving threads functionality, it seems now that we can effectively drop threads from storage that its not worth having, and it can confuse people about when and why to do cleanups.
- Could you do a handbook PR to reconcile?

2021-03-01 12:06 UTC, bedeho commented on runtime-modules/forum/src/lib.rs
>      pub num_direct_posts: u32,
is `Post::num_direct_posts` needed any longer? `posts` probably exposes a coutner for the number of mappings.

2021-03-01 12:06 UTC, bedeho commented on runtime-modules/forum/src/lib.rs
> +    type StartingCleanupPayOff: Get<Self::Balance>;
Please find a more descriptive name.

2021-03-01 12:06 UTC, bedeho commented on runtime-modules/forum/src/lib.rs
> +            Self::transfer_to_thread_account(cleanup_pay_off, new_thread_id, &account_id);
Can we call this account which holds funds associated with state cleanup bounties something like `state cleanup treasury account`.

2021-03-01 12:06 UTC, bedeho commented on runtime-modules/forum/src/lib.rs
> +            Self::transfer_to_thread_account(cleanup_pay_off, new_thread_id, &account_id);
Why do you not need to actually check that there is sufficient balance for this call in the pre-mutation stage?

2021-03-01 12:06 UTC, bedeho commented on runtime-modules/forum/src/lib.rs
> +            Self::transfer_to_thread_account(cleanup_pay_off, new_thread_id, &account_id);
Ah. found this in `ensure_can_create_thread` now.

2021-03-01 14:26 UTC, bedeho commented
Forgot to ask, is there any reason to couple this to the `balances` module?  could you not just use the `Currency` trait or something similar to keep the coupling loose and tests without sideffects?

2021-03-03 14:40 UTC, conectado commented
>     * Could you create an issue about dropping archiving threads functionality, it seems now that we can effectively drop threads from storage that its not worth having, and it can confuse people about when and why to do cleanups.

Created in #2222

2021-03-03 16:50 UTC, conectado commented
>     * Is it the case that we could have a non-zero thread account balance if we delete a thread without previously deleting posts?

Could you re-phrase this? I don't understand. However, as it currently stand deleting post doesn't change the cleanup thread pay off.

>     * You didn't change the AccountId type for mocks from the u64 to u128 as in Parity's recommendation. Are you sure that you get different account ids for different threads in the test environment?

Added a test to check for this and inded I needed to change to u128.

2021-03-04 11:09 UTC, conectado commented
>     Could you do a handbook PR to reconcile?

[Here](https://github.com/Joystream/handbook/pull/34)

2021-03-08 14:27 UTC, bedeho approved these changes
Good job.

2021-03-08 14:27 UTC, merged