Uploads can be done to any storage provider
Joystream/joystream pull request #2278
Opened 2021-03-23 11:38 UTC by mnaamani

2021-03-30 15:31 UTC, shamil-gadelshin requested changes
Looks good. I tested "upload" and "download" commands. Left just a couple of small issues.

2021-03-30 15:31 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/download.ts
> +        Example: storage-cli download 0x7a6ba7e9157e5fba190dc146fe1baa8180e29728a5c76779ed99655500cff795 ./movie.mp4
Please, change an example for download to different CID format (eg.: "5GFwJXfTf19eUAgoHLsDwxd3YZ5ADdHs5mSzPZVU3Aw6T5Gf")

2021-03-30 15:31 UTC, shamil-gadelshin commented on runtime-modules/storage/src/data_directory.rs
> +                // It is irrelevant what liaison is set when judgement is pending
It is confusing. Do you mind changing it to the Option?

2021-03-30 17:27 UTC, mnaamani commented on storage-node/packages/cli/src/commands/download.ts
> +        Example: storage-cli download 0x7a6ba7e9157e5fba190dc146fe1baa8180e29728a5c76779ed99655500cff795 ./movie.mp4
makes sense, will update

2021-03-30 17:28 UTC, mnaamani commented on runtime-modules/storage/src/data_directory.rs
> +                // It is irrelevant what liaison is set when judgement is pending
I agree, an Option will be clearer.

2021-03-30 19:00 UTC, mnaamani commented on storage-node/packages/cli/src/commands/download.ts
> +        Example: storage-cli download 0x7a6ba7e9157e5fba190dc146fe1baa8180e29728a5c76779ed99655500cff795 ./movie.mp4
done in https://github.com/Joystream/joystream/pull/2278/commits/edf7e2671e3e897505158fdedefb7892c24fcbb1

2021-03-30 19:01 UTC, mnaamani commented on runtime-modules/storage/src/data_directory.rs
> +                // It is irrelevant what liaison is set when judgement is pending
done in https://github.com/Joystream/joystream/pull/2278/commits/fad04b7e2caf78333f360ba04741c0b92d9f5725

2021-03-31 09:49 UTC, shamil-gadelshin approved these changes
LGTM

2021-03-31 09:50 UTC, merged