Sumer upgrade substrate version to 2.0.1
Joystream/joystream pull request #2348
Opened 2021-04-15 18:49 UTC by conectado

This PR ports the changes upgrading substrate to v2.0.1 from antioch.

There should be no conflict due to this changes with antioch, however some exists where sumer diverged from antioch on unrelated ways.

2021-04-20 13:21 UTC, shamil-gadelshin requested changes
Looks OK. Left a couple of issues. The important one - change runtime and node versions.

I bumped the runtime version locally and tested different configurations:
- runtime upgrade from antioch to sumer works both in dev and 'two-validators' modes
- upgraded sumer node works both in dev and 'two-validators' modes

However, when injecting the keys for the Sumer 'two-validators' running nodes. The chain starts producing blocks but without finalization. It resumes finalization after the restart. Is it a problem? @mnaamani

2021-04-20 13:21 UTC, shamil-gadelshin commented on runtime/src/lib.rs
> +    authoring_version: 9,
The spec version should be bumped further. Antioch has v9.3.0

2021-04-20 13:21 UTC, shamil-gadelshin commented on runtime/Cargo.toml
> +version = '9.0.0'
The spec version should be bumped further. Antioch has v9.3.0

2021-04-20 13:21 UTC, shamil-gadelshin commented on runtime-modules/proposals/engine/src/lib.rs
> +//! The main component of the proposals frame_system. Provides methods and extrinsics to create and
Fix incorrect replace of the `system`

2021-04-20 13:21 UTC, shamil-gadelshin commented on runtime-modules/proposals/discussion/src/lib.rs
> +//! It contains discussion subframe_system of the proposals.
Fix incorrect replace of the `system`

2021-04-20 13:21 UTC, shamil-gadelshin commented on runtime-modules/proposals/codex/src/lib.rs
> +//! Component of the proposals frame_system. It contains preset proposal types.
Fix incorrect replace of the `system`

2021-04-20 13:21 UTC, shamil-gadelshin commented on runtime-modules/proposals/codex/src/lib.rs
> +//! The proposals codex module serves as a facade and entry point of the proposals frame_system. It uses
Fix incorrect replace of the `system`

2021-04-20 13:21 UTC, shamil-gadelshin commented on node/Cargo.toml
> -version = '3.7.2'
Please, bump version.

2021-04-20 13:24 UTC, shamil-gadelshin commented
What compiler version do we use for this release? @conectado Is it the same as for Antioch (`nightly-2021-03-24`)?

2021-04-21 18:37 UTC, conectado commented
> What compiler version do we use for this release? @conectado Is it the same as for Antioch (`nightly-2021-03-24`)?

Yes, I set that up using `setup.sh` which is the same as in antioch

2021-04-21 23:27 UTC, conectado commented
> Looks OK. Left a couple of issues. The important one - change runtime and node versions.
> 
> I bumped the runtime version locally and tested different configurations:
> 
>     * runtime upgrade from antioch to sumer works both in dev and 'two-validators' modes
> 
>     * upgraded sumer node works both in dev and 'two-validators' modes
> 
> 
> However, when injecting the keys for the Sumer 'two-validators' running nodes. The chain starts producing blocks but without finalization. It resumes finalization after the restart. Is it a problem? @mnaamani

I ran the nodes using `./tests/network-tests/run-local-node-tests.sh`. But I'm not sure how to execute the runtime upgrade locally to tests if this works.

2021-04-26 09:34 UTC, mnaamani commented
> However, when injecting the keys for the Sumer 'two-validators' running nodes. The chain starts producing blocks but without finalization. It resumes finalization after the restart. Is it a problem? @mnaamani

I had no issues with finalization running a `local` chain with alice and bob as validators

2021-04-26 09:38 UTC, mnaamani approved these changes
Will continue work to update in new PR

2021-04-26 09:38 UTC, merged