Video comments
Joystream/joystream pull request #2510
Opened 2021-07-01 13:18 UTC by ignazio-bovo

Specs are from #2492.

2021-07-24 13:34 UTC, bedeho requested changes
Looks like a great start, here are some changes needed

- allow channel owner to turn comment section off or on, and while its off, no comments or reactions on comments are possible. during video creation, the creator can choose to have comment on or off to begin with.
- introduce reactions to the video itself, as distinct from the posts/replies.
- follow this updated scheme that is being introduced in the forum 
https://github.com/Joystream/joystream/issues/2545
- video deletion should include deletion of all posts/replies. This should work in the same way as thread deletion, using witnesses to size of object tree, and unrolling over multiple blocks. Again, we only allow one simultaneous unrolling. In order to traverse the entire tree of posts/replies for a video, an iterable double map with key space `VideoIdxPostId`may be needed to organise the posts/replies.
- Can you calculate what the total state footprint, in bytes, of all comments will be as a functino of the number of videos and the average number of comments per video? We need this as a final sanity check on the cost of this feature on the system. If its too expensive, we will need to possible select an off-chain version of this using a metaprotocol version https://github.com/Joystream/joystream/issues/1990. The forum is likely fine as it is, as it won't grow nearly as much as the video comments possibly will.

2021-07-24 13:34 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +    pub video: VideoId,
I don't think we need both a `Post` and a `Reply` representation, correct me if I am wrong.

All we need is one, say `Post`, where its `parent` field is a sum type over a video, e.g. like `ParentId`, if its a post directly to a video itself, or to a prior post on the same video.

2021-07-24 13:34 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +    text: Hash,
Drop all hash commitments, we are not using this any longer.

2021-07-24 13:34 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +    pub last_edited: BlockNumber,
Check https://github.com/Joystream/joystream/issues/2545, we no longer use this timeout mechanism.

2021-08-10 06:33 UTC, ignazio-bovo commented
The post data structure now looks like this.

``` rust
pub struct Post_<
    MemberId: Default + Clone + Copy,
    CuratorGroupId: Default + Clone + Copy,
    CuratorId: Default + Clone + Copy,
    Balance,
    PostId,
    VideoId,
> {
    /// Author of post.
    pub author: ContentActor<CuratorGroupId, CuratorId, MemberId>,

    /// Cleanup pay off
    pub bloat_bond: Balance,

    /// Overall replies counter
    pub replies_count: PostId,

    /// video associated to the post (instead of the body hash as in the blog module)
    pub post_type: PostType,

    /// parent comment if any
    pub parent_id: Option<PostId>,

    /// text
    pub text: Vec<u8>,

    /// video reference
    pub video_reference: VideoId,
}
```
The `video_reference` field is needed in order to have a quick access to video id the comment is referring to, In order to be inserted into the double map `VideoIdxPostId`

2021-08-10 12:29 UTC, ignazio-bovo commented
## Compute total state footprint due to comments as a function of number of videos & avg comments per video
- Dropping hash commitments O(`Average Characters per comment` x `Averege comments per video` x `Number Of Videos`)
- Not Dropping hash commitments O(`32` x `Averege comments per video` x `Number Of Videos`) assuming
`blake2_256` is used as hashing function
*** Computations
- Comments engagement (= comments/views) for a successful channel is at least .5% (source: https://tubularlabs.com/blog/3-metrics-youtube-success/)
- A youtube video (as of now) has on average 8,332 views (source: Google search)
- This means that on average you get 8,332 x .005 = 41.66 comments per video
- Estimates suggest that there are from 135 to 145 billion videos on youtube
*Size in bytes of comments without hash*
Considering 5 randomly picked comments and taking the average lenght in a top trending video in my YT homepage it appears 
to be around 75 < 80, hence:
about 80 * 41.66 * 140,000,000,0002 = 4.66592e+14 bytes as of 2021
*Size in bytes of comments with hash*
about 32 * 41.66 * 140,000,000,000 = 1.866368e+14 bytes as of 2021

2021-08-16 10:58 UTC, ignazio-bovo commented
As for now I left `cleanup_cost = 1`.
I have the following problem 
- posts are stored in a `double_map`: `VideoId x PostId`
- A `remove_prefix` invocation in a storage double map `N x M` should have complexity O(log(N) + M)
- cleanup cost for `post` should therefore be sized around `log (next_video_id) + post.replies_count`. This quantity is effectively available at deletion time and not at post creation time, hence I cannot effectively ask for the author to deposit `max( size_of::<Post>() x byte_price, cleanup_cost + margin)`

So here what I would do:
##### during post creation time
- `bloat_bond = size_of::<Post>() x byte_price` 
- bloat_bond is deposited from post author to post treasury account
##### during cleanup time 
- `bloat_bond = max( size_of::<Post>() x byte_price, cleanup_cost + margin)`
and it is refunded if actor is the post author, burned otherwise

2021-08-18 16:25 UTC, bedeho commented
> A remove_prefix invocation in a storage double map N x M should (and maybe I am wrong) have complexity O(log(N) + M) 

- I could not find where you are getting this from those links? can you be more specific?
- My guess would be that each deletion of a post takes `log(N)` steps, and since you are doing this `M` times, it would be  `Mlog(N)`?
- Your general point here is that database access costs are not constant, but depend on the total size of the current database. This is an interesting point, but surely this should already be an issue confronting pricing normal single database reads, not only these sequences of deletions. Given that the benchmarking approach for Substrate appears to just have a fixed price for reads and writes in all contexts, I wonder if they just choose to pretend that some constant is good enough since `log` grows very slowly eventually. But you should def. dig deeper here, perhaps on the Substrate technical chat.

2021-08-19 05:03 UTC, ignazio-bovo commented
>I could not find where you are getting this from those links? can you be more specific?
I was convinced of O(M log N) too, but then I asked on the substrate technical chat and they said it was O(log N + M). I wasn't convinced that is way I expressed caution in the () brackets. Maybe O(M log N) is the cost of M access to a single map and they 
use some optimization for a double map...

2022-01-14 10:22 UTC, ignazio-bovo commented
closing in favor of newest Olympia work

2022-01-14 10:22 UTC, closed without merging