DevOps - Add Github action to deploy node-network [WIP]
Joystream/joystream pull request #2594
Opened 2021-08-25 14:14 UTC by ahhda

Adds a Github Action workflow dispatch to deploy the Pulumi stack for node-network

2021-08-31 09:20 UTC, mnaamani requested changes

2021-08-31 09:20 UTC, mnaamani commented on .github/workflows/create-node-network-pulumi.yml
> +          pulumi config set-all --plaintext aws:region=us-east-1 \
stack name "dev" should be a user input as well as other stack settings:
`numberOfValidators`, `networkSuffix`, and `nodeImage` with values you set here as defaults perhaps.

2021-08-31 09:20 UTC, mnaamani commented on .github/workflows/create-node-network-pulumi.yml
> +          kubectl cp $(kubectl get pods | grep rpc-node | awk '{print $1}'):/chain-data/chain-data.7z ./chain-data.7z
```suggestion
          kubectl cp $(kubectl get pods | grep rpc-node | awk '{print $1}'):chain-data/chain-data.7z ./chain-data.7z
```

Is this change needed?

2021-08-31 09:20 UTC, mnaamani commented on .github/workflows/delete-node-network-pulumi.yml
> +
stack name should be an input as well.

2021-08-31 09:20 UTC, mnaamani commented on .github/workflows/create-node-network-pulumi.yml
> +          pulumi config set-all --plaintext aws:region=us-east-1 \
Also the AWS region is configured in "Configure AWS credentials" step. Should we make sure a variable is used to ensure the same value is always used here as well?

2021-09-01 05:55 UTC, mnaamani commented on .github/workflows/create-node-network-pulumi.yml
> +          kubectl cp $(kubectl get pods | grep rpc-node | awk '{print $1}'):/chain-data/chain-data.7z ./chain-data.7z
Not required.

2021-09-01 07:31 UTC, ahhda commented on .github/workflows/delete-node-network-pulumi.yml
> +
Done

2021-09-01 07:31 UTC, ahhda commented on .github/workflows/create-node-network-pulumi.yml
> +          pulumi config set-all --plaintext aws:region=us-east-1 \
Added all as inputs with default values

2022-01-03 08:21 UTC, closed without merging