Olympia query node - relations filtering
Joystream/joystream pull request #2606
Opened 2021-09-02 00:42 UTC by ondratra

**DO NOT MERGE YET**

This PR brings to query node a new feature - filtering by properties of related entities. It includes work from https://github.com/Joystream/hydra/pull/453 & https://github.com/Joystream/warthog/pull/3 into Olympia.

Some queries that work now:
```
channels(where: {videos_some: {title_eq: 'MyVideo'}}) {id}
channels(where: {videos_none: {title_eq: 'MyVideo'}}) {id}
channels(where: {videos_every: {duration_eq: 60}}) {id}
storageBags(where: {storedBy_some: {id_eq: 1}}, orderBy: [createdAt_DESC]) {id, storedBy {id}}
events(where: {type_eq: AppliedOnOpeningEvent, inBlock_eq: 1, id_eq: 1}) {inBlock, type}
```

Before merging this PR, we need to make sure PRs mentioned above are merged first, Hydra version is bumped, and Hydra dependency version is bumped in this PR as well.

2021-09-02 00:44 UTC, ondratra commented on query-node/codegen/package.json
> +    "@joystream/hydra-cli": "https://github.com/ondratra/hydra/releases/download/relation-selection-and-filtering/joystream-hydra-cli-v3.1.0-alpha.9_relationSelectionAndFiltering.tgz",
This is a temporary dependency target. I am using my repo before the feature will get merged into Hydra.

2021-09-02 10:04 UTC, Lezek123 requested changes

2021-09-02 10:04 UTC, Lezek123 commented on package.json
> +    "query-node/codegen",
This one was purposefully excluded as a workspace, since the dependencies of `hydra-cli` / `hydra-typegen` may conflict with the monorepo dependencies (for example, this causes an issue on https://github.com/Joystream/joystream/pull/2547 branch, where `@polkadot/api` was updated to `5.3.1` for the monorepo)

2022-01-12 12:13 UTC, Lezek123 commented
Superseded by https://github.com/Joystream/joystream/pull/2822

2022-01-12 12:13 UTC, closed without merging