Feature: auction extension period
Joystream/joystream pull request #2667
Opened 2021-09-15 14:19 UTC by iorveth

Closes https://github.com/Joystream/joystream/issues/2656

Depends on https://github.com/Joystream/joystream/pull/2512

2021-10-18 11:20 UTC, bedeho requested changes
- Am I correct that we are still automatically closing auctions if a buy now bid is made, even if its within the extension window? I think that is the most appropriate.
_ I think it would be useful to clearly signal in the event `AuctionBidMade`  when the auction is extended.

2021-10-18 11:20 UTC, bedeho commented on runtime-modules/content/src/nft/types.rs
> +    pub extension_period: BlockNumber,
Is providing a value of `0` the way you avoid having any extension at all?

2021-10-20 14:07 UTC, iorveth commented on runtime-modules/content/src/nft/types.rs
> +    pub extension_period: BlockNumber,
Yes, it's correct and possible in theory.
Though we also have safety bounds for both `English` `auction_duration` and `extension_period` parameters.

2021-10-20 14:08 UTC, iorveth commented on runtime-modules/content/src/nft/types.rs
> +    pub extension_period: BlockNumber,
I added additional safety check here as well https://github.com/Joystream/joystream/pull/2667/commits/5e271e3a29aac70b7be46f23eb83570c8286e4e3

2021-10-20 14:10 UTC, iorveth commented
> * Am I correct that we are still automatically closing auctions if a buy now bid is made, even if its within the extension window? I think that is the most appropriate.
>
You are correct, this features don't cause any conflict with each other 
>   _ I think it would be useful to clearly signal in the event `AuctionBidMade`  when the auction is extended.
>
Done here https://github.com/Joystream/joystream/pull/2667/commits/d6f95b93b126a3cfbcfa7b34d11859360e7e0779

2021-10-20 15:11 UTC, bedeho approved these changes
Looks good!

2021-10-20 15:11 UTC, merged