Add new operations groups to Pioneer
Joystream/joystream pull request #2707
Opened 2021-09-27 12:08 UTC by DzhideX

This PR aims to implement this issue: https://github.com/Joystream/joystream/issues/2629

Changes:
- Add WGs Alpha, Beta, Gamma to Working Groups tab. I've just copied the wording from the previous Operations group card. It may be a good idea to change this now?
- Add new WGs to proposals.
- Add new WGs to the Tokenomics tab. The Spending and Stake distribution table and charts are getting crowded but I think it shouldn't really pose a problem seeing as Pioneer v2 is almost around the corner.
- Update types.

Edit:
These issues have also been added to this PR: https://github.com/Joystream/joystream/issues/2627, https://github.com/Joystream/joystream/issues/2628

2021-09-29 11:56 UTC, Lezek123 reviewed
Looks good, just 2 additional observations:
- Runtime type name has been changed from `DAOId` to `DaoId` which is not reflected in `@joystream/types`
- The tokenomics module requires by far the most manual work when updating working groups compared to any other affected module. Since all working groups have exactly the same logic, will it be possible to refactor the tokenomics module in such a way that the overhead of updating it is minimal? First thing that comes to mind is the multiplication of `SpendingAndStakeTableRow`.

2021-09-29 11:56 UTC, Lezek123 commented on pioneer/packages/joy-proposals/src/forms/GenericWorkingGroupProposalForm.tsx
> +    let text = wgKey + 'Working Group';
I think you missed the spacebar:
```suggestion
    let text = `${wgKey} Working Group`;
```

2021-09-30 14:41 UTC, DzhideX commented
I've gone through and implemented your comments. 

One thing to note wrt `DaoId`, there are still some remaining `DAOId`'s in the code, namely:
- There's a comment in `/runtime-modules/content/src/tests/mock.rs` .
- A bunch of references in `/runtime-modules/common/src/storage.rs` and `/query-node/generated/types/typedefs.json`.

I think the rust files shouldn't be a problem but what about the `typedefs.json`?

2021-10-05 17:07 UTC, Lezek123 requested changes

2021-10-05 17:07 UTC, Lezek123 commented on pioneer/packages/joy-tokenomics/src/Overview/SpendingAndStakeDistributionTable.tsx
> +                helpContent={helpText}
```suggestion
                helpContent={lead.helpText}
```

2021-10-05 20:35 UTC, DzhideX commented
Latest changes:
- Implement distribution group in Tokenomics, Working groups section and Proposals.
- Fix lead help text in `SpendingAndStakeDistributionTable`.
- Rename `contentDirectoryWorkingGroup` to `contentWorkingGroup` where necessary.
- Comment out reserved0 and reserved1 in `/types`.

2021-10-11 08:11 UTC, Lezek123 approved these changes
Fantastic work, thank you!

2021-10-11 10:24 UTC, merged