Working group migration
Joystream/joystream pull request #2769
Opened 2021-10-15 14:45 UTC by dobertRowneySr

As discussed #2747

2021-10-18 15:41 UTC, shamil-gadelshin requested changes
A good start! I have a couple of questions and one refactoring request.

Also, I can't test it using the `run-test.sh`. Am I missing something? A manual test worked well.

2021-10-18 15:41 UTC, shamil-gadelshin commented on runtime/src/runtime_api.rs
> +// Alias for the alpha operationsworking group
We don't need this. We should import these groups from lib.rs. They are generated by the Parity's runtime macro.

2021-10-18 15:41 UTC, shamil-gadelshin commented on docker-compose.yml
> +    image: joystream/node:giza
Why do we rename this? Shouldn't we always use the latest version for the docker compose?

2021-10-18 15:41 UTC, shamil-gadelshin commented on runtime-modules/content/src/lib.rs
> +        <NextChannelCategoryId<T>>::put(T::ChannelCategoryId::one());
Why do we start it from the 1? Do we need to change ids and if yes shouldn't we start from zero?

2021-10-18 15:42 UTC, shamil-gadelshin commented
I failed to test the PR.
My steps:
1. Checkout `sumer` branch and build docker image tagged `joystream/node:latest`
2. Checkout `ignazio-bovo:runtime_migration` branch and build docker image tagged `joystream/node:giza`
3. Run `RUNTIME=latest TARGET_RUNTIME=giza ./run-tests.sh` command in the `./tests/network-tests` working directory of the `runtime_migration` branch.

My output:

```
Oct 18 15:27:06.116  INFO Building chain spec    
Oct 18 15:27:07.413  INFO 💸 new validator set of size 1 has been elected via ElectionCompute::OnChain for era 0    
Extracting wasm blob from target joystream/node image.
0aa876ccd138cc1eac57661ce3506c50d194550c552d9a5fc5f485bfb1a803c1
2021-10-18 18:27:17        METADATA: Unknown types found, no types for ContentId, ContentParameters, DataObjectStorageRelationship, DataObjectStorageRelationshipId, DataObjectType, DataObjectTypeId, NewAsset, ObjectOwner, StorageObjectOwner, UploadingStatus, VoucherLimit
Runtime Version: 9.7.0
2021-10-18 18:27:17             DRR: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
2021-10-18 18:27:17             DRR: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
2021-10-18 18:27:17             DRR: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450
      throw new Error(`Unable to decode storage ${key.section || 'unknown'}.${key.method || 'unknown'}:${entryNum}: ${error.message}`);
            ^
Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
    at RpcCore._newType (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)
    at RpcCore._formatStorageSetEntry (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:430:17)
    at /Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:410:25
    at Array.reduce (<anonymous>)
    at RpcCore._formatStorageSet (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:409:17)
    at RpcCore._formatOutput (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:379:26)
    at Object.update [as callback] (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:330:57)
    at WsProvider.value (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-provider/ws/index.cjs:284:19)
    at W3CWebSocket.value [as onmessage] (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-provider/ws/index.cjs:219:267)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/yaeti/lib/EventTarget.js:107:17)
error Command failed with exit code 1.                                                                                                                                                              
error Command failed.                                                                                                                                                                               
Exit code: 1
Command: /Users/shamix/.volta/tools/image/node/14.18.0/bin/node
Arguments: /Users/shamix/.volta/tools/image/yarn/1.22.4/lib/cli.js tsnode-strict src/status.ts
Directory: /Users/shamix/rust/joystream/substrate-runtime-joystream/utils/api-scripts
Output:

Performing runtime upgrade.
yarn workspace v1.22.4
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
yarn run v1.22.4
$ node -r ts-node/register --unhandled-rejections=strict src/dev-set-runtime-code.ts /Users/shamix/tmp/runtime.compact.wasm
WASM bytes: 2280411
2021-10-18 18:27:24        METADATA: Unknown types found, no types for ContentId, ContentParameters, DataObjectStorageRelationship, DataObjectStorageRelationshipId, DataObjectType, DataObjectTypeId, NewAsset, ObjectOwner, StorageObjectOwner, UploadingStatus, VoucherLimit
2021-10-18 18:27:24        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450
      throw new Error(`Unable to decode storage ${key.section || 'unknown'}.${key.method || 'unknown'}:${entryNum}: ${error.message}`);
            ^
Error: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
    at RpcCore._newType (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)
    at RpcCore._formatStorageData (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:399:17)
    at RpcCore._formatOutput (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:376:19)
    at callWithRegistry (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle. [...]

2021-10-19 07:21 UTC, mnaamani commented on runtime-modules/content/src/lib.rs
> +        <VideoById<T>>::remove_all();
We also want to `remove_all()` channels.

2021-10-19 07:22 UTC, mnaamani commented on runtime-modules/content/src/lib.rs
> +        <NextChannelCategoryId<T>>::put(T::ChannelCategoryId::one());
The plan was to leave next Ids untouched, but only empty the maps.

2021-10-19 07:25 UTC, mnaamani commented on runtime/src/runtime_api.rs
> +
We also need to initialize the `ContentWorkingGroup` which has been renamed from sumer runtime `ContentDirectoryWorkingGroup`

2021-10-19 08:37 UTC, mnaamani commented on runtime-modules/content/src/lib.rs
> +        <NextChannelCategoryId<T>>::put(T::ChannelCategoryId::one());
@blrhc Are we planning to reset the Categories when upgrading and recreate them?

2021-10-19 10:19 UTC, mnaamani commented on docker-compose.yml
> +    image: joystream/node:giza
I concur, here there is no need to rename

2021-10-19 11:01 UTC, mnaamani commented on tests/network-tests/run-migration-tests.sh
> +#!/usr/bin/env bash
the script file needs `chmod +x` execute permission

2021-10-19 11:05 UTC, mnaamani commented on tests/network-tests/run-migration-tests.sh
> +
The cli is a nice idea, but I was prompted to select a query-node (since it was the first time I actually ran the cli)
The test should cover the values initialized for 
```            
default_text_constraint,
default_storage_size_constraint,
default_content_working_group_mint_capacity,
```

2021-10-20 09:46 UTC, dobertRowneySr commented on runtime-modules/content/src/lib.rs
> +        <VideoById<T>>::remove_all();
I am moving this task to a separate PR as we agree during our last call

2021-10-20 13:34 UTC, ignazio-bovo commented
> I failed to test the PR. My steps:
> 
> 1. Checkout `sumer` branch and build docker image tagged `joystream/node:latest`
> 2. Checkout `ignazio-bovo:runtime_migration` branch and build docker image tagged `joystream/node:giza`
> 3. Run `RUNTIME=latest TARGET_RUNTIME=giza ./run-tests.sh` command in the `./tests/network-tests` working directory of the `runtime_migration` branch.
> 
> My output:
> 
> ```
> Oct 18 15:27:06.116  INFO Building chain spec    
> Oct 18 15:27:07.413  INFO 💸 new validator set of size 1 has been elected via ElectionCompute::OnChain for era 0    
> Extracting wasm blob from target joystream/node image.
> 0aa876ccd138cc1eac57661ce3506c50d194550c552d9a5fc5f485bfb1a803c1
> 2021-10-18 18:27:17        METADATA: Unknown types found, no types for ContentId, ContentParameters, DataObjectStorageRelationship, DataObjectStorageRelationshipId, DataObjectType, DataObjectTypeId, NewAsset, ObjectOwner, StorageObjectOwner, UploadingStatus, VoucherLimit
> Runtime Version: 9.7.0
> 2021-10-18 18:27:17             DRR: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
> 2021-10-18 18:27:17             DRR: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
> 2021-10-18 18:27:17             DRR: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
> /Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450
>       throw new Error(`Unable to decode storage ${key.section || 'unknown'}.${key.method || 'unknown'}:${entryNum}: ${error.message}`);
>             ^
> Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000003000000881300000000000000000000000000000000000000000000…8813000000000000000000000000000088130000000000000000000000000000 (72 bytes), created 0x0000000003000000881300000000000000000000000000000000000000000000…0000000000000000881300000000000000000000000000000000000000000000 (80 bytes)
>     at RpcCore._newType (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)
>     at RpcCore._formatStorageSetEntry (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:430:17)
>     at /Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:410:25
>     at Array.reduce (<anonymous>)
>     at RpcCore._formatStorageSet (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:409:17)
>     at RpcCore._formatOutput (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:379:26)
>     at Object.update [as callback] (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:330:57)
>     at WsProvider.value (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-provider/ws/index.cjs:284:19)
>     at W3CWebSocket.value [as onmessage] (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-provider/ws/index.cjs:219:267)
>     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/yaeti/lib/EventTarget.js:107:17)
> error Command failed with exit code 1.                                                                                                                                                              
> error Command failed.                                                                                                                                                                               
> Exit code: 1
> Command: /Users/shamix/.volta/tools/image/node/14.18.0/bin/node
> Arguments: /Users/shamix/.volta/tools/image/yarn/1.22.4/lib/cli.js tsnode-strict src/status.ts
> Directory: /Users/shamix/rust/joystream/substrate-runtime-joystream/utils/api-scripts
> Output:
> 
> Performing runtime upgrade.
> yarn workspace v1.22.4
> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
> yarn run v1.22.4
> $ node -r ts-node/register --unhandled-rejections=strict src/dev-set-runtime-code.ts /Users/shamix/tmp/runtime.compact.wasm
> WASM bytes: 2280411
> 2021-10-18 18:27:24        METADATA: Unknown types found, no types for ContentId, ContentParameters, DataObjectStorageRelationship, DataObjectStorageRelationshipId, DataObjectType, DataObjectTypeId, NewAsset, ObjectOwner, StorageObjectOwner, UploadingStatus, VoucherLimit
> 2021-10-18 18:27:24        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
> /Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450
>       throw new Error(`Unable to decode storage ${key.section || 'unknown'}.${key.method || 'unknown'}:${entryNum}: ${error.message}`);
>             ^
> Error: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x000000000000000000e1f5050000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
>     at RpcCore._newType (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)
>     at RpcCore._formatStorageData (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:399:17)
>     at RpcCore._formatOutput (/Users/shamix/rust/joystream/substrate-runtime-joystream/node_modules/@polkadot/rpc-core/bundle.cjs:376:19)
>     at c [...]

2021-10-20 14:54 UTC, mnaamani requested changes

2021-10-20 14:54 UTC, mnaamani commented on types/src/legacy.ts
> +  VoucherLimit
```suggestion
  VoucherLimit,
```

To fix linter error.
This would be fixed by running `yarn format` in `types/` directory.

2021-10-20 14:54 UTC, mnaamani commented on docker-compose.yml
> +    container_name: joystream-node-giza
```suggestion
    container_name: joystream-node
```

There is no need to rename the container name really.

2021-10-20 14:54 UTC, mnaamani commented on runtime/src/runtime_api.rs
> +        content::Module::<Runtime>::on_runtime_upgrade();
Is this function implemented?

And where is the call to :remove_all() on the channel and video maps ?

2021-10-20 14:54 UTC, mnaamani commented on runtime/src/runtime_api.rs
> +// Alias for the alpha operationsworking group
has this been addressed?

2021-10-20 14:54 UTC, mnaamani commented on yarn.lock
> -"@jest/console@^24.7.1", "@jest/console@^24.9.0":
Please merge giza_staging into your branch, then run `yarn build:packages` to fix the `yarn.lock` changes.

2021-10-20 15:07 UTC, mnaamani commented on runtime/src/runtime_api.rs
> +        content::Module::<Runtime>::on_runtime_upgrade();
Just to clarify we agreed to keep the ID's untouched, but we still want to clear the videos and channels maps.

2021-10-20 19:28 UTC, dobertRowneySr commented on runtime/src/runtime_api.rs
> +        content::Module::<Runtime>::on_runtime_upgrade();
Yes, Indeed. I am addressing that into the next PR

2021-10-20 20:25 UTC, dobertRowneySr commented on runtime/src/runtime_api.rs
> +// Alias for the alpha operationsworking group
I did not add this, in fac itt is present also on Sumer codebase (https://github.com/Joystream/joystream/blob/b4b674d7b5bb660d048b9c920099479d6c5d00f9/runtime/src/runtime_api.rs#L60)
Removing one of the `generic::` type alias will break all the `impl_runtime_api` macro implementation

2021-10-21 09:31 UTC, merged