Giza staging update
Joystream/joystream pull request #2774
Opened 2021-10-19 10:08 UTC by mnaamani

Update from Giza branch (include chain metadata into repo) simplifying build steps.

2021-10-19 10:46 UTC, Lezek123 commented on types/package.json
> +    "build": "git clean -xdf -e node_modules || yarn compile && yarn generate:all",
This seems to have caused an issue in CI checks, try changing `||` to `;` (see: https://github.com/Joystream/joystream/pull/2582/commits/c46c8f49561f05fcd546fb5f30ef5b0119a22f6e)

2021-10-19 12:59 UTC, mnaamani commented on types/package.json
> +    "build": "git clean -xdf -e node_modules || yarn compile && yarn generate:all",
thanks will fix

2021-10-19 13:15 UTC, mnaamani commented on types/package.json
> +    "build": "git clean -xdf -e node_modules || yarn compile && yarn generate:all",
Done in https://github.com/Joystream/joystream/pull/2774/commits/851e47d5c78b15b6c13e3dd04a5a494c8f887500 and 202aedd8acc2d7b1acde85b394f05769d4b42044

2021-10-19 16:39 UTC, Lezek123 commented on build-npm-packages.sh
> +yarn --frozen-lockfile
Oddly enough, now with `--frozen-lockfile` I'm running into issues on Ubuntu:
```
src/commands/working-groups/updateWorkerReward.ts:65:56 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(...text: string[]): string', gave the following error.
    Argument of type 'number' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(text: TemplateStringsArray, ...placeholders: string[]): string', gave the following error.
    Argument of type 'number' is not assignable to parameter of type 'TemplateStringsArray'.

65     this.log(chalk.green(`Worker ${chalk.magentaBright(workerId)} reward has been updated!`))
```
I think the magic `chalk` resolution needs to be added back

2021-10-19 17:23 UTC, Lezek123 commented on build-npm-packages.sh
> +yarn --frozen-lockfile
After adding `"chalk": "^4.0.0"` back to `resolutions` (https://github.com/Joystream/joystream/pull/2582/commits/8fe1e13a7ecbe0b2901bb236ea4239b98c3c96c6) I managed to run both `yarn build:packages` and `yarn build:apps:docker` succesfully.

2021-10-19 17:33 UTC, Lezek123 commented
Please include changes from https://github.com/Joystream/joystream/pull/2708/commits/7a299eda57cf1a2c3c04fed46e988dd620c890c0 if possible (CLI fix for uploading large files)

2021-10-20 06:08 UTC, mnaamani commented
> Please include changes from [7a299ed](https://github.com/Joystream/joystream/commit/7a299eda57cf1a2c3c04fed46e988dd620c890c0) if possible (CLI fix for uploading large files)

done in 9be96b5

2021-10-20 06:14 UTC, mnaamani commented on build-npm-packages.sh
> +yarn --frozen-lockfile
Ah its a shame that dependencies are being resolved differently on linux and mac with yarn. Perhaps we are using different versions of yarn?

If you have `volta` installed it should at least ensure we are using the same version. Can you confirm. With volta I get version `1.22.4`

2021-10-20 06:45 UTC, Lezek123 commented on build-npm-packages.sh
> +yarn --frozen-lockfile
Yes, I'm using `volta` and I've got the same version of `yarn` (`1.22.4`)

2021-10-20 07:17 UTC, Lezek123 requested changes
I'm still running into issues with `chalk`, please add it to resolutions, I already did that on `distributor-node` branch, where the issue was introduced: https://github.com/Joystream/joystream/commit/8fe1e13a7ecbe0b2901bb236ea4239b98c3c96c6

**Edit:** After some more investigation with fresh monorepo clone I found that even though initailly the `4.1.1` version of `chalk` is installed in root `node_modules`, it changes to `2.4.2` after the query-node is built, which means that probably some dependencies inside query-node autogenerated code are affecting this.

2021-10-20 07:50 UTC, mnaamani commented
Added chalk to resolutions :+1:

2021-10-20 08:34 UTC, Lezek123 approved these changes
Everything working as expected!

2021-10-20 09:25 UTC, merged