Giza - Bootstrap video and channel categories data
Joystream/joystream pull request #2781
Opened 2021-10-20 14:42 UTC by ahhda

Adds scripts to bootstrap `channelCategories` and `videoCategories` data from the Graphql endpoint.

### How to run
* `export QUERY_NODE_URL=https://hydra.joystream.org/graphql`
* `yarn workspace query-node-mappings bootstrap-data:fetch:categories`
![Screenshot 2021-10-20 at 8 11 04 PM](https://user-images.githubusercontent.com/7795956/138115414-f5481825-a22b-4a8c-953b-02ab10406d7c.png)

* Two new files `channelCategories.json` and `videoCategories.json` will be generated

2021-10-21 11:18 UTC, mnaamani requested changes
The fetching and import works perfectly.
I left a suggestion about how to deal with including the bootstrap data in the repo.

One improvement that can be made but is not critical right now is for the categories fetching script to "double check" on chain state at a particular block.

2021-10-21 11:18 UTC, mnaamani commented on query-node/.gitignore
> +mappings/bootstrap-data/data/*
I agree that it doesn't make sense to include all the bootstrapping date in the git repo.

However it seems the storage system needs some initial data.

The ideal solution would be to indeed ignore this directory and improve `query-node/mappings/bootstrap-data/index.ts` to dynamically load files if found here (generated by running the "fetch:*" script) instead of using javascript `import` statement. When file is not found, the default "json" data would be used.

2021-10-21 11:35 UTC, Lezek123 commented on query-node/.gitignore
> +mappings/bootstrap-data/data/*
The reason I chose static import is that this way we get the additional benefit of typesafety check during build, so `yarn workspace query-node-mappings build` will fail if the json data doesn't match the expected format.

2021-10-21 11:44 UTC, mnaamani commented on query-node/.gitignore
> +mappings/bootstrap-data/data/*
Yes perhaps type safety is more important.
Ok lets not .gitignore the data folder, and we just have to be sure not to check in bootstrap data.

2021-10-21 11:52 UTC, mnaamani commented on query-node/mappings/bootstrap.ts
> +  await Promise.all(channelCategories.map((m) => store.save<VideoCategory>(m)))
```suggestion
  await Promise.all(videoCategories.map((m) => store.save<VideoCategory>(m)))
```

2021-10-21 12:47 UTC, mnaamani commented on query-node/mappings/bootstrap.ts
> +      })
I think for both the ChannelCategory you must also include the other fields:
channels, createdInBlock, createdAt and updatedAt.

2021-10-21 12:48 UTC, mnaamani commented on query-node/mappings/bootstrap.ts
> +      })
As I see this error in processor when bootstrapping occurs:
```
ERROR: Stopping the proccessor due to errors: {
  "message": "null value in column \"created_in_block\" violates not-null constraint",
  "length": 354,
  "name": "QueryFailedError",
  "severity": "ERROR",
  "code": "23502",
  "detail": "Failing row contains (1, 2021-10-21 12:34:02.825962, YSVbUNz5DM, 2021-10-21 12:34:02.825962, null, null, null, 1, Film & Animation, null, 'anim':2A 'film':1A, Film & Animation).",
  "schema": "public",
  "table": "channel_category",
  "column": "created_in_block",
  "file": "execMain.c",
  "line": "1948",
  "routine": "ExecConstraints",
  "query": "INSERT INTO \"channel_category\"(\"id\", \"created_at\", \"created_by_id\", \"updated_at\", \"updated_by_id\", \"deleted_at\", \"deleted_by_id\", \"version\", \"name\", \"created_in_block\") VALUES ($1, DEFAULT, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4, DEFAULT) RETURNING \"created_at\", \"updated_at\", \"version\"",
  "parameters": [
    "1",
    "YSVbUNz5DM",
    1,
    "Film & Animation"
  ]
}
```

2021-10-21 12:49 UTC, mnaamani commented on query-node/mappings/bootstrap.ts
> +  await Promise.all(channelCategories.map((m) => store.save<VideoCategory>(m)))
~I'm not sure there are actually any mappings for VideoCategories in the query node~
I was looking in wrong place.

2021-10-21 13:28 UTC, mnaamani commented on query-node/mappings/bootstrap.ts
> +        name: m.name,
```suggestion
        name: m.name,
        channels: [],
        createdInBlock: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
```

Something like that would work.

2021-10-21 13:29 UTC, mnaamani commented on query-node/mappings/bootstrap.ts
> +        name: m.name,
```suggestion
        name: m.name,
        videos: [],
        createdInBlock: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
```

2021-10-22 11:26 UTC, mnaamani approved these changes

2021-10-22 13:55 UTC, mnaamani requested changes
I added comment with suggestion from leszek.

2021-10-22 13:55 UTC, mnaamani commented on query-node/mappings/bootstrap.ts
> +        createdInBlock: 1,
@Lezek123 recommended that we should fetch the actual values when fetching the categories.

2021-10-22 18:50 UTC, mnaamani approved these changes

2021-10-22 18:51 UTC, merged