Refactor distribution buckets (with extra state).
Joystream/joystream pull request #2797
Opened 2021-10-26 10:53 UTC by shamil-gadelshin

#### Changes
- updated distribution bucket storage (from distribution type family container to a double map)
- introduced a new type - `DistributionBucketState`
- types

#### Review comments
- This is the second option for the distribution bucket family changes ([this is the first one](https://github.com/Joystream/joystream/pull/2792))

2021-10-27 06:25 UTC, Lezek123 requested changes

2021-10-27 06:25 UTC, Lezek123 commented on types/src/storage.ts
> +export class DistributionBucketState
Please add the new type to `storageTypes` const below and regenerate `defs.json`

2021-10-27 06:28 UTC, Lezek123 commented on types/src/storage.ts
> +export class DistributionBucketState
Also please update `chain-metadata.json` with `yarn update-chain-metadata`

2021-10-27 09:21 UTC, shamil-gadelshin commented on types/src/storage.ts
> +export class DistributionBucketState
Fixed.

2021-10-27 13:19 UTC, Lezek123 approved these changes
LGTM
Didn't encounter any issues during my local tests

2021-11-25 15:07 UTC, bedeho approved these changes
Approved, with 2nd review of core concept later.

2021-12-06 15:32 UTC, shamil-gadelshin commented
Superseded by https://github.com/Joystream/joystream/pull/2897

2021-12-06 15:32 UTC, closed without merging