Giza fix working group enum
Joystream/joystream pull request #2804
Opened 2021-10-28 10:51 UTC by mnaamani

We concluded that chancing the enum variant ordering for WorkingGroup type in a runtime upgrade while existing state (proposals) references the WorkingGroup vlaue should be avoided.

2021-10-29 15:25 UTC, shamil-gadelshin requested changes
The build is failing because of the typo. Please, fix it.

2021-10-29 15:25 UTC, shamil-gadelshin commented on types/src/common.ts
>  export class WorkingGroup extends JoyEnum({
Could be just `WorkingGroupDef` without expanding.

2021-10-29 15:25 UTC, shamil-gadelshin commented on runtime-modules/common/src/working_group.rs
> +    Distributione,
Here is the typo that affects the building process (check failed github actions)

2021-11-02 16:33 UTC, mnaamani commented on runtime-modules/common/src/working_group.rs
> +    Distributione,
Thanks for spotting this.
Fixed in 43d27f230c67c493e301ebaf44d6479ac6fd11ca

2021-11-02 16:34 UTC, mnaamani commented on types/src/common.ts
>  export class WorkingGroup extends JoyEnum({
fixed in ca4b7d778cf2235c529ad52e2c57cc3814e04864
Tested in pioneer proposal creation

2021-11-03 08:59 UTC, shamil-gadelshin approved these changes
LGTM

Tested with storage node scripts including:
`yarn storage-node leader:update-bag -a=0 -i static:wg:distribution --dev` that covers the use cases for this PR.

2021-11-03 09:00 UTC, merged