DevOps - Separate stack for deploying a Kubernetes cluster
Joystream/joystream pull request #2831
Opened 2021-11-15 11:09 UTC by ahhda

2021-11-16 11:44 UTC, ahhda commented
@mnaamani Please review

2021-11-18 12:01 UTC, mnaamani commented on devops/kubernetes/node-network/index.ts
> +  const provider = await getProvider(clusterStackRef)
I'm getting a compiler error at this line when trying to bring up the stack:
```
Previewing update (network):
     Type                 Name                  Plan       Info
 +   pulumi:pulumi:Stack  node-network-network  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (node-network-network):
    error: Running program '/Users/mokhtar/joystream/joystream/devops/kubernetes/node-network' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(14,38): error TS2345: Argument of type 'import("/Users/mokhtar/joystream/joystream/devops/kubernetes/node-network/node_modules/@pulumi/pulumi/stackReference").StackReference' is not assignable to parameter of type 'import("/Users/mokhtar/joystream/joystream/devops/kubernetes/node-network/node_modules/pulumi-common/node_modules/@pulumi/pulumi/stackReference").StackReference'.
      Types have separate declarations of a private property 'readOutputValue'.
    index.ts(15,47): error TS2345: Argument of type 'import("/Users/mokhtar/joystream/joystream/devops/kubernetes/node-network/node_modules/@pulumi/pulumi/stackReference").StackReference' is not assignable to parameter of type 'import("/Users/mokhtar/joystream/joystream/devops/kubernetes/node-network/node_modules/pulumi-common/node_modules/@pulumi/pulumi/stackReference").StackReference'.
```

2021-11-18 12:11 UTC, mnaamani requested changes
I'm not able to fully test this because of the compiler issue, but a comment on general approach.

When deploying a new stack to a k8 provider, the ability to reference a cluster by pulumi specific stack name is very handy (such as an aws eks cluster we deployed with his new cluster stack), but it shouldn't be the only way. We may not have deployed a kubernetes cluster via pulumi.

We need an additional option of passing a reference to a `kubeconfig` file, to make it as general as possible. Can this be done and are there any downsides to this approach?

2021-11-18 12:11 UTC, mnaamani commented on devops/kubernetes/cluster/index.ts
> +} else if (platform === 'aws') {
I think the following parameters should be configurable when deploying the cluster:

- number of availability zones
- the cluster name
- instanceType

2021-12-27 08:37 UTC, ahhda commented
> We need an additional option of passing a reference to a `kubeconfig` file, to make it as general as possible. Can this be done and are there any downsides to this approach?

Sounds like a good idea to me. Added the feature 👍

2022-01-06 07:23 UTC, mnaamani requested changes

2022-01-06 07:23 UTC, mnaamani commented on devops/kubernetes/cluster/index.ts
> +if (platform === 'minikube') {
Looking back at these options and trying things out, it doesn't seem necessary to me to have to create a pulumi stack when the provider is just going to be "local" cluster. So I suggest we drop the minikube option, and this script should only deploy clusters to aws, and later maybe add support for google and azure.

2022-01-06 07:23 UTC, mnaamani commented on devops/kubernetes/node-network/index.ts
> +    isMinikube = false
Assumption that passing a kubeconfig file automatically means it is a cloud provider is not correct.
I can for example pass the default kubeconfig file path or a custom config at an arbitrary location with:
```
KUBECONFIG=/tmp/mini-kubeconfig minikube start
or
KUBECONFIG=/tmp/kind-kubeconfig kind create
```

Determining if the selected cluster is a cloud provider or a local cluster (minikube or kind) should be done by inspecting the kubeconfig instead.

2022-01-06 07:23 UTC, mnaamani commented on devops/kubernetes/node-network/index.ts
> +  let isMinikube: boolean = false
I think we should drop the minikube config but replace it with `useLocalProvider` for user to have freedom to just use the currently selected context in their default kubeconfig?

2022-01-06 07:27 UTC, mnaamani commented
if I create a cloud cluster stack, and then the node-network stack which references the cluster stack, what happens when I run `pulumi destroy` on the node-network stack. Will it also destroy the cluster stack?

2022-01-06 07:36 UTC, ahhda commented
> if I create a cloud cluster stack, and then the node-network stack which references the cluster stack, what happens when I run `pulumi destroy` on the node-network stack. Will it also destroy the cluster stack?

It will only destroy the resources created by the `node-network` stack and not the cluster.

2022-03-04 06:35 UTC, closed without merging