Giza distribution bucket changes.
Joystream/joystream pull request #2897
Opened 2021-12-06 11:04 UTC by shamil-gadelshin

2021-12-07 10:36 UTC, Lezek123 requested changes

2021-12-07 10:36 UTC, Lezek123 commented on types/src/storage.ts
> +  implements IDistributionBucketState {}
I couldn't find this type defined anywhere in the runtime

2021-12-07 15:12 UTC, shamil-gadelshin commented on types/src/storage.ts
> +  implements IDistributionBucketState {}
This is dead code. I removed it here 14c4633

2021-12-08 16:47 UTC, bedeho approved these changes
This looks good to me, approving under the assumption that there will be fix later which introduces the ability, and perhaps replaces wholesale the current permissive mode, to create dynamic bags which are guaranteed to be stored and distributed in a policy compliant way.

2021-12-08 16:47 UTC, bedeho commented on runtime-modules/storage/src/lib.rs
> +pub type DistributionBucketId<T> = DistributionBucketIdRecord<
Is it risky, or confusing, to have `DistributionBucketId` and `DistributionBucketIndex` denote distinct but intimately related concepts? This caused me a bit of confusion when reading through.

Perhaps the latter could be something like `WithinFamilyDistributionBucketId` or something? just a tip, you decide what you want to do.

2021-12-08 16:47 UTC, bedeho commented on runtime-modules/storage/src/random_buckets/storage_bucket_picker.rs
> +    // Selects storage bucket ID sets to assign to the storage bucket.
`assign to the bag`

2021-12-09 11:06 UTC, shamil-gadelshin commented on runtime-modules/storage/src/random_buckets/storage_bucket_picker.rs
> +    // Selects storage bucket ID sets to assign to the storage bucket.
Fixed.

2021-12-09 11:08 UTC, shamil-gadelshin commented on runtime-modules/storage/src/lib.rs
> +pub type DistributionBucketId<T> = DistributionBucketIdRecord<
`DistributionBucketIndex` seemed to satisfy the rest of the team. So, I tend to keep the name for now.

2021-12-09 11:08 UTC, merged