DevOps - Github action to deploy node network
Joystream/joystream pull request #2991
Opened 2022-01-05 14:47 UTC by ahhda

Using CloudFormation and Ansible

2022-01-31 13:58 UTC, mnaamani commented
Looks good, just a couple of suggestions.

Who can access the artifacts. I know you have to be signed into github, but then who has permission to fetch them?

2022-01-31 14:01 UTC, mnaamani requested changes
deploy-node-network is note really the best name really for the action.
I suggest to rename it to just `Deploy Network` (similar to our other action `Deploy Playground`)

2022-01-31 14:01 UTC, mnaamani commented on .github/workflows/deploy-node-network.yml
> +                          initial_balances_file=${{ steps.myoutputs.outputs.initialBalancesFilePath }}"
there was a variable also to select staging or production type

2022-01-31 14:01 UTC, mnaamani commented on .pipelines/deploy-node-network-inputs.json
> +  }
I think we should probably have a password here that can be passed to encrypt the artifact files produces with the secrets generated. Or we can keep it simple, don't include secrets in the artifact, just the chainspec and expect the user to ssh into the build instance and get the necessary files?

2022-01-31 14:01 UTC, mnaamani commented on .github/workflows/deploy-node-network.yml
> +                          initial_balances_file=${{ steps.myoutputs.outputs.initialBalancesFilePath }}"
I recently tested the deploy-infra script where I omitted the initial members file but somehow the playbook still tried adding the argument to include in the chain spec builder. Perhaps you can look into that. I had updated to latest version of ansible maybe that has something to do with it.

2022-02-01 06:22 UTC, ahhda commented
> Who can access the artifacts. I know you have to be signed into github, but then who has permission to fetch them?

Anyone logged into Github can access and download the artifacts for a public repository.

2022-02-01 07:50 UTC, ahhda commented on .pipelines/deploy-node-network-inputs.json
> +  }
Added `encryptionKey` parameter

2022-02-01 10:55 UTC, merged