Migration scripts: allow non-sudo transactions
Joystream/joystream pull request #3034
Opened 2022-01-13 11:41 UTC by traumschule

For the ongoing the [Giza test](https://github.com/traumschule/community-repo/tree/giza-testing/working-groups/operations-group/Giza-testing#storage-1) i tried to use #2819.

Because it requires a `sudo` key i modified `ChannelsMigration.ts` and `VideosMigration.ts` to let a member perform the transactions.
```
$ /root/joystream/node_modules/.bin/migration-scripts sumer-giza:migrateContent -c 2 3
Sudo key: 5Ev8KjT9UYvi1Joe8vvDCuK4YvFFSBH5MZQpKGzrcjLF5CLy
Our key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY (member 207)
Fetching a batch of 2 channels...
All channels in this batch were already migrated (2/2)
Added 39 video ids to the list of videos to migrate
Sudo key: 5Ev8KjT9UYvi1Joe8vvDCuK4YvFFSBH5MZQpKGzrcjLF5CLy
Our key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY (member 207)
Fetching a batch of 20 videos...
Sending utility.batch extrinsic from 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
Video map entries added! [
  [ 1, 807 ],   [ 2, 808 ],
  [ 3, 809 ],   [ 4, 810 ],
  [ 5, 811 ],   [ 12, 812 ],
  [ 13, 813 ],  [ 14, 814 ],
  [ 15, 815 ],  [ 16, 816 ],
  [ 17, 817 ],  [ 18, 818 ],
  [ 19, 819 ],  [ 20, 820 ],
  [ 21, 821 ],  [ 275, 822 ],
  [ 484, 823 ], [ 948, 824 ],
  [ 981, 825 ], [ 1266, 826 ]
]
Uploading 40 data objects...
Upload of object 2192 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
...
Upload of object 2221 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
Fetching a batch of 19 videos...
Sending utility.batch extrinsic from 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
Video map entries added! [
  [ 6495, 827 ], [ 6814, 828 ],
  [ 6854, 829 ], [ 6920, 830 ],
  [ 7048, 831 ], [ 7410, 832 ],
  [ 7411, 833 ], [ 7412, 834 ],
  [ 7413, 835 ], [ 7652, 836 ],
  [ 8139, 837 ], [ 8140, 838 ],
  [ 8141, 839 ], [ 8162, 840 ],
  [ 8443, 841 ], [ 8827, 842 ],
  [ 8848, 843 ], [ 8849, 844 ],
  [ 8850, 845 ]
]
Uploading 78 data objects...
Upload of object 2192 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
...
Upload of object 2219 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
  C-c                                                                              

$ /root/joystream/node_modules/.bin/migration-scripts sumer-giza:migrateContent -c 2 3
Sudo key: 5Ev8KjT9UYvi1Joe8vvDCuK4YvFFSBH5MZQpKGzrcjLF5CLy
Our key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY (member 207)
Fetching a batch of 2 channels...
All channels in this batch were already migrated (2/2)
Added 39 video ids to the list of videos to migrate
Sudo key: 5Ev8KjT9UYvi1Joe8vvDCuK4YvFFSBH5MZQpKGzrcjLF5CLy
Our key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY (member 207)
All videos already migrated, skippping...
Done in 8.83s.

# yarn migration-scripts sumer-giza:retryFailedUploads -f utils/migration-scripts/results/sumer-giza/channelsMigrationFailedUploads_1642061324133.json 
yarn run v1.22.4
$ /root/joystream/node_modules/.bin/migration-scripts sumer-giza:retryFailedUploads -f utils/migration-scripts/results/sumer-giza/channelsMigrationFailedUploads_1642061324133.json
Uploading 4 data objects...
Upload of object 2188 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
Upload of object 2189 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
Upload of object 2190 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
Upload of object 2191 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
Done in 6.69s.
```

The updated version behaves a bit differently:
```
$ /root/joystream/node_modules/.bin/migration-scripts sumer-giza:migrateContent -c 4 5 6
2022-01-13 09:54:32:5432 Assets Manager [info]: Failed/pending uploads will be saved to /root/joystream/utils/migration-scripts/results/sumer-giza/unprocessedUploads_1642067672225.json
Sudo key: 5Ev8KjT9UYvi1Joe8vvDCuK4YvFFSBH5MZQpKGzrcjLF5CLy
Our key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY (member 207)
2022-01-13 09:54:32:5432 Channels migration [info]: Fetching a batch of 3 channels...
Error: Could not fetch asset 5DSuctx2Tu4fHo66pYBmEh5HBV8PZiLHebDdTtN6KNforip7 from any provider. Last error: timeout of 5000ms exceeded
    at AssetsManager.fetchAssetWithRetry (/root/joystream/utils/migration-scripts/src/sumer-giza/AssetsManager.ts:212:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
    at AssetsManager.prepareAsset (/root/joystream/utils/migration-scripts/src/sumer-giza/AssetsManager.ts:133:18)
    at /root/joystream/utils/migration-scripts/src/sumer-giza/AssetsManager.ts:164:24
    at async Promise.all (index 0)
    at AssetsManager.prepareAssets (/root/joystream/utils/migration-scripts/src/sumer-giza/AssetsManager.ts:159:5)
    at ChannelMigration.prepareChannel (/root/joystream/utils/migration-scripts/src/sumer-giza/ChannelsMigration.ts:145:28)

# yarn migration-scripts sumer-giza:retryFailedUploads -f utils/migration-scripts/results/sumer-giza/videosMigrationFailedUploads_1642065850907.json 
yarn run v1.22.4
$ /root/joystream/node_modules/.bin/migration-scripts sumer-giza:retryFailedUploads -f utils/migration-scripts/results/sumer-giza/videosMigrationFailedUploads_1642065850907.json
2022-01-13 09:56:42:5642 Assets Manager [info]: Failed/pending uploads will be saved to utils/migration-scripts/results/sumer-giza/unprocessedUploads_1642067802456.json
2022-01-13 09:56:42:5642 Assets Manager [info]: Uploading 78 data objects...
2022-01-13 09:56:42:5642 Assets Manager [error]: Upload of object 2192 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
...
2022-01-13 09:57:02:572 Assets Manager [error]: Upload of object 2213 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
2022-01-13 09:57:03:573 Assets Manager [error]: Upload of object 2219 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
Killed
error Command failed with exit code 137.
```

Maybe i do not understand the new system enough but the script seems to assume that the local provider holds the same bucket the new assets get assigned to?

Creation of channels (https://giza-l1dev.joystream.app/#/explorer/query/315051) and videos (https://giza-l1dev.joystream.app/#/explorer/query/315762) works, just the uploads fail.

I did not try to apply f6bd4c9871f1491bd0d781560c947c95781c1aec yet.

2022-01-13 13:45 UTC, Lezek123 commented
> Error: Could not fetch asset 5DSuctx2Tu4fHo66pYBmEh5HBV8PZiLHebDdTtN6KNforip7 from any provider. Last error: timeout of 5000ms exceeded

This should be solved by https://github.com/Joystream/joystream/commit/f6bd4c9871f1491bd0d781560c947c95781c1aec

> Maybe i do not understand the new system enough but the script seems to assume that the local provider holds the same bucket the new assets get assigned to?

The target storage node endpoint for the uploads can be specified with `--uploadSpEndpoint` flag and the bucket id can be provided through `--uploadSpBucketId` flag. By default they are `http://localhost:3333` and `0` respectively.

See `yarn migration-scripts sumer-giza:migrateContent --help` or [README](https://github.com/Joystream/joystream/blob/giza_staging/utils/migration-scripts/README.md)

The only assumption made is that all objects will get assigned to the specified bucket and that the bucket can hold all the assets, which is going to be a precondition for the migration, before the assets are actually split between different buckets through, for example, `update-bag` command later.

> 2022-01-13 09:56:42:5642 Assets Manager [error]: Upload of object 2192 to http://localhost:3333 failed: {"type":"upload","message":"Error: Incorrect storage bucket ID."}

Those errors indicate a mismatch between `--uploadSpBucketId` and `--uploadSpEndpoint` (since you didn't provide any explicit values, the defaults are used, so this means your local node is not supporting bucket `0`)

2022-01-13 13:59 UTC, Lezek123 requested changes

2022-01-13 13:59 UTC, Lezek123 commented on utils/migration-scripts/src/sumer-giza/BaseMigration.ts
> +    const key = keyring.createFromUri(sudoUri)
This varaible can no longer be called `sudoUri` in that case. Perhaps it should be called `senderUri` instead.

2022-01-13 13:59 UTC, Lezek123 commented on utils/migration-scripts/src/sumer-giza/BaseMigration.ts
> +    }
`createFromUri` either returns a non-empty `KeyringPair` or throws, so no additional check should be needed
```suggestion
    const key = keyring.createFromUri(sudoUri)
```

2022-01-13 13:59 UTC, Lezek123 commented on utils/migration-scripts/src/sumer-giza/BaseMigration.ts
> +    console.debug(`Sudo key: ${sudoKey.toString()}`)
```suggestion
    this.logger.debug(`Sudo key: ${sudoKey.toString()}`)
```

2022-01-13 13:59 UTC, Lezek123 commented on utils/migration-scripts/src/sumer-giza/BaseMigration.ts
> +    console.debug(`Using key: ${key.address} (member ${this.member.id})`)
```suggestion
    this.logger.debug(`Using key: ${key.address} (member ${this.member.id})`)
```

2022-01-13 13:59 UTC, Lezek123 commented on utils/migration-scripts/src/sumer-giza/ChannelsMigration.ts
> +      this.isSudo ? api.tx.sudo.sudoAs(ownerMember.controllerAccount, tx) : tx,
This will not be correctly processed by `extractFailedMigrations`, which assumes `sudoAs` is used

2022-01-13 13:59 UTC, Lezek123 commented on utils/migration-scripts/src/sumer-giza/VideosMigration.ts
> +      this.isSudo ? api.tx.sudo.sudoAs(this.sudo, tx) : tx,
This will not be correctly processed by `extractFailedMigrations`, which assumes `sudoAs` is used

2022-01-14 07:28 UTC, traumschule commented
The goal of above mentioned test is to overload the SP and later Distributor. This script needs some more tweaks for that.

It may be beyond the scope of this PR to add functionality that determines the bucket and provider per `bagId`. For now this query has to be executed manually:

[giza-l1dev.joystream.app/graphql](https://giza-l1dev.joystream.app/graphql)
```
query {
storageBuckets(
    where: {
      operatorStatus_json: { isTypeOf_eq: "StorageBucketOperatorStatusActive" }
      bags_some: { id_eq: "dynamic:channel:339" }
      operatorMetadata: { nodeEndpoint_contains: "http" }
    }
  ) {
  id
  operatorMetadata {
    nodeEndpoint
  }
  }
}

Response:
{
  "data": {
    "storageBuckets": [
      {
        "id": "4",
        "operatorMetadata": {
          "nodeEndpoint": "https://giza-staging-b.joystream.app/storage/"
        }
      }
    ]
  }
}
```

Channel and videos were created and uploads failed before. Exits successfully however.
`yarn migration-scripts sumer-giza:migrateContent -c 7 --wsProviderEndpointUri wss://giza-l1dev.joystream.app/rpc --uploadSpEndpoint https://giza-l1dev.joystream.app/storage --uploadSpEndpoint https://giza-tomato.joystream.app/storage/ --uploadSpBucketId 6`
```
2022-01-14 05:42:59:4259 Assets Manager [info]: Failed/pending uploads will be saved to /home/pioneer/joystream/utils/migration-scripts/results/sumer-giza/unprocessedUploads_1642138979565.json
2022-01-14 05:42:59:4259 Channels migration [info]: Fetching 1 channel(s)
2022-01-14 05:43:00:430 Channels migration [info]: All channels in this batch were already migrated (1/1)
```

Retry using wrong bucket/SP.
`yarn migration-scripts sumer-giza:retryFailedUploads -f results/sumer-giza/unprocessedUploads_1642137335755.json  --wsProviderEndpointUri wss://giza-l1dev.joystream.app/rpc --uploadSpEndpoint https://giza-l1dev.joystream.app/storage --uploadSpEndpoint https://giza-tomato.joystream.app/storage/ --uploadSpBucketId 6`
```
2022-01-14 05:49:01:491 Assets Manager [info]: Failed/pending uploads will be saved to results/sumer-giza/unprocessedUploads_1642139341373.json
2022-01-14 05:49:01:491 Assets Manager [info]: Uploading 2 data objects...
2022-01-14 05:49:07:497 Assets Manager [error]: Uploading object 2270 (dynamic:channel:339) to https://giza-tomato.joystream.app/storage/: {"type":"upload","message":"Error: Extrinsic execution error: StorageBucketIsNotBoundToBag ( The requested storage bucket is not bound to a bag.)"}
2022-01-14 05:49:07:497 Assets Manager [error]: Uploading object 2271 (dynamic:channel:339) to https://giza-tomato.joystream.app/storage/: {"type":"upload","message":"Error: Extrinsic execution error: StorageBucketIsNotBoundToBag ( The requested storage bucket is not bound to a bag.)"}
```

Correct bucket on wrong SP. The provider does not know the correct address, does it?
`yarn migration-scripts sumer-giza:retryFailedUploads -f results/sumer-giza/unprocessedUploads_1642137335755.json --wsProviderEndpointUri wss://giza-l1dev.joystream.app/rpc --uploadSpEndpoint https://giza-l1dev.joystream.app/storage --uploadSpEndpoint https://giza-tomato.joystream.app/storage/ --uploadSpBucketId 4 -l debug`
```
2022-01-14 05:53:29:5329 Assets Manager [info]: Failed/pending uploads will be saved to results/sumer-giza/unprocessedUploads_1642139609427.json
2022-01-14 05:53:29:5329 Assets Manager [info]: Uploading 2 data objects...
2022-01-14 05:53:30:5330 Assets Manager [error]: Uploading object 2270 (dynamic:channel:339) to https://giza-tomato.joystream.app/storage/: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
2022-01-14 05:53:30:5330 Assets Manager [error]: Uploading object 2271 (dynamic:channel:339) to https://giza-tomato.joystream.app/storage/: {"type":"upload","message":"Error: Incorrect storage bucket ID."}
```

Success.
`migration-scripts sumer-giza:retryFailedUploads -f results/sumer-giza/unprocessedUploads_1642137335755.json --wsProviderEndpointUri wss://giza-l1dev.joystream.app/rpc --uploadSpEndpoint https://giza-l1dev.joystream.app/storage --uploadSpEndpoint https://giza-staging-b.joystream.app/storage/ --uploadSpBucketId 4 -l debug`
```
2022-01-14 05:56:53:5653 Assets Manager [info]: Failed/pending uploads will be saved to results/sumer-giza/unprocessedUploads_1642139813151.json
2022-01-14 05:56:53:5653 Assets Manager [info]: Uploading 2 data objects...
2022-01-14 05:57:01:571 Assets Manager [debug]: results/sumer-giza/unprocessedUploads_1642139813151.json updated
{
    "queueSize": 1
}
2022-01-14 05:57:01:571 Assets Manager [debug]: results/sumer-giza/unprocessedUploads_1642139813151.json updated
{
    "queueSize": 0
}
```

Fail. Next channel gets assigned to new provider / bucket which requires manual lookup again.
`yarn migration-scripts sumer-giza:migrateContent -c 8 --wsProviderEndpointUri wss://giza-l1dev.joystream.app/rpc --uploadSpEndpoint https://giza-l1dev.joystream.app/storage --uploadSpEndpoint https://giza-staging-b.joystream.app/storage --uploadSpBucketId 4`
```
2022-01-14 06:39:18:3918 Channels migration [info]: Fetching 1 channel(s)
2022-01-14 06:39:18:3918 Assets Manager [debug]: Trying to fetch asset 5GCinX6a5zMttvbPLa9BDuN8485V44Q7v1r6TWrKzr3emcmC from https://storage-1.joystream.org/storage...
2022-01-14 06:39:18:3918 Assets Manager [debug]: Trying to fetch asset 5CT3xXijtqeG19AL5Pv8kQsJoRGvdzvhMNqVvEoZjjMqPqVa from https://storage-1.joystream.org/storage...
207
Sending utility.batch extrinsic from 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
2022-01-14 06:39:38:3938 Channels migration [info]: Channel map entries added!
{
    "newChannelMapEntries": [
        [
            8,
            340
        ]
    ]
}
2022-01-14 06:39:38:3938 Assets Manager [debug]: /home/pioneer/joystream/utils/migration-scripts/results/sumer-giza/unprocessedUploads_1642142358436.json updated
{
    "queueSize": 1
}
2022-01-14 06:39:38:3938 Assets Manager [debug]: /home/pioneer/joystream/utils/migration-scripts/results/sumer-giza/unprocessedUploads_1642142358436.json updated
{
    "queueSize": 2
}
2022-01-14 06:39:38:3938 Assets Manager [info]: Added 2 new data object uploads to the upload queue
2022-01-14 06:39:38:3938 Assets Manager [info]: Uploading 2 data objects...
2022-01-14 06:39:42:3942 Assets Manager [error]: Uploading object 2272 (dynamic:channel:340) to https://giza-staging-b.joystream.app/storage: {"type":"upload","message":"Error: Extrinsic execution error: StorageBucketIsNotBoundToBag ( The requested storage bucket is not bound to a bag.)"}
2022-01-14 06:39:42:3942 Assets Manager [error]: Uploading object 2273 (dynamic:channel:340) to https://giza-staging-b.joystream.app/storage: {"type":"upload","message":"Error: Extrinsic execution error: StorageBucketIsNotBoundToBag ( The requested storage bucket is not bound to a bag.)"}
```

Lookup
```
"storageBuckets": [
      {
        "id": "8",
        "operatorMetadata": {
          "nodeEndpoint": "https://giza-katefm.joystream.app/storage/"
```

Retry fails because scripts believes everything is fine.
```
yarn migration-scripts sumer-giza:migrateContent -c 8 --wsProviderEndpointUri wss://giza-l1dev.joystream.app/rpc --uploadSpEndpoi\
nt https://giza-l1dev.joystream.app/storage --uploadSpEndpoint https://giza-katefm.joystream.app/storage --uploadSpBucketId 8
2022-01-14 06:49:52:4952 Channels migration [info]: Fetching 1 channel(s)
2022-01-14 06:49:52:4952 Channels migration [info]: All channels in this batch were already migrated (1/1)
```

## Improvements

- automatically determine bucket / SP per back (see )
- make retries more handy: pick up unprocessed / failed files and continue automatically, do not expect passing of timestamped files
- check if asserts are successfully uploaded (HEAD request)
- load params from `.env`

Out of scope: informative / machine readable error messages. Pro: Helps humans and scripts. Contra: Puts the burden on providers who are under load already.
- "Error: Incorrect storage bucket ID." > "Error: Bag $bagId is assigned to N storage prov [...]

2022-01-21 18:08 UTC, traumschule commented
TLDR; for @bwhm
This PR uploads in Alice name if no sudo key is given. it fails however because specific bucketId and providerurl are expected - they change however for every created channel (see [comment](#issuecomment-1012843098)).

2024-01-05 08:00 UTC, closed without merging