Fix compile time proposal params config
Joystream/joystream pull request #3275
Opened 2022-02-21 08:59 UTC by mnaamani

Fixes https://github.com/Joystream/joystream/issues/3273

2022-02-21 14:40 UTC, shamil-gadelshin requested changes
Looks good. There are a couple of minor comments. It looks like there are clippy issues as well present in the code.

I corrupted the `./tests/integration-tests/proposal-parameters.json` file, ran the `./build-node-docker.sh`, and expected the build to fail but it was OK.

2022-02-21 14:40 UTC, shamil-gadelshin commented on runtime/src/proposals_configuration/mod.rs
> +    if json_str.is_none() || json_str.unwrap().is_empty() {
The `unwap()` method should be avoided in the production code. The first part of the condition `.is_none()` could be modified and we would end up with panic. Using the `map_or` looks like a safer approach.

2022-02-21 14:40 UTC, shamil-gadelshin commented on runtime/src/proposals_configuration/mod.rs
> +                if cfg!(test) {
Why do we allow invalid JSON in non-test cases?

2022-02-22 09:15 UTC, mnaamani commented on runtime/src/proposals_configuration/mod.rs
> +                if cfg!(test) {
I was trying to follow the description of the expected behavior in https://github.com/Joystream/joystream/blob/8bb0a84bc822eb817401e8ddd0f00e1613a40ccb/runtime/src/proposals_configuration/mod.rs#L6

2022-02-22 09:20 UTC, mnaamani commented
> Looks good. There are a couple of minor comments. It looks like there are clippy issues as well present in the code.
> 

The clippy warning are because I commented out the proposals_integration module in `runtime/src/tests/mod.rs` but didn't comment out some common code which was being used from those tests.

> I corrupted the `./tests/integration-tests/proposal-parameters.json` file, ran the `./build-node-docker.sh`, and expected the build to fail but it was OK.

Did you run with `TEST_NODE=true ./build-node-docker.sh` ?

2022-02-22 12:18 UTC, mnaamani commented on runtime/src/proposals_configuration/mod.rs
> +                if cfg!(test) {
But if we want compile time and runtime behavior to be the same, I can drop the condition `cfg!(test)` and always return `None` here.

2022-02-22 12:35 UTC, mnaamani commented on runtime/src/proposals_configuration/mod.rs
> +    if json_str.is_none() || json_str.unwrap().is_empty() {
Fixed in 565dd4f536bb879de3dad829fa64656f7e98f7a3

2022-02-22 14:27 UTC, mnaamani commented on runtime/src/proposals_configuration/mod.rs
> +                if cfg!(test) {
As discussed reverted to panic, and updated the comments to reflect actual behavior

2022-02-23 08:41 UTC, merged

2022-02-23 08:41 UTC, shamil-gadelshin reviewed
LGTM