Olympia add `WorkingGroupOpeningMetadata.title`
Joystream/joystream pull request #3386
Opened 2022-03-11 08:10 UTC by thesan

See Joystream/pioneer#2395

2022-03-11 11:46 UTC, ondratra approved these changes
LGTM

2022-03-14 10:08 UTC, Lezek123 requested changes
I know it's not within the scope of this PR, but I noticed that working group opening metadata processing is not secured against `/u0000` character.

Could you perhaps make it part of `deserializeMetadata` to iterate over all metadata fields and make sure that in case `typeof field === 'string'` it's beeing santizied with `prepareString`?

2022-03-14 10:08 UTC, Lezek123 commented on query-node/mappings/src/workingGroups.ts
> +    title: title ?? undefined,
This is a minor inconsistency with other fields (like `description` etc.), where empty string (`''`) is treated as _no-value_ (`null`)

2022-03-15 07:12 UTC, Lezek123 requested changes

2022-03-15 07:12 UTC, Lezek123 commented on query-node/mappings/src/common.ts
> +import { AnyMessage, AnyMetadataClass, DecodedMetadataObject } from '@joystream/metadata-protobuf/types'
Unused import
```suggestion
import { AnyMetadataClass, DecodedMetadataObject } from '@joystream/metadata-protobuf/types'
```

2022-03-15 07:12 UTC, Lezek123 commented on query-node/mappings/src/common.ts
> +      if (message.hasOwnProperty(key) && typeof message[key] === 'string') {
Linter error
```suggestion
      if (key in message && typeof message[key] === 'string') {
```

2022-03-15 07:12 UTC, Lezek123 commented on query-node/mappings/src/common.ts
> +        message[key] = bytesToString(message[key])
```suggestion
        message[key] = prepareString(message[key])
```

2022-03-15 08:57 UTC, thesan commented
@Lezek123 sorry about that commit last night, I was pretty tired :sweat_smile:

2022-03-15 12:25 UTC, Lezek123 approved these changes
LGTM!

2022-03-15 12:26 UTC, merged