Rhodes QN NFT's creator channel shortcut
Joystream/joystream pull request #3405
Opened 2022-03-15 08:37 UTC by zeeshanakram3

resolves this #3314

2022-03-15 23:35 UTC, ondratra requested changes
Feature's core is done. Only make small tweaks as requested in the comments, please.

2022-03-15 23:35 UTC, ondratra commented on tests/network-tests/src/scenarios/content-directory.ts
> +  )
This change is not needed after changes from https://github.com/Joystream/joystream/pull/3421 are merged into rhodes. Storage node, as well as storage working group leader, will be available. Please revert this change; you can merge #3421 into this branch to make it work again.

2022-03-15 23:35 UTC, ondratra commented on query-node/mappings/src/content/nft.ts
> +    creatorChannel: creatorChannel,
```suggestion
    creatorChannel: video.channel,
```
There's no need for loading of `creatorChannel` via `getById`. We can rely on `channel` being loaded in `video` (you've ensured that with your change on lane `527`).

2022-03-16 22:59 UTC, ondratra approved these changes

2022-03-16 22:59 UTC, ondratra approved these changes

2022-03-23 19:11 UTC, kdembler approved these changes

2022-03-23 19:12 UTC, merged