Audit3. Runtime. Add channel transfer feature to the content pallet.
Joystream/joystream pull request #3432
Opened 2022-03-16 13:45 UTC by shamil-gadelshin

[Original issue](https://github.com/Joystream/joystream/issues/2816)

2022-03-16 14:27 UTC, shamil-gadelshin commented
We should update the `audit3` branch with the code from `rhodes` branch prior to reviewing this PR.

2022-03-16 17:49 UTC, bedeho requested changes
Minor tweaks.

2022-03-16 17:49 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +                channel.transfer_status == ChannelTransferStatus::NoActiveTransfer,
This constraint is not required, I should be able to change terms of an ongoing transfer in any way, this is totally useful, e.g. reducing price or anything else.

2022-03-16 17:49 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +            Self::validate_member_set(&new_status_params.new_collaborators)?;
I would not even bother with this, let people provide whatever ids they want, runtime does not need to babysit, and if we are doing this check other places I would say that is the mistake, and it should be removed in the interest of consistency, rather than adding here.

2022-03-17 07:46 UTC, shamil-gadelshin commented on runtime-modules/content/src/lib.rs
> +            Self::validate_member_set(&new_status_params.new_collaborators)?;
Should, I remove all entries of the `validate_member_set` within this task?

- create_channel
https://github.com/Joystream/joystream/blob/b3d36b7ebf348cf083b79bbe904bce6ebb1ea341/runtime-modules/content/src/lib.rs#L355

- update_channel
https://github.com/Joystream/joystream/blob/b3d36b7ebf348cf083b79bbe904bce6ebb1ea341/runtime-modules/content/src/lib.rs#L461

- update_moderator_set
https://github.com/Joystream/joystream/blob/b3d36b7ebf348cf083b79bbe904bce6ebb1ea341/runtime-modules/content/src/lib.rs#L1235

2022-03-17 07:52 UTC, shamil-gadelshin commented on runtime-modules/content/src/lib.rs
> +                channel.transfer_status == ChannelTransferStatus::NoActiveTransfer,
We forgot about the `cancel_transfer` extrinsic. But we could skip creating it if we allow `update_channel_transfer_status` to set any transfer status.

2022-03-17 07:54 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +            Self::validate_member_set(&new_status_params.new_collaborators)?;
yes I think so, thank you for chasing this down here in this PR. Some tests will probably break.

2022-03-17 07:55 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +                channel.transfer_status == ChannelTransferStatus::NoActiveTransfer,
yes this was the idea.

2022-03-18 08:10 UTC, bedeho approved these changes
Excellent work.

2022-03-21 10:14 UTC, merged