Pioneer v1 update
Joystream/joystream pull request #3474
Opened 2022-03-23 08:29 UTC by DzhideX

Changes:
- Remove non-working modules
- Add new opening text and Pioneer v2 section to home page

2022-03-23 14:39 UTC, traumschule commented on pioneer/packages/apps-config/src/settings/endpoints.ts
> +    //   text: t<string>('rpc.joystream-2', 'Joystream (JoystreamStats.Live)', { ns: 'apps-config' }),
This load balanced endpoint will stay available and https://pioneer.joystreamstats.live/ is going to be updated too,

2022-03-23 16:08 UTC, bwhm requested changes
Just two small fixes needed!

2022-03-23 16:08 UTC, bwhm commented on pioneer/packages/joy-media/src/index.tsx
> +        and all the action will happen on <a target='_blank' rel='noopener noreferrer' href='https://www.dao.joystream.org'>dao.joystream.org</a>.
```suggestion
        and all the action will happen on <a target='_blank' rel='noopener noreferrer' href='https://dao.joystream.org'>dao.joystream.org</a>.
```

2022-03-23 16:08 UTC, bwhm commented on pioneer/packages/joy-media/src/index.tsx
> +          More information can be found <a target='_blank' rel='noopener noreferrer' href='https://blog.joystream.org/olympia-released/'>here</a>!
This needs to be scrapped, as the blog post won't go live yet...

2022-03-24 08:33 UTC, bwhm commented
Looks good now!

2022-03-24 08:33 UTC, merged