Rhodes fix removed eng auction duration
Joystream/joystream pull request #3490
Opened 2022-03-24 14:50 UTC by ignazio-bovo

fixes #3488

2022-03-28 22:46 UTC, ondratra approved these changes
LGTM

2022-03-29 10:15 UTC, bedeho approved these changes
LGTM.

2022-03-29 16:33 UTC, bedeho reviewed
LGTM, just one cosmetic fix.

2022-03-29 16:33 UTC, bedeho commented on runtime-modules/content/src/nft/types.rs
> +        // sniping extension logic
I would explicitly write out the logic here in the comment. If bid block is in `[end - extension_period, end)` then new `end` is `end + extension_period`

2022-03-30 00:36 UTC, ondratra requested changes

2022-03-30 00:36 UTC, ondratra commented on types/src/content/index.ts
> +  starts_at: Option.with(BlockNumber),
Order needs to match the definition in runtime.
```suggestion
  starts_at: Option.with(BlockNumber),
  duration: BlockNumber,
```

2022-03-30 07:54 UTC, merged