Audit3 removed content posts and reactions
Joystream/joystream pull request #3565
Opened 2022-04-06 10:41 UTC by ignazio-bovo

fixes #3222

2022-04-06 11:01 UTC, bedeho approved these changes
LGTM.

2022-04-06 13:06 UTC, Lezek123 requested changes
Two places where I noticed some remainings of the removed feature:
- `VideoPostDoesNotExist` in `content/src/errors.rs`
- `BloatBondCap` in `content/src/tests/mock.rs`

Also, all the stuff related to video comments' `moderators` should be removed as agreed.

I noticed that tests are failing on this branch:
```
error[E0599]: no method named `with_transfer_status_by_member_id` found for struct `fixtures::UpdateChannelTransferStatusFixture` in the current scope
    --> runtime-modules/content/src/tests/moderators.rs:103:14
     |
103  |             .with_transfer_status_by_member_id(DEFAULT_MEMBER_ID)
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `fixtures::UpdateChannelTransferStatusFixture`
     | 
    ::: runtime-modules/content/src/tests/fixtures.rs:1842:1
     |
1842 | pub struct UpdateChannelTransferStatusFixture {
     | --------------------------------------------- method `with_transfer_status_by_member_id` not found for this
```
Could you look into that?

2022-04-06 13:06 UTC, Lezek123 commented on runtime-modules/content/src/tests/mock.rs
> +    pub const ExistentialDeposit: u32 = 1;
Why was this value changed?

2022-04-06 14:13 UTC, ignazio-bovo commented on runtime-modules/content/src/tests/mock.rs
> +    pub const ExistentialDeposit: u32 = 1;
To accomodate both  Storage and membership traits.
I updated it with two different contstants now, so `ExistentialDeposit` is back to `0`

2022-04-06 14:30 UTC, Lezek123 commented
A few more remainings uncovered:

**`runtime/lib`:**

```rust
    pub const CleanupMargin: u32 = 3;    // TODO: update
    pub const CleanupCost: u32 = 1; // TODO: update
```
    
**`runtime-modules/content/src/tests/mock.rs`**:
 ```rust
    pub const DEFAULT_MODERATOR_ACCOUNT_ID: u64 = 105;
```

```rust
    pub const DEFAULT_MODERATOR_ID: u64 = 205;
```

```rust
    pub const MaxModerators: u64 = 5;
    pub const CleanupMargin: u32 = 3;
    pub const CleanupCost: u32 = 1;
```

```rust
    pub const VideoCommentsModuleId: ModuleId = ModuleId(*b"m0:forum"); // module : forum
```

2022-04-07 08:01 UTC, Lezek123 approved these changes
LGTM!

2022-04-07 08:21 UTC, merged