Ephesus. Runtime. Add NFT-limits to the content pallet.
Joystream/joystream pull request #3609
Opened 2022-04-14 10:20 UTC by shamil-gadelshin

This PR adds NFT-limits to the content pallet.
Limit types:
1. daily or weekly
2. global or channel

#### Comments

- There are four combinations of these limits like `global daily` limit. 
- Limits are imposed on the NFT-issuing extrinsics (like 'update_video'). 
- Global limits update requires `root` privileges and could be set using a new proposal.
- Channel limits update requires `lead` privileges and could be set using a dedicated extrinsic.

#### Changes
-  content-pallet: `issue_nft`, `create_video` and `update_video` extrinsics are affected
- tests for runtime, proposals-codex-pallet, and pallet-content crates
- benchmarking for proposals-codex-pallet

2022-04-14 16:22 UTC, bedeho requested changes
As agreed, 

- move channel specific limits & counters into channels
- move global limits out of maps and into top level storage fields

2022-04-14 20:00 UTC, bedeho requested changes

2022-04-14 20:00 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +                Self::check_nft_limits(&channel)?;
Eeek! classic side-effect violation due to storage integration! what happens if upload suceeds but mintin limit is constrained! 😢 

We will kill this devil once and for all with a better interface, but for now the fix is easy, lift this check up, right after construction of `nft_status` makes most sense.

2022-04-14 20:00 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +                Self::check_nft_limits(&channel)?;
I think this was the only one, but great if you can double check!

2022-04-14 22:00 UTC, shamil-gadelshin commented on runtime-modules/content/src/lib.rs
> +                Self::check_nft_limits(&channel)?;
Yes, you are correct. I was confused by the `mutation safe` mark. Fixed here: https://github.com/Joystream/joystream/pull/3609/commits/4399cc53878de0e79618ba6e579535ae0050a99a

I didn't touch the mark though as agreed in previous PRs.

2022-04-15 04:52 UTC, bedeho approved these changes

2022-04-21 09:05 UTC, ignazio-bovo approved these changes

2022-04-22 12:39 UTC, merged