Creator token pallet benchmarking
Joystream/joystream pull request #3671
Opened 2022-04-26 07:18 UTC by Lezek123

Based on https://github.com/Joystream/joystream/pull/3618
To be updated once https://github.com/Joystream/joystream/pull/3456 and https://github.com/Joystream/joystream/pull/3618 are merged

2022-07-21 06:34 UTC, ignazio-bovo requested changes
Looks Ok in terms of benchmarking and performance accounting.  
 There is just a minor and subtle issue with the statement:
`token.sale.is_some() (affects the size of TokenData):` The size of an option is
size of `T` + bytes necessary to align `T`, in any case. So it is not necessary to start
a sale during the benchmarks in order to increase the size of token data (which does not
depend weather Option is some or not).
The same idea holds for split staking status and also with revenue split state field
(which is a enum and the same rules hold).
Removing these part should speed up the weight generation process (in theory):

https://users.rust-lang.org/t/why-does-an-option-around-t-imply-a-size-of-std-t-2/32945/2

2022-07-21 06:34 UTC, dobertRowneySr commented on runtime-modules/project-token/src/lib.rs
> +        ///   - `O(1)` - doesn't depend on the state or parameters
```suggestion
         ///  - DB:
        ///   - `O(1)` - doesn't depend on the state or parameters
```

2022-07-21 06:34 UTC, dobertRowneySr commented on runtime-modules/project-token/src/lib.rs
> +        ///   - `O(T)` - from the the generated weights
```suggestion
        ///   - `O(T)` - event fields written to Storage
```

2022-07-21 06:34 UTC, dobertRowneySr commented on runtime-modules/project-token/src/lib.rs
> +        ///   - `O(T)` - from the the generated weights
This is due to the deposited event (containing the validated transfers) that is written to Storage.
https://docs.substrate.io/main-docs/build/events-errors/

2022-07-21 16:43 UTC, Lezek123 commented on runtime-modules/project-token/src/lib.rs
> +        ///   - `O(T)` - from the the generated weights
I think that's actually due to token balances of the destinations being updated.
Events don't seem to affect `writes` and `reads`

2022-07-21 16:43 UTC, Lezek123 commented
> Looks Ok in terms of benchmarking and performance accounting.
There is just a minor and subtle issue with the statement:
token.sale.is_some() (affects the size of TokenData): The size of an option is
size of T + bytes necessary to align T, in any case. So it is not necessary to start
a sale during the benchmarks in order to increase the size of token data (which does not
depend whether Option is some or not).
The same idea holds for split staking status and also with revenue split state field
(which is a enum and the same rules hold).

Great observation.
I actually noticed that the impact on the weight was almost non-existing and I was wondering why that's the case.
Thank you for the detailed explanation!

2022-07-22 09:44 UTC, ignazio-bovo approved these changes
LGTM

2022-07-22 13:23 UTC, merged