Creator token revenue split tweaks
Joystream/joystream pull request #3756
Opened 2022-05-17 08:29 UTC by ignazio-bovo

Specs: #3637 

#### Changes
- `MinRevenueSplitDuration` is now a storage variable
- `MinRevenueSplitForewarning` storage variable added. Now whenever `issue_revenue_split` is called (either with or without optional starting block) at `current_block` it holds `revenue_split_starting_block >= current_block + MinRevenueSplitForewarning`. 
- User participating in a previous split is able to unstake automatically by using `participate_in_split`

To be merged after https://github.com/Joystream/joystream/pull/3632#pullrequestreview-975008984

2022-05-17 13:24 UTC, Lezek123 requested changes
- Please add `issue_split_ok_with_custom_start_block` test case to test a scenario where the user provides `Some(start_block)`
- Not strictly related to this PR, but I think `issue_revenue_split` w/ `allocation == 0` should result in `DispatchError` (consistently w/ `participate_in_split` w/ `amount == 0`)
- Merge conflicts

2022-05-17 13:24 UTC, Lezek123 commented on runtime-modules/project-token/src/lib.rs
> +        pub MinRevenueSplitForewarning get(fn min_revenue_split_forewarning) config(): T::BlockNumber
I think `TimeToStart` would be much clearer of a name than `Forewarning`

2022-05-18 06:32 UTC, ignazio-bovo commented on runtime-modules/project-token/src/lib.rs
> +        pub MinRevenueSplitForewarning get(fn min_revenue_split_forewarning) config(): T::BlockNumber
fixed in 94d7272167f3cb56eebb85640dc8f66868a3ca28

2022-05-18 13:29 UTC, Lezek123 approved these changes
LGTM

2022-05-18 13:30 UTC, merged