Creator tokens: Burning
Joystream/joystream pull request #3782
Opened 2022-05-23 14:47 UTC by Lezek123

Addresses https://github.com/Joystream/joystream/issues/3640

Burning priority:
- Unvested and staked tokens are burned first
- Transferrable tokens are burned only if no unvested / staked tokens remain

This is achieved by introducing `burned_amount` property to `vesting_schedule`. `vesting_schedule.locks(b)` is equal to `max(0, unvested_amount (according to original schedule) - burned_amount)`. Multiple test cases have been added to ilustrate this and make sure everything works as expected.

When burning funds, all vesting schedules that either already were or just became stale (ended up with `locks(current_block) == 0`) are removed.

It is possible to immediately `dust_account` once all funds are burned, even if some of those funds were still locked in a vesting schedule before (unvested). If some tokens were staked, they need to be unstaked first however (even though the staked amount is now `0`), this is to prevent `burn` extrinsic from directly affecting the `staking_status` of an account (since this is a more risky ingerention than just changing the staked `amount` to `0`)

2022-05-24 12:00 UTC, ignazio-bovo requested changes
great job!
I would add the following test cases:
- burn ok with just staking
- burn ok with no vesting and no staking
- burn ok with vesting period over amount fully burned (which you are already testing in the `...should_work_as_expected` test)
- burn ok with vesting period non over amount fully burned

2022-05-24 12:00 UTC, dobertRowneySr commented on runtime-modules/project-token/src/lib.rs
> +        /// Postconditions:
I would use a simpler description like:
- if a schedule vesting amount is completely burned, then vesting schedule is removed
- else vesting schedule `burned_amount += amount`

2022-05-24 12:00 UTC, dobertRowneySr commented on runtime-modules/project-token/src/tests/canonical.rs
> +        assert_eq!(
I felt (by going through this) that the test is too complex, since you are basically testing the following units of behavior:
- whether  vesting schedule accounting logic &`transferrable` behaves correctly as blocks pass (which should already be covered in the `sales`- tests) -> first 5 assertions
- you are checking that `transferrable` amount is left untouched after the burn since only vesting amount has been modified (and you have already tested this in `burn_ok_with_vesting_and_staked_tokens_burned_first`)
- then you are testing that `transferrable` amount accounting is correct
- then you are testing that a schedule with a fully burned vesting amount is gone -> ok!

2022-05-24 12:02 UTC, ignazio-bovo commented on runtime-modules/project-token/src/tests/canonical.rs
> +        assert_eq!(
WDYT?

2022-05-24 15:38 UTC, Lezek123 commented on runtime-modules/project-token/src/tests/canonical.rs
> +        assert_eq!(
> - whether vesting schedule accounting logic &transferrable behaves correctly as blocks pass (which should already be covered in the sales- tests) -> first 5 assertions

This is different from the vesting schedule tests in `sale.rs`, because it checks the behavior of a schedule that is "partially burned" (while the tests inside `sale.rs` only test the vesting schedule that has `burend_amount == 0`)

> you are checking that transferrable amount is left untouched after the burn since only vesting amount has been modified (and you have already tested this in burn_ok_with_vesting_and_staked_tokens_burned_first)

`burn_ok_with_vesting_and_staked_tokens_burned_first` is different, because in that case vesting_schedules are removed completely. Those tests check the behavior of a "partially burned" vesting schedule throughout different stages.

2022-05-24 16:02 UTC, Lezek123 commented
> I would add the following test cases:

> - burn ok with just staking

Ok

> - burn ok with no vesting and no staking

This is already covered by basic cases:
- `burn_ok`
- `burn_ok_with_account_tokens_amount_decreased`
- `burn_ok_with_token_supply_decreased` 

> - burn ok with vesting period over amount fully burned (which you are already testing in the ...should_work_as_expected test)

I'm not sure what you mean by `with vesting period over amount fully burned`.
Vesting schedules are also fully burned (and removed) as part of `burn_ok_with_vesting_and_staked_tokens_burned_first`

> - burn ok with vesting period non over amount fully burned

Same as above, I don't understand what exactly should I test here, could you rephrase / elaborate?

2022-05-25 08:45 UTC, ignazio-bovo commented
> Same as above, I don't understand what exactly should I test here, could you rephrase / elaborate?

Yes, I was referring to the edge case when the internal `burn` methods finds a ended vesting schedule.
But you are already checking cases when a vesting schedule is removed (with both `locks() != 0` and `locks() == 0`)

2022-05-25 08:54 UTC, ignazio-bovo requested changes
LGTM, just cosmetics left

2022-05-25 08:54 UTC, ignazio-bovo commented on runtime-modules/project-token/src/tests/canonical.rs
> +fn burn_ok_with_partially_burned_vesting_schedule_working_as_expected() {
```suggestion
fn burn_ok_with_partially_burned_vesting_schedule_amounts_working_as_expected() {
```

2022-05-25 08:54 UTC, ignazio-bovo commented on runtime-modules/project-token/src/tests/canonical.rs
> +fn burn_ok_with_partially_burned_vesting_schedule_working_as_expected() {
Or something similar

2022-05-25 09:38 UTC, ignazio-bovo approved these changes

2022-05-25 09:39 UTC, merged