Fix Vote Stake Unlocking
Joystream/joystream pull request #3783
Opened 2022-05-24 09:17 UTC by mnaamani

Fix for https://github.com/Joystream/joystream/issues/3559

- Fix implementation of `council::can_unlock_vote_stake()` to match the rules described in the handbook
- Adjust run_full_council_cycle to support interrupt to allow testing vote unlocks during council idle stage

2022-05-25 12:04 UTC, Lezek123 requested changes
I think it would be a good idea to add tests for the following scenarios:
- `run_council_cycle_with_interrupt` at `CouncilCycleInterrupt::AfterVoting` - expect no voter is able to unstake
- `run_council_cycle_with_interrupt` at `CouncilCycleInterrupt::AfterRevealing` - expect no voter is able to unstake
- a scenario similar to `council_vote_for_winner_stakes_longer`, but with second cycle interrupted at `CouncilCycleInterrupt::BeforeCandidatesAnnounce`

2022-05-25 12:04 UTC, Lezek123 commented on runtime-modules/council/src/lib.rs
> +        // If the vote is for an election prior to the last concluded..
```suggestion
        // If the vote was cast before the latest Announcing stage...
```
The handbook should also be updated accordingly

2022-05-25 16:14 UTC, bedeho commented
I very much agree with the idea of adding explicit tests here.

2022-05-26 15:43 UTC, mnaamani commented
> I very much agree with the idea of adding explicit tests here.

Agreed, its the best way to describe the rules

2022-05-27 14:04 UTC, Lezek123 approved these changes
LGTM

2022-05-28 20:41 UTC, merged