qn - *not* filtering support
Joystream/joystream pull request #3803
Opened 2022-05-27 00:44 UTC by ondratra

This PR brings support for negative filtering in QN queries + fixed variant `or` filtering  https://github.com/Joystream/hydra/issues/485 & https://github.com/Joystream/hydra/issues/476.

This type of queries can be used now
```
# selects all nfts except the one with id 3
query {
  ownedNfts(
     where: {
          NOT: [
            {id_eq: 3},
          ]
        }
    ) {
      id,
      transactionalStatus {
        __typename
      }
    }
  }
}
```

2022-05-27 08:56 UTC, ondratra commented
CI tests are failing on some connection issues that shouldn't be related to the PR itself. I'll try to do an extra commit later on to see if problems disappear. So far, it failed twice, with ~10 hours between runs.

2022-05-30 09:42 UTC, zeeshanakram3 reviewed
Not able to build `query-node` locally. Running 
- `yarn build` in `/joystream/query-node`, OR
- `yarn workspace query-node-root build` in `/joystream/`

results in the following error:
```
3/6] Fetching packages...
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning codecov@3.8.3: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
warning i18n-tag-schema > babel-runtime > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
[3/5] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/axa-ch/cyclic-schemas-test.git
Directory: /workspace/joystream/query-node
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 128.
```

2022-06-07 13:10 UTC, zeeshanakram3 requested changes

2022-06-07 13:10 UTC, zeeshanakram3 commented on cli/src/Api.ts
> +    )
This formatting change causes the prettier issue
<img width="776" alt="image" src="https://user-images.githubusercontent.com/37098720/172387796-98065375-1a05-4514-83d6-3016fb509284.png">

2022-06-07 13:10 UTC, zeeshanakram3 commented on cli/src/Api.ts
> +    return this._api as unknown as UnaugmentedApiPromise
This formatting change causes the prettier issue
<img width="739" alt="image" src="https://user-images.githubusercontent.com/37098720/172387574-66237ab0-d64d-42bb-bca5-7d3a71389072.png">

2022-06-07 15:56 UTC, zeeshanakram3 approved these changes

2022-06-10 09:51 UTC, ondratra commented on cli/src/Api.ts
> +    )
After a discussion, we've concluded that this issue was due to not properly updated `yarn` dependencies on local machine (removing all `node_modules` folders and running `yarn` again fixed the issue).

2022-06-10 09:51 UTC, ondratra commented on cli/src/Api.ts
> +    return this._api as unknown as UnaugmentedApiPromise
After a discussion, we've concluded that this issue was due to not properly updated `yarn` dependencies on local machine (removing all `node_modules` folders and running `yarn` again fixed the issue).

2022-06-28 10:08 UTC, ondratra commented
The last commit had to fix an issue with TypeORM that (likely) changed the behavior for `find*` function using `logical or` in `where` condition. 

For example, the following `.get` call
```
const channel = await store.get(Channel, {
  where: channelAssets.map((assetName) => ({
    [assetName]: {
      id: dataObject.id,
  })),
  relations: [...channelAssets],
})
```
resulted in sql query
```
SELECT 
"Channel"."id" AS "Channel_id", "Channel__Channel_avatarPhoto"."id", "Channel__Channel_coverPhoto"."id"
...
FROM "channel" "Channel" 
INNER JOIN "storage_data_object" "Channel__Channel_avatarPhoto" ON "Channel__Channel_avatarPhoto"."id"="Channel"."avatar_photo_id"  
INNER JOIN "storage_data_object" "Channel__Channel_coverPhoto" ON "Channel__Channel_coverPhoto"."id"="Channel"."cover_photo_id" 
WHERE (("Channel__Channel_coverPhoto"."id" = '12641') OR ("Channel__Channel_avatarPhoto"."id" = '12641'))
```
but those two `INNER JOIN`s can't work with logical `OR` in the `WHERE` condition because they ultimately act as logical `AND`.

2022-07-08 13:52 UTC, merged