Introduce video state bloat bond #3394
Joystream/joystream pull request #3833
Opened 2022-06-02 17:42 UTC by L3pereira

- Closes #3394

Merge after #3821 

When creating a video, the sender gets slashed video state bloat bond
When deleting a channel sender gets paid the video state bloat bond amount
Uses the funds_needed_for_upload implemented here https://github.com/Joystream/joystream/pull/3693 to verify the funds needed before charging the video state bloat bond

2022-06-03 07:22 UTC, bedeho commented on runtime-modules/content/src/lib.rs
> +            let _ = Balances::<T>::slash(&sender, video_state_bloat_bond);
Do we not put the bloat bond in some treasury account or something? What did we do for bounty pallet bloat bonds, or for storage?

2022-06-03 13:50 UTC, ignazio-bovo requested changes
Same cosmetics as the channel bloat bond PR, otherwise LGTM

2022-06-03 13:50 UTC, ignazio-bovo commented on runtime-modules/content/src/lib.rs
> +            ensure_authorized_to_update_video_state_bloat_bond::<T>(&sender)?;
```suggestion
            ensure_authorized_to_update_video_state_bloat_bond::<T>(&sender)?;
            // == MUTATION SAFE ==
```

2022-06-03 13:50 UTC, ignazio-bovo commented on runtime-modules/content/src/tests/videos.rs
> +        let video_state_bloat_bond = 1;
why not use their `DEFAULT-*` counterparts?

2022-06-17 12:57 UTC, ignazio-bovo approved these changes
LGTM

2022-06-27 14:50 UTC, ignazio-bovo approved these changes

2022-06-30 14:51 UTC, ignazio-bovo requested changes
- build node & runtime :heavy_check_mark: 
- types and metadata :heavy_check_mark: 
- cargo test :heavy_check_mark: 
- there are some problem with benchmarks: 
```
---- tests::council_discard_remaining_rewards_on_depose stdout ----
thread 'tests::council_discard_remaining_rewards_on_depose' panicked at 'attempt to subtract with overflow', runtime-modules/council/src/mock.rs:1496:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::council_many_cycle_rewards stdout ----
thread 'tests::council_many_cycle_rewards' panicked at 'attempt to subtract with overflow', runtime-modules/council/src/mock.rs:1496:17

---- tests::council_rewards_are_paid stdout ----
thread 'tests::council_rewards_are_paid' panicked at 'attempt to subtract with overflow', runtime-modules/council/src/mock.rs:1496:17

---- tests::vote_stake_locks_after_new_election_starts stdout ----
thread 'tests::vote_stake_locks_after_new_election_starts' panicked at 'attempt to subtract with overflow', runtime-modules/council/src/mock.rs:1496:17
```
These should be fixed see https://github.com/mnaamani/joystream/pull/13

2022-07-01 11:51 UTC, ignazio-bovo approved these changes

2022-07-01 11:51 UTC, merged