build script for network tests added, readme updated
Joystream/joystream pull request #386
Opened 2020-05-04 15:02 UTC by gleb-urvanov

2020-05-08 11:01 UTC, mnaamani requested changes
Nice trick, just needs small fix to use the edited chainspec.json file, maybe also add the chainspec.json file to .gitignore ?

2020-05-08 11:01 UTC, mnaamani commented on scripts/run-test-chain.sh
> +cargo run --release -p joystream-node -- --dev
```suggestion
cargo run --release -p joystream-node -- --chain ./chainspec.json
```

To use the custom chainspec file that was produced.

2020-05-11 12:32 UTC, gleb-urvanov commented on scripts/run-test-chain.sh
> +cargo run --release -p joystream-node -- --dev
Fixed, also removed build from the script

2020-05-19 08:34 UTC, mnaamani commented
Included in https://github.com/Joystream/joystream/pull/399

2020-05-19 08:34 UTC, closed without merging