Carthage curator moderation actions
Joystream/joystream pull request #3937
Opened 2022-06-22 07:39 UTC by zeeshanakram3

implements #3870

Based on #3921 so expects it to be merged first

2022-06-28 11:02 UTC, ondratra requested changes
I found one spot that could use a better code style, but otherwise this PR looks good.

2022-06-28 11:02 UTC, ondratra commented on tests/network-tests/src/fixtures/content/createCuratorGroupFixture.ts
> +          : { ChangeChannelFeatureStatus: { CreatorCashout: null } }
This part is very hard to read. Let's replace this ternary operators chain by a helper function that will return proper value(s).

2022-07-14 12:09 UTC, ondratra approved these changes
LGTM

2022-07-14 12:23 UTC, mnaamani commented
small conflict fix needed.

2022-07-14 17:38 UTC, merged