Fix benchmaks and weights generation
Joystream/joystream pull request #3970
Opened 2022-06-27 08:21 UTC by mnaamani

Address Benchmark issues from https://github.com/Joystream/joystream/issues/3948

2022-06-28 17:03 UTC, mnaamani commented
All pallet benchmarks are correctly being executed against the main runtime (not mock runtime used in tests).
I've re-organized where the weights.rs for each pallet is now stored.

I haven't been able to resolve issue with generating storage info to see more detailed information about storage accessed by the weight functions.

Pending fix is https://github.com/Joystream/joystream/issues/3923 the referendum benchmark test is only failing for the mock runtime for some reason.

2022-06-29 13:11 UTC, mnaamani commented
> All pallet benchmarks are correctly being executed against the main runtime (not mock runtime used in tests). I've re-organized where the weights.rs for each pallet is now stored.
> 
> I haven't been able to resolve issue with generating storage info to see more detailed information about storage accessed by the weight functions.
> 
> Pending fix is #3923 the referendum benchmark test is only failing for the mock runtime for some reason.

Finally resolved, it was a real pain to debug https://github.com/Joystream/joystream/pull/3970/commits/78553b278ca2c63a612e8aa9dc8012e60b103921

2022-07-03 17:56 UTC, ignazio-bovo requested changes
Looks ok, I have just left a comment about weights generation

2022-07-03 17:56 UTC, dobertRowneySr commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
I did not understand where this part comes from:
The `MaxWhiteListSize` scenario can only be reached in `change_thread_mode` however here only `ensure_thread_mode` is used.

2022-07-03 17:56 UTC, dobertRowneySr commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
And also here the `text` parameter is passed by move. So all the operation on it should be O(1).
Hence I am not getting the `text.len()` weight complexity parameter

2022-07-04 07:03 UTC, mnaamani commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
Looks like this was a mistake, the first arg should be `T::MaxCategoryDepth::get()`

Here is the benchmark code snippet for `add_post()`

```
add_post {

        let forum_user_id = 0;
        let caller_id =
            insert_a_leader::<T>(forum_user_id);

        let i in 1 .. (T::MaxCategoryDepth::get() + 1) as u32;

        let j in 0 .. MAX_BYTES;
...
```

2022-07-04 07:07 UTC, mnaamani commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
> And also here the `text` parameter is passed by move. So all the operation on it should be O(1). Hence I am not getting the `text.len()` weight complexity parameter

My guess is the subsequent call to `add_new_post()` which computes a hash over the text, so I presume that is `O(text.len())` ? The weight component from weights.rs looks like 
`.saturating_add((2_000 as Weight).saturating_mul(j as Weight))`

2022-07-04 07:10 UTC, mnaamani commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
Lol sorry I was looking at `forum::add_post()`

2022-07-04 07:13 UTC, mnaamani commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
So you are right about that, the actual value (`i`) is not even used by the weight function:
```rust
fn add_post(_i: u32, j: u32, ) -> Weight {
		(74_579_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(j as Weight))
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
```

2022-07-04 07:19 UTC, mnaamani commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
The benchmark should probably be re-written to remove that value as a "component".

As for the text len weight component is very tiny `.saturating_add((1_000 as Weight).saturating_mul(j as Weight))` but still `O(n)` not `O(1)`. I suppose there is still computation involved to decode the vec and copy it into the event.

2022-07-04 08:22 UTC, mnaamani commented on runtime-modules/proposals/discussion/src/lib.rs
> +            T::MaxWhiteListSize::get() as u32,
Is this the correct fix @ignazio-bovo 81c89b8a6fdd3e7b65047c05dce22711c5005c3b

2022-07-06 05:42 UTC, ignazio-bovo approved these changes
LGTM

2022-07-07 08:32 UTC, merged