Carthage qn categories metaprotocol 2
Joystream/joystream pull request #4026
Opened 2022-07-14 00:49 UTC by ondratra

Fixes https://github.com/Joystream/joystream/issues/3574.
Superseeds https://github.com/Joystream/joystream/pull/3950. Builds on top of https://github.com/Joystream/joystream/pull/4021 and expects it to be merged first.

This PR contains:
- removal of channel categories from QN
- rework of video categories - from Joystream-node-based event's to metaprotocol-based representation
- adjustments to comments and reactions code so it can use common parts with video categories

2022-07-26 10:51 UTC, ondratra commented
I'm not sure why is the the active-video-counters test is failing in CI.
When I run it locally via 
```
DEBUG=true ./query-node/run-tests.sh # QN tests only
DEBUG=true ./query-node/run-tests.sh full # full tests
```
everything passes just fine.

2022-07-26 12:34 UTC, kdembler commented
@ondratra @mnaamani I think we should add categories creation in chain setup script so new playgrounds have some categories from the start

2022-07-28 13:18 UTC, zeeshanakram3 commented on tests/network-tests/src/scenarios/content-directory.ts
> +  job('video comments and reactions', commentsAndReactions).after(curatorModerationActionsJob)
`curatorModerationActionsJob` does not really need `nftAuctionAndOffersJob` to be completed first. So they can be run in parallel. I think current approach unnecessarily increases the running time of tests
```suggestion
  job('nft auction and offers', nftAuctionAndOffers).after(videoCategoriesJob)
  job('curator moderation actions', curatorModerationActions).after(videoCategoriesJob)
  job('video comments and reactions', commentsAndReactions).after(videoCategoriesJob)
```

2022-07-28 19:38 UTC, zeeshanakram3 requested changes

2022-07-28 19:38 UTC, zeeshanakram3 commented on tests/network-tests/src/scenarios/content-directory.ts
> +  job('video comments and reactions', commentsAndReactions).after(curatorModerationActionsJob)
`curatorModerationActionsJob` does not really need `nftAuctionAndOffersJob` to be completed first. So they can be run in parallel. I think the current approach unnecessarily increases the running time of tests
```suggestion
  job('nft auction and offers', nftAuctionAndOffers).after(videoCategoriesJob)
  job('curator moderation actions', curatorModerationActions).after(videoCategoriesJob)
  job('video comments and reactions', commentsAndReactions).after(videoCategoriesJob)
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on tests/network-tests/src/cli/joystream.ts
> +import { Utils } from '../utils'
Unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on tests/network-tests/src/cli/joystream.ts
> +import Long from 'long'
Unused imports
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on tests/network-tests/src/cli/joystream.ts
>    VideoCategoryInputParameters,
Unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on tests/network-tests/src/fixtures/content/nft/englishAuction.ts
>  import BN from 'bn.js'
Unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on tests/network-tests/src/fixtures/content/nft/openAuction.ts
>  import BN from 'bn.js'
Unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on tests/network-tests/src/fixtures/content/createContentStructure.ts
>  import { getVideoCategoryDefaults, getChannelCategoryDefaults } from './contentTemplates'
unused import
```suggestion
import { getVideoCategoryDefaults } from './contentTemplates'
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on query-node/mappings/src/content/channel.ts
>  import { BaseModel } from '@joystream/warthog'
unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on query-node/mappings/src/content/channel.ts
>    MetaprotocolTransactionErrored,
unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on query-node/mappings/src/content/channel.ts
>    MetaprotocolTransactionStatusEvent,
unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on query-node/mappings/src/content/channel.ts
>  import { getAllManagers } from '../derivedPropertiesManager/applications'
unused import
```suggestion
```

2022-07-28 19:38 UTC, zeeshanakram3 commented on metadata-protobuf/proto/Metaprotocol.proto
> +}
The nested `oneof` message doesn't seem necessary here, we can achieve the purpose by only a single `oneof` message as well, i.e. directly wrapping `*VideoCategory` messages inside `WorkerGroupLeadRemarked`

The message serialized with the schema described in the PR would have a few extra bytes (needed to encode nested `oneof` field) compared to the schema proposed in this comment

Given that the serialized message would be part of on-chain transaction payload, and hence would impact transaction fees, we should  aim for minimum serialized message size
```suggestion
message WorkerGroupLeadRemarked {
    oneof worker_group_lead_remarked {
        CreateVideoCategory create_category = 1;
        UpdateVideoCategory update_category = 2;
        DeleteVideoCategory delete_category = 3;
    }
}
```

2022-08-09 09:19 UTC, dmtrjsg commented
Closing this PR as superceded by https://github.com/Joystream/joystream/pull/4122

2022-08-09 09:19 UTC, closed without merging