Qn carthage video subtitles
Joystream/joystream pull request #4092
Opened 2022-07-29 07:16 UTC by zeeshanakram3

implements #4087

2022-08-03 01:01 UTC, ondratra requested changes
I've suggested a couple of tweaks. Plus, some tests are failing and need to be fixed.

2022-08-03 01:01 UTC, ondratra commented on query-node/manifest.yml
> +      handler: content_ContentDeleted
Why is the handler renamed? It will be easier to navigate between runtime and mappings if handler names are the same as event names.

2022-08-03 01:01 UTC, ondratra commented on query-node/mappings/src/content/utils.ts
> +}
Let's reduce the amount of nested `if`s by introducint helper function(s).

2022-08-03 01:01 UTC, ondratra commented on query-node/mappings/src/content/utils.ts
> +    _.remove(subtitlesToRemove, (sub) => sub.id === subtitleId)
Let's not intruduce `lodash` only to use `remove` function once. We can use vanilla JS `Array.filter` instead.

2022-08-03 01:01 UTC, ondratra commented on tests/network-tests/src/cli/joystream.ts
> +      throw new Error(`Unexpected CLI failure on  updating video: "${stderr}"`)
Typo

2022-08-23 18:35 UTC, kdembler commented on query-node/mappings/src/content/utils.ts
> +    await processVideoSubtitles(ctx, video, assets, meta.subtitles || [], meta.clearSubtitles)
I think `clearSubtitles` should take priority if defined next to regular subtitles? Maybe we do
```ts
const subtitles = meta.clearSubtitles ? [] : meta.subtitles
if (isSet(subtitles)) {
  // ...
}
```

2022-08-24 15:10 UTC, kdembler approved these changes
Tested this a bunch and everything seems to be working properly 🎉

2022-08-24 15:25 UTC, merged