Balances proxy for staking pallet
Joystream/joystream pull request #4203
Opened 2022-08-23 20:32 UTC by mnaamani

Fixes https://github.com/Joystream/joystream/issues/4189 by implementing suggestion to "override" free_balance() for the runtime balances pallet instance used by the staking pallet.

- [x] Implementation
- [ ] Tests

2022-08-24 11:37 UTC, ignazio-bovo approved these changes
lgtm

2022-08-24 12:21 UTC, Lezek123 requested changes
I was going through alternative solutions that would actually make the `bond` call fail and therefore make us avoid any additional confusion among the users that try to bond with an already existing rivalrous lock. I found one that is pretty simple and looks promising to me.

There is one fallable call in `staking::bond()` method which seems like we can safely make fail for a given caller (stash) account:

```rust
frame_system::Pallet::<T>::inc_consumers(&stash).map_err(|_| Error::<T>::BadState)?;
```

As I discovered, there are 2 failing conditions for `Account::inc_consumers`:
- `a.providers == 0` - we probably don't want trigger this one
- `a.consumers >= T::MaxConsumers::max_consumers()` - this one seems safe and easy to trigger

So my suggestion is:
- When a new rivalrous lock is being set via `StakingHandler`, we increase account's `consumers` value by `T::MaxConsumers::max_consumers()` (this way we make sure the account never goes below `T::MaxConsumers::max_consumers()` while the rivalrous lock is in place and it also makes it trivial to go back to the "actual" value once the lock is removed)
- When a rivalrous lock is being removed, we decrease account's `consumers` by `T::MaxConsumers::max_consumers()`, which brings it back to the real value

And that's about it. By applying this fix we prevent `staking::bond()` from ever succeeding in context of an account that has a rivalrous lock. This seems to me like a much simpler and safer approach than the `BalancesProxy` and I couldn't find any bad side-effects that this approach would have.

Let me know what you think.

2022-08-24 12:21 UTC, Lezek123 commented on runtime/src/lib.rs
> +        }
Because `STAKING_LOCK_ID` is rivalrous this will prevent someone from increasing the bond, because after initially bonding there will be already a "conflicting" lock in the account when calling `bond_extra`.

To solve this you could:
- return `Balances::free_balance(who)` also in case there is already a `STAKING_LOCK_ID` lock assigned to the account (but not any other rivalrous lock)
- add a test to make sure this works as expected (`bond` + `bond_extra` scenario)

2022-08-24 12:50 UTC, bedeho commented
> I couldn't find any bad side-effects that this approach would have

This is the main thing here, I don't really understand this fix, but certainly we are here making a change to very public state which lots of code may be using, or may use in the future in some random fix. The proxy solution did exactly one thing, locally: make staking pallet think there was 0 funds if there was a rivalrous lock. Noone else is affected by that. I'm not even 100% sure we fully grasp the consequences of that, say if someone can use it in some other way with the staking pallet where the balance > 0 is not important, and then at a later time the balance has gone up in a way the staking pallet expects to know (say if it depends on some on_balance_change hook or something). But for this fix I just have no way to gauge what level of confidence we should ascribe to your inability to find a sideeffect right now.

2022-08-24 13:08 UTC, bedeho commented on runtime/src/lib.rs
> +// MUST ONLY BE USED BY THE STAKING PALLET
A longer explanation of _why_ this is being added makes sense, also,nice if this all could be in a different file, this file is getting out of hand :D.

2022-08-24 13:09 UTC, bedeho commented on runtime/src/lib.rs
> +// MUST ONLY BE USED BY THE STAKING PALLET
A longer explanation of why this is being added makes sense, also,nice if this all could be in a different file, this file is getting out of hand :D.

2022-08-28 09:05 UTC, mnaamani commented
Replaced by https://github.com/Joystream/joystream/pull/4213

2022-08-28 09:05 UTC, closed without merging