Carthage remove forum reaction
Joystream/joystream pull request #4211
Opened 2022-08-25 14:15 UTC by ignazio-bovo

addresses #4132

2022-08-30 10:59 UTC, Lezek123 requested changes
1. Conflicts resolution needed
2. Could you also update the query node, `metadata-protobuf` and integration tests ie.:
    - Remove `PostReaction` and `ForumPostReaction` from `query-node/schemas/forum.graphql`
    - Remove `reactions` field from `ForumPost` in `query-node/schemas/forum.graphql`
    - Remove `PostReactionResult`, `PostReactedEvent` etc. from `query-node/schemas/forumEvents.graphql`
    - Remove everything that has to do with post reactions from `/query-node/mappings/src/forum.ts` (the imports, `parseReaction` function, `forum_PostReacted` handler etc.)
    - Remove `forum.PostReacted` from `query-node/manifest.yml`
    - Remove `ForumPostReaction` message from `/metadata-protobuf/proto/Forum.proto`, bump the `version` in `/metadata-protobuf/pakage.json` and update docs with `yarn workspace @joystream/metadata-protobuf generate-doc`
    - Remove `ReactToPostsFixture` from `/network-tests/src/fixtures/forum`
    - Remove post reaction tests from `/tests/network-tests/src/flows/forum/posts.ts`
    - Remove `reactions` from `ForumPostFields` in `network-tests/src/graphql/queries/forum.graphql`
    - Remove `PostReactedEventFields` and `getPostReactedEventsByEventIds` from `tests/network-tests/src/graphql/queries/forumEvents.graphql`
    - Re-build packages (`yarn && yarn build:packages`) and update autogenerated graphql types in the network-tests workspace: `yarn workspace network-tests generate:all`

2022-09-09 09:09 UTC, Lezek123 requested changes
1. You need to remove `export { ReactToPostsFixture, PostReactionParams } from './ReactToPostsFixture'` from `tests/network-tests/src/fixtures/forum/index.ts`
1. You can also remove `ForumPostReactionId` from `types/src/primitives.ts`
1. Please re-generate graphql typing for typescript apps:
    1. `yarn workspace network-tests generate:types:graphql`
    2. `yarn workspace @joystream/distributor-cli generate:types:graphql`
    3. `yarn workspace @joystream/cli generate:graphql-typings`
    4. `yarn workspace storage-node generate:types:graphql`
1. Remove import in `tests/network-tests/src/QueryNodeApi.ts`:
    ```
      PostReactedEventFieldsFragment,
      GetPostReactedEventsByEventIdsQuery,
      GetPostReactedEventsByEventIdsQueryVariables,
      GetPostReactedEventsByEventIds,
    ```
1. Remove `getPostReactedEvents` in `tests/network-tests/src/QueryNodeApi.ts`
1. Fix formatting:
    1. `yarn workspace query-node-mappings format`
    2. `yarn workspace network-tests format`
1. Make sure those commands are not failing locally:
    1. `yarn workspace query-node-root build`
    2. `yarn workspace query-node-root checks`
    3. `yarn workspace @joystream/cli checks`
    4. `yarn workspace @joystream/distributor-cli checks`
    5. `yarn workspace storage-node checks`
    6. `yarn workspace network-tests checks`

2022-09-09 09:09 UTC, Lezek123 commented on query-node/manifest.yml
> +        - forum.CategoryStickyThreadUpdate
Broken formatting, causes the query node build to fail

2022-09-09 09:09 UTC, Lezek123 commented on metadata-protobuf/doc/index.md
> +meta = VideoMetadata {
- Looks like this file was not correctly updated. It still has `ForumPostReaction` message and the _**Referencing Assets**_ section looks broken now.

2022-09-11 18:35 UTC, ignazio-bovo commented
all checks passing, meging...

2022-09-12 07:55 UTC, Lezek123 approved these changes
LGTM.
Seems like there's something wrong with `metatada-protobuf` doc generation script, since _Referencing Assets_ gets duplicated, but I guess it can be fixed in some other PR

2022-09-12 07:56 UTC, merged