Referendum: Add voting opt-out functionality
Joystream/joystream pull request #4409
Opened 2022-10-27 15:41 UTC by Lezek123

Addresses https://github.com/Joystream/joystream/issues/2927

2022-11-25 09:16 UTC, ignazio-bovo approved these changes
LGTM

2023-02-01 07:01 UTC, mnaamani requested changes
Looks good, just left a suggestion so `AccountOptedOutOfVoting` event is only ever emitted once for an account.

2023-02-01 07:01 UTC, mnaamani commented on runtime-modules/referendum/src/lib.rs
> +            Self::deposit_event(RawEvent::AccountOptedOutOfVoting(account_id));
Event will emit even if account already existed in the list. Perhaps `add_account_to_opted_out_set` can return a `bool` to indicate if account was inserted for first time, and only emit event if true.

Or simply check for existence of account at the start and return `Ok(())` early, skipping insert and deposit_event calls. (basically just a no-op if account has previously opted out)

2023-02-01 07:01 UTC, mnaamani commented on yarn.lock
I think you only ran yarn build in the types directory, so yarn.lock file has a lot of changes.
If you run yarn `build:packages` in root it will revert these changes?

2023-02-01 12:30 UTC, Lezek123 commented on yarn.lock
Re-ran in https://github.com/Joystream/joystream/pull/4409/commits/af969d29e1e1354ca9db3a90c7f9d7f6b81dd6c3

2023-02-01 12:31 UTC, Lezek123 commented on runtime-modules/referendum/src/lib.rs
> +            Self::deposit_event(RawEvent::AccountOptedOutOfVoting(account_id));
Added in https://github.com/Joystream/joystream/pull/4409/commits/0a4eb6edf6e2474871f473f2ed769da79ab89379

2023-02-01 16:33 UTC, dobertRowneySr approved these changes
LGTM

2023-02-02 08:50 UTC, mnaamani approved these changes

2023-02-02 08:50 UTC, merged