Mainnet liberated integration test fix
Joystream/joystream pull request #4542
Opened 2023-01-18 15:29 UTC by ignazio-bovo

fixes #4401 

# Details
- [ ] replace sudo flows with proposals
- [ ] updated to `mainnet-liberated`
- [ ] merged into `ephesus`

2023-01-31 13:09 UTC, mnaamani requested changes
Overall looks great, well done. I left my concern about assumption being made about result of proposals query from chain state and query node which will not always hold. So it would be better to address now, otherwise it might be hard to debug failing proposals test in future.

Although running the integration tests locally didn't cause a problem.

2023-01-31 13:09 UTC, mnaamani commented on tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts
> +        const qProposal = qProposals[i]
There is a potential problem with this assignment since qProposals will contain all proposals every created, and this.proposals is only the proposals that are currently active in chain state. It would be more correct to pick from qProposals the proposal with the matching proposalId.

2023-01-31 13:09 UTC, mnaamani commented on tests/network-tests/src/fixtures/workingGroups/CreateLeadOpeningFixture.ts
> +    // Query the events
best to remove commented out code

2023-01-31 13:09 UTC, mnaamani commented on tests/network-tests/src/scenarios/full.ts
> +  const sudoHireLead = job('sudo lead opening', leadOpening(process.env.IGNORE_HIRED_LEADS === 'true')).after(
the "sudo" in the name of this job doesn't make sense anymore

2023-02-01 06:20 UTC, mnaamani commented
Additional points:
we should add back the setupNewChain, and setupNewChainMultiStorage scenarios to `run_test_scenarios` job in github workflow run-network-tests.

Also update some of the bash scripts in tests/network-tests/ that still have some reference to sudo arguments and env variables which are not required anymore, and dropping the SUDO_ACCOUNT_URI from .env file

2023-02-01 14:23 UTC, ignazio-bovo commented
I have addressed all the required comments.
There where still some outdated `sudo` references, mostly in the form of `asSudo` boolean for WG tests.
They are removed now

2023-02-01 14:23 UTC, ignazio-bovo commented
I have addressed all the required comments.
There where still some outdated `sudo` references, mostly in the form of `asSudo` boolean for WG tests.
They are removed now

2023-02-02 16:38 UTC, mnaamani approved these changes

2023-02-02 16:38 UTC, mnaamani commented on tests/network-tests/src/flows/membership/invitingMembers.ts
> +  // Membership WG balance required
Since this flow could be used in other scenarios where perhaps a council was not elected, maybe it should fail early.

2023-02-02 16:38 UTC, mnaamani commented on tests/network-tests/src/flows/membership/invitingMembers.ts
> +  await new FixtureRunner(decideOnUpdateWgBudgetProposalStatusFixture).run()
Will the fixture fail if there is no council to actually vote on the proposal?

2023-02-02 16:38 UTC, merged