Ephesus cli for direct channel payment
Joystream/joystream pull request #4561
Opened 2023-01-22 18:52 UTC by zeeshanakram3

addresses #4518

This PR:
- adds `content:directChannelPayment` CLI command
- decorates `membership:memberRemark` with payment option

2023-01-23 18:52 UTC, Lezek123 requested changes

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/base/AccountsCommandBase.ts
> +    if (toBalances.availableBalance.add(new BN(amount)).lt(this.getApi().existentialDeposit())) {
`ExistentialDeposit` applies to total (or "`voting`") balance.
```suggestion
    if (toBalances.votingBalance.add(new BN(amount)).lt(this.getApi().existentialDeposit())) {
```

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/base/AccountsCommandBase.ts
> +    checkBalance(fromBalances, new BN(amount))
To be precise, the balance should also be sufficient to:
- cover transaction fee of the member remark extrinsic
- not go below existential deposit (this, however, only applies to `votingBalance`, not `availableBalance`)

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/commands/content/directChannelPayment.ts
> +    context: ContentDirectoryCommandBase.channelCreationContextFlag,
This flag is not used

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/commands/content/directChannelPayment.ts
> +      - payment context Formant: 'channel' or 'video:{videoId}'
```suggestion
      - payment context format: 'channel' or 'video:{videoId}'
```

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/commands/content/directChannelPayment.ts
> +  private static parsePaymentContext(input: 'channel' | `video:${number}`): { videoId: string } | undefined {
It's not guaranteed that the input here will be of type:
```
'channel' | `video:${number}`
```
It can be any arbitrary string, so it should be validated accordingly.

Perhaps it would be easier to use optional `videoId` flag instead?

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/commands/content/directChannelPayment.ts
> +    await MemberRemarkCommand.run([metaMessage, '--account', channel.rewardAccount, '--amount', amount])
> First, it is generally a bad idea to run a command directly as the command exports a user interface, not a code interface. It's a design smell that should rarely (if ever) be used. Generally speaking, it's better to break up the code so that it can be called directly rather than as a command.

_Source: https://oclif.io/docs/running_programmatically_

Here you are also losing some context, for example, if user executes `directChannelPayment` with `--useMemberId 10`, this flag is not passed down to `MemberRemarkCommand` here.

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/commands/content/directChannelPayment.ts
> +      : await this.getQNApi().getChannelByRewardAccount(rewardAccount!)
Better to avoid non-null assertions
```suggestion
      : await this.getQNApi().getChannelByRewardAccount(rewardAccount || '')
```
The current implementation actually results in a very uniformative error when neither `channelId` nor `rewardAccount` is provided, ie.:

```
 ›   Warning: Query node error: Response not successful: Received status code 400
    Error: Response not successful: Received status code 400
error Command failed with exit code 1.
```

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/commands/content/directChannelPayment.ts
> +      this.error(`Channel with reward account ${rewardAccount} does not exist`, { exit: ExitCodes.InvalidInput })
The error can also be caused by invalid channel id provided, in which case the error message will be wrong

2023-01-23 18:52 UTC, Lezek123 commented on cli/src/QueryNodeApi.ts
> +    return channels.length > 0 ? channels[0] : null
There is a `firstEntityQuery` method for this use-case

2023-01-24 16:56 UTC, zeeshanakram3 commented on cli/src/QueryNodeApi.ts
> +    return channels.length > 0 ? channels[0] : null
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:56 UTC, zeeshanakram3 commented on cli/src/commands/content/directChannelPayment.ts
> +      this.error(`Channel with reward account ${rewardAccount} does not exist`, { exit: ExitCodes.InvalidInput })
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:56 UTC, zeeshanakram3 commented on cli/src/commands/content/directChannelPayment.ts
> +      : await this.getQNApi().getChannelByRewardAccount(rewardAccount!)
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:56 UTC, zeeshanakram3 commented on cli/src/commands/content/directChannelPayment.ts
> +    await MemberRemarkCommand.run([metaMessage, '--account', channel.rewardAccount, '--amount', amount])
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:57 UTC, zeeshanakram3 commented on cli/src/commands/content/directChannelPayment.ts
> +  private static parsePaymentContext(input: 'channel' | `video:${number}`): { videoId: string } | undefined {
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:57 UTC, zeeshanakram3 commented on cli/src/commands/content/directChannelPayment.ts
> +      - payment context Formant: 'channel' or 'video:{videoId}'
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:57 UTC, zeeshanakram3 commented on cli/src/commands/content/directChannelPayment.ts
> +    context: ContentDirectoryCommandBase.channelCreationContextFlag,
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:57 UTC, zeeshanakram3 commented on cli/src/base/AccountsCommandBase.ts
> +    checkBalance(fromBalances, new BN(amount))
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-24 16:57 UTC, zeeshanakram3 commented on cli/src/base/AccountsCommandBase.ts
> +    if (toBalances.availableBalance.add(new BN(amount)).lt(this.getApi().existentialDeposit())) {
Addressed in [e36fd92](https://github.com/Joystream/joystream/pull/4561/commits/e36fd92b87a4cbbb73dda7e88253e00ff33af25f)

2023-01-25 12:43 UTC, Lezek123 requested changes

2023-01-25 12:43 UTC, Lezek123 commented on cli/src/base/AccountsCommandBase.ts
> +    if (fromBalances.votingBalance.lt(new BN(amount))) {
- `votingBalance` should be `>= amount + existentialDeposit`
- `availableBalance` should be `>= amount`
(this ignores transaction fees however)
```suggestion
    if (
      fromBalances.votingBalance.lt(new BN(amount).add(this.getApi().existentialDeposit()))
      || fromBalances.availableBalance.lt(new BN(amount))
    ) {
```

2023-01-26 08:05 UTC, Lezek123 approved these changes
Looks good!

2023-01-26 08:08 UTC, merged