Fix channel payouts mappings and add missing tests
Joystream/joystream pull request #4594
Opened 2023-01-31 19:50 UTC by Lezek123

Addresses https://github.com/Joystream/joystream/issues/4579 and adds test coverage

2023-02-02 22:06 UTC, ignazio-bovo requested changes
it's ok, I just left a cosmetic suggestion.

 I just want to mention 2 things:
1. we are not having any tests for curator channel in which `claim_and_withdraw` would leave the council budget unaffected theoretically. 
2. we are not making any checks to ensure proper `api.query.council.budget` variations

I am not sure if they should be implemented here or they can be checked in other way (QA)

2023-02-02 22:06 UTC, dobertRowneySr commented on query-node/mappings/src/content/channel.ts
> +  const [owner, channelId, amount, destination] = new Content.ChannelRewardClaimedAndWithdrawnEvent(event).params
maybe replace `amount` with `withdrawnAmount` since it's easier to understand

2023-02-03 09:23 UTC, Lezek123 commented on query-node/mappings/src/content/channel.ts
> +  const [owner, channelId, amount, destination] = new Content.ChannelRewardClaimedAndWithdrawnEvent(event).params
Done in https://github.com/Joystream/joystream/pull/4594/commits/d7013f7523758e1d1211056e968d91fc2544002e

2023-02-03 09:43 UTC, Lezek123 commented
> we are not having any tests for curator channel in which claim_and_withdraw would leave the council budget unaffected theoretically.

We have unit tests in the runtime, but we don't have integration tests. We don't really have integration tests for curator channels in general, which is quite unfortunate.

> we are not making any checks to ensure proper api.query.council.budget variations

Added some basic checks in https://github.com/Joystream/joystream/pull/4594/commits/1320d219cc9dacba79ab5087f39867511b94768f

2023-02-03 11:54 UTC, ignazio-bovo approved these changes
LGTM, merging

2023-02-03 11:55 UTC, merged