fix: channel deletion mapping bug
Joystream/joystream pull request #4603
Opened 2023-02-06 14:43 UTC by zeeshanakram3

addresses #4601

2023-02-06 16:10 UTC, Lezek123 requested changes
Additional notes:
1. I don't think we have any tests for banning members from a channel. If it's not time-consuming, could you add a call to `BanOrUnbanMemberFixture` in `flows/commentsAndReactions`, to make sure removing `MemberBannedFromChannelEvent` references works as expected?

2023-02-06 16:10 UTC, Lezek123 commented on query-node/mappings/src/content/channel.ts
> +  const referencingEntities: typeof BaseModel[] = [Collaborator, ChannelNftCollectors, MemberBannedFromChannelEvent]
If you declare it as:
```typescript
  const referencingEntities: { new (): BaseModel & { channel: Partial<Channel> } }[] = [
    Collaborator,
    ChannelNftCollectors,
    MemberBannedFromChannelEvent,
  ]
```
then you can remove `entity as any` assertion below and preserve the typesafety

2023-02-07 10:42 UTC, zeeshanakram3 commented on query-node/mappings/src/content/channel.ts
> +  const referencingEntities: typeof BaseModel[] = [Collaborator, ChannelNftCollectors, MemberBannedFromChannelEvent]
Adressed in [550314a](https://github.com/Joystream/joystream/pull/4603/commits/550314a18c8fe98af2eb5b65e96815cda80bb394)

2023-02-07 11:27 UTC, Lezek123 approved these changes
LGTM, but will wait until the checks pass before merging.

A note about updating atlas-dev: Because the atlas-dev network is running from `carthage` branch and the mappings between `carthage` and `master` are not fully compatible (there was `Gateway` => `Apps` working group renaming), you probably just want to cherry-pick [463c141](https://github.com/Joystream/joystream/pull/4603/commits/463c141bdc9b69988b3916f943801e003cab3e6b) and [550314a](https://github.com/Joystream/joystream/pull/4603/commits/550314a18c8fe98af2eb5b65e96815cda80bb394) into `carthage` before re-building and restarting the processor.

2023-02-07 11:49 UTC, merged