Ephesus update from master
Joystream/joystream pull request #4634
Opened 2023-02-14 16:22 UTC by mnaamani

Porting fixes and updates from master to ephesus

2023-02-16 09:44 UTC, mnaamani commented
Will update this again once following PRs are merged
- https://github.com/Joystream/joystream/pull/4632
- https://github.com/Joystream/joystream/pull/4560
- https://github.com/Joystream/joystream/pull/4636
-

2023-02-17 11:02 UTC, Lezek123 requested changes
Looks like integration tests from https://github.com/Joystream/joystream/pull/4533 got lost during conflict resolutions.

2023-02-17 12:32 UTC, zeeshanakram3 approved these changes

2023-02-17 12:36 UTC, Lezek123 commented
> Looks like integration tests from https://github.com/Joystream/joystream/pull/4533 got lost during conflict resolutions.

I'll make another PR with a fix.

2023-02-17 12:36 UTC, merged