Tweak remarks
Joystream/joystream pull request #4644
Opened 2023-02-17 12:14 UTC by Lezek123

2023-02-22 08:31 UTC, mnaamani approved these changes
LGTM

2023-02-22 11:05 UTC, bedeho approved these changes

2023-02-22 11:52 UTC, mnaamani requested changes
We just need to bump runtime spec version and joystream-node version since we have deployed a staging network with prior version already.

2023-02-22 13:56 UTC, mnaamani commented
Lol looks like the storage sync test killed the github runner. Maybe 10_000 videos is a little too much?

2023-02-23 08:05 UTC, mnaamani approved these changes

2023-02-23 08:05 UTC, merged