Fix/remove app deletion
Joystream/joystream pull request #4667
Opened 2023-02-27 10:51 UTC by WRadoslaw

2023-02-27 11:10 UTC, drillprop requested changes
1. Totally unrelated, but could you also fix a small typo in `cli/examples/content/CreateApp.json` and `cli/examples/content/UpdateApp.json` as part of this PR? You wrote "exmaple" instead of "example".  

2. You didn't remove `deleteApp` test from the `full.ts`

2023-02-27 13:22 UTC, Lezek123 reviewed
Please also remove:
- `deleteApp` CLI command
- References to `deleteApp` protobuf message in `/tests/network-tests/src/Api.ts`
- Reference to `deleteApp` CLI command in `/tests/network-tests/src/cli/joystream.ts`

2023-02-27 15:58 UTC, Lezek123 commented on tests/network-tests/src/Api.ts
> -      createApp: new CreateApp({
It looks like you forgot about removing imports from `@joystream/metadata-protobuf` (`CreateApp`, `DeleteApp`, `IAppMetadata`, `UpdateApp`), so the CI checks are failing: https://github.com/Joystream/joystream/actions/runs/4283418182/jobs/7458964301

2023-02-28 10:56 UTC, Lezek123 approved these changes
LGTM

2023-02-28 12:28 UTC, merged