Ephesus: Implement graceful QA processing across upgrades
Joystream/joystream pull request #4718
Opened 2023-03-27 13:58 UTC by zeeshanakram3

Addresses #4650

depends on https://github.com/Joystream/atlas/issues/3986

2023-03-27 18:23 UTC, Lezek123 requested changes
After making a few adjustments as suggested in the comment the solution appears to have worked as expected.

However I was wondering why providing chain metadata as json is no longer supported? If it was, we could avoid having to commit the entire `query-node/types/generated` directory.

I also noticed that all types are imported from `@polkadot/types/lookup`, so in case a type (like `ChannelCreationParametersRecord` for example) is modified in the runtime during the upgrade, this will not be correctly handled by this solution, as only the latest version of this type will be imported in the event type files (`query-node/types/generated`).

2023-03-27 18:23 UTC, Lezek123 commented on query-node/mappings/src/membership.ts
> +  console.log('block', block)
```suggestion
```
Leftover

2023-03-27 18:23 UTC, Lezek123 commented on query-node/mappings/src/membership.ts
> +  console.log('block', block, typeof specVersion)
```suggestion
```

2023-03-27 18:23 UTC, Lezek123 commented on query-node/mappings/src/storage/index.ts
> +  const [bucketId, workerId] = new DistributionBucketOperatorInvitedEvent_V1001(event).params
```suggestion
  const [bucketId, workerId] = new DistributionBucketInvitationCancelledEvent_V1001(event).params
```

2023-03-27 18:23 UTC, Lezek123 commented on query-node/mappings/src/workingGroups.ts
> +  const [newBudget] = new Council_BudgetBalanceSetEvent_V1001(event).params
```suggestion
  const [newBudget] = new StorageWorkingGroup_BudgetSetEvent_V1001(event).params
```

2023-03-27 18:23 UTC, Lezek123 commented on query-node/mappings/src/workingGroups.ts
> +  Council_BudgetBalanceSetEvent_V1001,
```suggestion
  StorageWorkingGroup_BudgetSetEvent_V1001,
```

2023-03-27 18:23 UTC, Lezek123 commented on query-node/mappings/src/membership.ts
> +  const [memberId, metadataBytes, payment] = specVersion === v2001 ? asV2001 : asV1001
This implementation causes error when trying to process `MemberRemarked` events on mainnet chain:
```
ERROR: Stopping the proccessor due to errors: {} name: TypeError, message: Cannot read property 'value' of undefined, stack: TypeError: Cannot read property 'value' of undefined
    at Members_MemberRemarkedEvent_V2001.get params [as params] (/joystream/query-node/mappings/lib/types/generated/2001/members.js:467:36)
    at members_MemberRemarked (/joystream/query-node/mappings/lib/mappings/src/membership.js:297:41)
    at MappingsLookupService.call (/joystream/node_modules/@joystream/hydra-processor/lib/executor/MappingsLookupService.js:80:15)
    at /joystream/node_modules/@joystream/hydra-processor/lib/executor/TransactionalExecutor.js:41:43
    at EntityManager.<anonymous> (/joystream/node_modules/typeorm/entity-manager/EntityManager.js:80:46)
    at step (/joystream/node_modules/tslib/tslib.js:144:27)
    at Object.next (/joystream/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/joystream/node_modules/tslib/tslib.js:115:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

```suggestion
  const [memberId, metadataBytes, payment] =
    specVersion === 2001 ? new MemberRemarkedEvent_V2001(event).params : new MemberRemarkedEvent_V1001(event).params
````

2023-03-27 18:23 UTC, Lezek123 commented on query-node/mappings/src/membership.ts
> +  const [memberId, inviteMembershipParameters, maybeInvitedMemberBalance] = specVersion === v2001 ? asV2001 : asV1001
This implementation causes an error when trying to process `MemberInvited` event from the mainnet chain:
```
ERROR: Stopping the proccessor due to errors: {} name: TypeError, message: Cannot read property 'value' of undefined, stack: TypeError: Cannot read property 'value' of undefined
    at Members_MemberInvitedEvent_V2001.get params [as params] (/joystream/query-node/mappings/lib/types/generated/2001/members.js:228:101)
    at members_MemberInvited (/joystream/query-node/mappings/lib/mappings/src/membership.js:201:41)
    at MappingsLookupService.call (/joystream/node_modules/@joystream/hydra-processor/lib/executor/MappingsLookupService.js:80:15)
    at /joystream/node_modules/@joystream/hydra-processor/lib/executor/TransactionalExecutor.js:41:43
    at EntityManager.<anonymous> (/joystream/node_modules/typeorm/entity-manager/EntityManager.js:80:46)
    at step (/joystream/node_modules/tslib/tslib.js:144:27)
    at Object.next (/joystream/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/joystream/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
```suggestion
  const [memberId, inviteMembershipParameters, maybeInvitedMemberBalance] =
    specVersion === 2001 ? new MemberInvitedEvent_V2001(event).params : new MemberInvitedEvent_V1001(event).params
```

2023-03-28 20:45 UTC, zeeshanakram3 commented
> However I was wondering why providing chain metadata as json is no longer supported? If it was, we could avoid having to commit the entire query-node/types/generated directory.

The hydra-typegen package now requires the chain's specVersion to populate the event template & generate the typescript files. And I am assuming that the spec version can only be retrieved from the chain. (Is my assumption correct? Can we get the chain spec version from the metadata?)

Even if we could generate the event using metadata I think we still need to save query-node/types/generated for all the previous previous spec versions? So that mappings (of the latest version) can access all the previous types.

> I also noticed that all types are imported from @polkadot/types/lookup, so in case a type (like ChannelCreationParametersRecord for example) is modified in the runtime during the upgrade, this will not be correctly handled by this solution, as only the latest version of this type will be imported in the event type files (query-node/types/generated).

Addressed in Hydra([b9319e6](https://github.com/Joystream/hydra/pull/518/commits/b9319e6f9ce9331573265697bd18ad6d5f65cea6)) & QN([a04112a](https://github.com/Joystream/joystream/pull/4718/commits/a04112abff6b4392c5f0fea60bfd5c5edd666278)). Though, it also employs a similar approach (i.e. committing the runtime types used as event parameters for each spec in `types/generated`)

2023-03-31 14:42 UTC, Lezek123 requested changes
Looks good besides the small issues mentioned in the comments.
Unfortunately I still can't do full sync test against mainnet locally, because of https://github.com/Joystream/hydra/issues/519.

2023-03-31 14:42 UTC, Lezek123 commented on query-node/mappings/tsconfig.json
> +  "include": ["./src/**/*", "../types"],
```suggestion
  "include": ["./src/**/*"],
```

2023-03-31 14:42 UTC, Lezek123 commented on tests/network-tests/run-runtime-upgrade-tests.sh
> +    ./run-test-scenario.sh content-directory
Nft auction and offers flow fails currently because of a longer `minAuctionDuration` time on mainnet:
```
2023-03-30T17:41:25.2317319Z 2023-03-30T17:41:25.231Z integration-tests:awaiting:blocknumber 2726 Condition not satisfied, waiting...
2023-03-30T17:41:26.2329565Z 2023-03-30T17:41:26.232Z integration-tests:awaiting:blocknumber 2726 Current block: 1722
2023-03-30T17:41:26.2374597Z 2023-03-30T17:41:26.232Z integration-tests:awaiting:blocknumber 2726 Condition not satisfied, waiting...
2023-03-30T17:41:27.2335251Z 2023-03-30T17:41:27.233Z integration-tests:awaiting:blocknumber 2726 Current block: 1723
2023-03-30T17:41:27.2336736Z 2023-03-30T17:41:27.233Z integration-tests:awaiting:blocknumber 2726 Condition not satisfied, waiting...
2023-03-30T17:41:28.2336799Z 2023-03-30T17:41:28.233Z integration-tests:awaiting:blocknumber 2726 Current block: 1724
2023-03-30T17:41:28.2337650Z 2023-03-30T17:41:28.233Z integration-tests:awaiting:blocknumber 2726 Condition not satisfied, waiting...
2023-03-30T17:41:29.2343738Z 2023-03-30T17:41:29.234Z integration-tests:awaiting:blocknumber 2726 Current block: 1725
2023-03-30T17:41:29.2344544Z 2023-03-30T17:41:29.234Z integration-tests:awaiting:blocknumber 2726 Condition not satisfied, waiting...
2023-03-30T17:41:30.2354376Z 2023-03-30T17:41:30.235Z integration-tests:awaiting:blocknumber 2726 Current block: 1726
2023-03-30T17:41:30.2357058Z 2023-03-30T17:41:30.235Z integration-tests:awaiting:blocknumber 2726 Condition not satisfied, waiting...
2023-03-30T17:41:31.2356888Z 2023-03-30T17:41:31.235Z integration-tests:awaiting:blocknumber 2726 Current block: 1727
2023-03-30T17:41:31.2357936Z 2023-03-30T17:41:31.235Z integration-tests:awaiting:blocknumber 2726 Condition not satisfied, waiting...
2023-03-30T17:41:32.1787584Z 2023-03-30T17:41:32.178Z integration-tests:job:nft auction and offers flow 0 failed:
2023-03-30T17:41:32.1900286Z Error: Awaiting blocknumber 2726 - timeout reached
2023-03-30T17:41:32.1900994Z     at Timeout._onTimeout (/home/runner/work/joystream/joystream/tests/network-tests/src/utils.ts:144:47)
2023-03-30T17:41:32.1901486Z     at listOnTimeout (internal/timers.js:557:17)
2023-03-30T17:41:32.1901891Z     at processTimers (internal/timers.js:500:7)
```

2023-04-04 08:34 UTC, Lezek123 approved these changes
LGTM, great job!

2023-04-04 09:21 UTC, merged