add mass discretionary spending to cli (#4715)
Joystream/joystream pull request #4719
Opened 2023-03-27 15:02 UTC by chrlschwb

solves #4715
Sometimes there is a need to send small amounts of tokens to multiple, like hundreds, accounts.
This new command will help with that.

2023-04-11 08:25 UTC, zeeshanakram3 requested changes
1. [test.json](https://github.com/Joystream/joystream/blob/7dc70b2f98f76a6d0218303c04a028a848d0758b/cli/bin/test.json) file should be placed in the` examples/working-group` directory, and not in the `bin/` dir. Also, please rename it accordingly.

2. `yarn.lock` file is changed in this PR, which I think should not be the case since this PR does not add or remove any dependency from `package.json` file. So please revert the changes in `yarn.lock` file

3. What's the purpose of two different CLI commands? You can do both single or multiple discretionary spending transactions from the single file as well. So no need to create two different Commands. You can add `input` flag to `WorkingGroupsDiscretionarySpending` command.

2023-04-11 08:25 UTC, zeeshanakram3 commented on cli/src/commands/working-groups/discretionarySpending.ts
> +export default class WorkingGroupsDiscetionarySpending extends WorkingGroupsCommandBase {
Incorrect spelling 
```suggestion
export default class WorkingGroupsDiscretionarySpending extends WorkingGroupsCommandBase {
```

2023-04-11 08:25 UTC, zeeshanakram3 commented on cli/src/base/ApiCommandBase.ts
> +  async sendAndFollowTxMulti(account: KeyringPair, tx: SubmittableExtrinsic<'promise'>): Promise<SubmittableResult> {
What is the purpose of this function? Why send `sendAndFollowTx` can't be used in CLI commands for sending extrinsics? It seems a redundant addition, so please remove it

2023-04-11 08:25 UTC, zeeshanakram3 commented on cli/src/base/ApiCommandBase.ts
> +
Same as above.
What is the purpose of this function? Why send `sendAndFollowNamedTx` can't be used in CLI commands for sending extrinsics? It seems a redundant addition, so please remove it

2023-04-11 08:25 UTC, zeeshanakram3 commented on cli/src/commands/working-groups/discretionarySpending.ts
> +  static args = [
Add the CLI command's description here.

2023-04-13 15:26 UTC, chrlschwb commented on cli/src/commands/working-groups/discretionarySpending.ts
> +  static args = [
Do you mean as a comment?
The command help is working by typing, "working-groups:discretionarySpending --help"

2023-04-21 15:56 UTC, chrlschwb commented on cli/src/base/ApiCommandBase.ts
> +
The `sendAndFollowNamedTx` function doesn't require the user to confirm transaction each time.
This is very useful if the user is using mass discretionary spending. For example, if they send 100 JOY to 100 people, they do not need to confirm 100 transactions in CLI.

2023-04-27 07:35 UTC, zeeshanakram3 commented on cli/src/commands/working-groups/discretionarySpending.ts
> +  static args = [
I mean a `description` property of the class, like it's part of other [commands](https://github.com/Joystream/joystream/blob/7dc70b2f98f76a6d0218303c04a028a848d0758b/cli/src/commands/working-groups/decreaseWorkerStake.ts#L10) too.

2023-04-27 07:48 UTC, zeeshanakram3 commented on cli/src/base/ApiCommandBase.ts
> +
If you see [requireConfirmation](https://github.com/chrlschwb/joystream/blob/d8a021cb0cf2adfc031b28ecfc4b73e6b8447004/cli/src/base/DefaultCommandBase.ts#L58) function there is a `AUTO_CONFIRM` env var which is used to decided whether to prompt for confirmation or not. Please set this variable before initiating a transaction and it will solve your problem

2023-08-28 03:05 UTC, closed without merging