Update from node v14 to v18.6.0
Joystream/joystream pull request #4778
Opened 2023-06-01 15:08 UTC by mnaamani

2023-07-18 14:22 UTC, zeeshanakram3 requested changes

2023-07-18 14:22 UTC, zeeshanakram3 commented on package.json
> +    "node": ">=14.6.1",
If Volta is not installed, then this engine requirement could break things. I got the following error while installing dependencies using node `14.7.0`. 

```
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
error file-type@17.1.1: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "14.7.0"
error Found incompatible module.
```

So the engine min version needs to be increased. Things seem to work at the minimum of `14.18.0` (version previously defined in "volta" section)

2023-07-18 14:22 UTC, zeeshanakram3 commented on README.md
> +- [nodejs](https://nodejs.org/) >= v18.6 - _required_
shouldn't be `v14.x.x` i.e. the minimum node version defined in the engine section?

2023-07-20 13:50 UTC, mnaamani commented on README.md
> +- [nodejs](https://nodejs.org/) >= v18.6 - _required_
Will fix, I think I changed that originally when I was forcing all engine filed to be >=18

2023-07-20 15:59 UTC, mnaamani commented
@zeeshanakram3 Applied your feedback, I also update Readme to document the fact that old version of linux will not support node v18, so I include a workaround.

2023-07-20 17:04 UTC, zeeshanakram3 commented
Looks good, I think we should use the same nodes engine requirement (`>=14.18.0`) in all package.json files in monorepo.

2023-07-20 20:26 UTC, mnaamani commented
> @zeeshanakram3 Applied your feedback, I also update Readme to document the fact that old version of linux will not support node v18, so I include a workaround.

done in [4a985be](https://github.com/Joystream/joystream/pull/4778/commits/4a985bebe3cfa1ea6c160385f0c51e75404c3c0c)

2023-07-21 14:56 UTC, zeeshanakram3 commented on CHANGELOG.md
> +If no packages or cargo crates are changed then the changes are usually "devops" realted.
```suggestion
If no packages or cargo crates are changed then the changes are usually "devops" related.
```

2023-07-21 14:56 UTC, zeeshanakram3 commented on CHANGELOG.md
> +No npm packages have not been published with new engine version yet, so you are not impacted if your application depedns on them, until the next package version release. To be ready do one of:
```suggestion
No npm packages have not been published with new engine version yet, so you are not impacted if your application depends on them, until the next package version release. To be ready do one of:
```

2023-07-22 18:12 UTC, zeeshanakram3 approved these changes
LGTM

2023-07-24 06:45 UTC, merged