[argus] few tweaks
Joystream/joystream pull request #4925
Opened 2023-10-10 12:36 UTC by kdembler

- Add 1s delay between fetching pages for QN state sync. This will allow QN to have some breathing space and process other requests that may have been stuck because of heavy processing.
- Add `Access-Control-Expose-Headers` response header to allow web clients checking cache status of downloaded file.
- Include response headers in `http` logs

2023-10-11 16:49 UTC, zeeshanakram3 approved these changes
LGTM

2023-10-16 06:42 UTC, mnaamani commented
The browser is getting the header `Access-Control-Expose-Headers` twice for each value:

<img width="458" alt="Screenshot 2023-10-16 at 10 39 26 AM" src="https://github.com/Joystream/joystream/assets/1621012/5f58fa57-0cbe-4f32-ac16-a91abb67ec7e">

I would have expected one header with the multiple values. Is this the expected response?

2023-10-16 06:53 UTC, mnaamani requested changes
Just a minor merge conflict fix needed otherwise I think this is good to go.

2023-10-16 10:29 UTC, kdembler commented
Good call @mnaamani, changed to a single header with comma-separated values. Also rebased and fixed conflicts

2023-10-16 13:41 UTC, mnaamani approved these changes

2023-10-16 13:41 UTC, merged