Verify Validator Membership
Joystream/joystream pull request #4976
Opened 2023-11-27 10:29 UTC by eshark9312

closes #4824

2023-11-30 15:17 UTC, thesan requested changes

2023-11-30 15:17 UTC, thesan commented on query-node/mappings/src/common.ts
> +}
There's already a `getMembershipById` in this file which AFAICS is the same

2023-11-30 15:17 UTC, thesan commented on query-node/mappings/src/workingGroups.ts
> +    await getWorkingGroupLeadOrFail(store, group.name)
@zeeshanakram3 both`getWorkingGroupLeadOrFail` and `getMembershipById` throw errors, is it safe to call these in the mappings without error catching ? Or are these errors caught upstream ?

2023-11-30 15:17 UTC, thesan commented on query-node/mappings/src/workingGroups.ts
> +    }
Right now member is necessarily defined:
```suggestion
```

2023-11-30 15:17 UTC, thesan commented on query-node/mappings/src/workingGroups.ts
> +    await getWorkingGroupLeadOrFail(store, group.name)
@eshark9312 this is not necessary though
```suggestion
```

2023-11-30 15:17 UTC, thesan commented on query-node/mappings/src/workingGroups.ts
> +    await getWorkerOrFail(store, group.name, workerId)
Same here:
```suggestion
```

2023-11-30 15:17 UTC, thesan commented on query-node/mappings/src/workingGroups.ts
> +    }
```suggestion
```

2023-11-30 15:17 UTC, thesan commented on tests/network-tests/src/fixtures/membership/WithMembershipWorkersFixture.ts
> +        throw new Error('Forum working group lead not set!')
```suggestion
        throw new Error('Membership working group lead not set!')
```

2023-11-30 15:17 UTC, thesan commented on tests/network-tests/src/flows/membership/updateValidatorVerifications.ts
> +  await new FixtureRunner(buyMembershipsFixture).runWithQueryNodeChecks()
Maybe this can be skipped:
```suggestion
```
I'm not sure though... WDYT @zeeshanakram3 ?

2023-11-30 15:17 UTC, thesan commented on query-node/schemas/membershipEvents.graphql
> +type ValididatorVerificationStatusUpdatedEvent implements Event @entity {
You added this event to the schema but it's never created in `query-node/mappings/src/workingGroups.ts`. However I don't think this is necessary at this point to have an event for this.

2023-11-30 15:17 UTC, thesan commented on query-node/mappings/src/workingGroups.ts
> +    await store.save<MemberProfileUpdatedEvent>(memberProfileUpdatedEvent)
Also IMO it's not necessary to create a `MemberProfileUpdatedEvent` here

2023-11-30 15:17 UTC, thesan commented on tests/network-tests/src/fixtures/membership/VerifyValidatorMembershipFixture.ts
> +    )
I don't know if you need to check the events here. I vaguely remember chatting with @chrlschwb about that but I don't remember what was the conclusion. Maybe can you try running the test without ?
```suggestion
```

2023-12-04 17:27 UTC, thesan approved these changes
LGTM! but I don't understand the failing test (`curatorModerationActions`), and @zeeshanakram3 review and advice are really needed to complete this PR

2023-12-04 17:27 UTC, thesan commented on tests/network-tests/src/fixtures/membership/VerifyValidatorMembershipFixture.ts
> +  protected assertQueryNodeEventIsValid(qEvent: AnyQueryNodeEvent, i: number): void {
@zeeshanakram3 as this method must be defined, should the event be `MemberProfileUpdatedEvent` or should it be a new event specific to this action (e.g `ValididatorVerificationStatusUpdatedEvent`), or should this method remain empty ?

2023-12-05 11:20 UTC, zeeshanakram3 requested changes

2023-12-05 11:20 UTC, zeeshanakram3 commented on query-node/mappings/src/workingGroups.ts
> +    const member = await getMembershipById(store, createType('u64', Number(memberId)))
```suggestion
    const member = await getById(store, Membership, memberId)
    // If member does not exist, just log an invalid metadata message
```

Since there is no runtime validation for metaprotocol messages, as a general rule, the functions that throw should not be used in metaprotocol mappings logic. 

These functions should only be called in the mappings when we know for sure that the corresponding state exists in the runtime so if the QN db does not have that state, it means there is a state consistent and hence throw the error.

cc. @thesan

2023-12-05 11:20 UTC, zeeshanakram3 commented on query-node/mappings/src/workingGroups.ts
> +    const member = await getMembershipById(store, createType('u64', Number(memberId)))
```suggestion
    const member = await getById(store, Membership, memberId)
```

2023-12-05 18:47 UTC, zeeshanakram3 approved these changes
LGTM.

2023-12-06 09:03 UTC, merged