Feature/crt constraints proposal
Joystream/joystream pull request #5103
Opened 2024-03-14 06:53 UTC by ignazio-bovo

addresses #5098 replace previous PR #4696

2024-03-25 01:33 UTC, freakstatic approved these changes

2024-03-26 12:16 UTC, mnaamani requested changes
Implementation looks correct, but the term "GovernanceParameters" doesn't quite fit.
I think `TokenConstraints` fits better (just as the PR title makes sense).

A round of cargo-fmt is needed.

2024-03-28 13:32 UTC, thesan commented on runtime-modules/project-token/src/benchmarking.rs
> +            max_yearly_rate Some(YearlyRate(Permill::from_penrcent(15))),
Is that a typo ?
```suggestion
            max_yearly_rate Some(YearlyRate(Permill::from_percent(15))),
```

2024-03-30 11:31 UTC, mnaamani requested changes
Additional place to remove the "governance parameters" terminology from.

There seems to be some issue in the benchmark code: https://github.com/Joystream/joystream/actions/runs/8479690474/job/23234144846?pr=5103#step:6:1375

2024-03-30 11:31 UTC, mnaamani commented on runtime-modules/project-token/src/lib.rs
> +        #[weight = WeightInfoToken::<T>::update_governance_parameters()]
the name change is not reflected in the function.
```suggestion
        #[weight = WeightInfoToken::<T>::update_token_constraints()]
```

2024-03-30 11:31 UTC, mnaamani commented on runtime-modules/proposals/codex/src/types.rs
> +    /// Update CRT governance parameters
```suggestion
    /// Update token constraints
```

2024-03-30 11:31 UTC, mnaamani commented on runtime-modules/proposals/codex/src/types.rs
> +    TokenTokenConstraints,
```suggestion
    TokenConstraints,
```
I don't think the actual type `TokenConstraints` is in scope, so we can reuse it for the template parameter name here.

2024-03-30 11:34 UTC, mnaamani commented on runtime-modules/project-token/src/benchmarking.rs
> +        }
```suggestion
        };
```

2024-03-30 11:34 UTC, mnaamani commented on runtime-modules/project-token/src/benchmarking.rs
> +        let origin = RawOrigin::root_account()
```suggestion
        let origin = RawOrigin::root_account();
```

2024-03-31 11:45 UTC, mnaamani commented on runtime-modules/project-token/src/benchmarking.rs
> -use crate::utils::{build_merkle_path_helper, generate_merkle_root_helper};
Why were all these imports dropped, they are used in the benchmarking code

2024-04-03 13:14 UTC, mnaamani commented on runtime-modules/project-token/src/lib.rs
> +                MinRevenueSplitDuration::<T>::put(new_min_revenue_split_time_to_start);
```suggestion
                MinRevenueSplitTimeToStart::<T>::put(new_min_revenue_split_time_to_start);
```

2024-04-03 13:21 UTC, mnaamani requested changes
Left a code change request to ensure `MinRevenueSplitDuration` is correctly updated.

Are you sure you are running yarn build in types/ and that you are running the correct node when generating metadata?

I'm getting slightly different

2024-04-03 13:25 UTC, mnaamani commented
When I build joystream-node and generate chain metadata and types there is a diff compared with your PR:

```diff
diff --git a/types/src/augment/augment-api-rpc.ts b/types/src/augment/augment-api-rpc.ts
index bd142eb07f..f882746f38 100644
--- a/types/src/augment/augment-api-rpc.ts
+++ b/types/src/augment/augment-api-rpc.ts
@@ -21,7 +21,7 @@ import type { CreatedBlock } from '@polkadot/types/interfaces/engine';
 import type { EthAccount, EthCallRequest, EthFeeHistory, EthFilter, EthFilterChanges, EthLog, EthReceipt, EthRichBlock, EthSubKind, EthSubParams, EthSyncStatus, EthTransaction, EthTransactionRequest, EthWork } from '@polkadot/types/interfaces/eth';
 import type { Extrinsic } from '@polkadot/types/interfaces/extrinsics';
 import type { EncodedFinalityProofs, JustificationNotification, ReportedRoundStates } from '@polkadot/types/interfaces/grandpa';
-import type { MmrHash, MmrLeafBatchProof } from '@polkadot/types/interfaces/mmr';
+import type { MmrLeafBatchProof, MmrLeafProof } from '@polkadot/types/interfaces/mmr';
 import type { StorageKind } from '@polkadot/types/interfaces/offchain';
 import type { FeeDetails, RuntimeDispatchInfoV1 } from '@polkadot/types/interfaces/payment';
 import type { RpcMethods } from '@polkadot/types/interfaces/rpc';
@@ -373,21 +373,13 @@ declare module '@polkadot/rpc-core/types/jsonrpc' {
     };
     mmr: {
       /**
-       * Generate MMR proof for the given block numbers.
+       * Generate MMR proof for the given leaf indices.
        **/
-      generateProof: AugmentedRpc<(blockNumbers: Vec<u64> | (u64 | AnyNumber | Uint8Array)[], bestKnownBlockNumber?: u64 | AnyNumber | Uint8Array, at?: BlockHash | string | Uint8Array) => Observable<MmrLeafBatchProof>>;
+      generateBatchProof: AugmentedRpc<(leafIndices: Vec<u64> | (u64 | AnyNumber | Uint8Array)[], at?: BlockHash | string | Uint8Array) => Observable<MmrLeafProof>>;
       /**
-       * Get the MMR root hash for the current best block.
+       * Generate MMR proof for given leaf index.
        **/
-      root: AugmentedRpc<(at?: BlockHash | string | Uint8Array) => Observable<MmrHash>>;
-      /**
-       * Verify an MMR proof
-       **/
-      verifyProof: AugmentedRpc<(proof: MmrLeafBatchProof | { blockHash?: any; leaves?: any; proof?: any } | string | Uint8Array) => Observable<bool>>;
-      /**
-       * Verify an MMR proof statelessly given an mmr_root
-       **/
-      verifyProofStateless: AugmentedRpc<(root: MmrHash | string | Uint8Array, proof: MmrLeafBatchProof | { blockHash?: any; leaves?: any; proof?: any } | string | Uint8Array) => Observable<bool>>;
+      generateProof: AugmentedRpc<(leafIndex: u64 | AnyNumber | Uint8Array, at?: BlockHash | string | Uint8Array) => Observable<MmrLeafBatchProof>>;
     };
     net: {
       /**
diff --git a/types/src/augment/augment-types.ts b/types/src/augment/augment-types.ts
index 762a89c48b..5ce509bfd6 100644
--- a/types/src/augment/augment-types.ts
+++ b/types/src/augment/augment-types.ts
@@ -6,7 +6,7 @@
 import '@polkadot/types/types/registry';
 
 import type { Data, StorageKey } from '@polkadot/types';
-import type { BitVec, Bool, Bytes, F32, F64, I128, I16, I256, I32, I64, I8, ISize, Json, Null, OptionBool, Raw, Text, Type, U128, U16, U256, U32, U64, U8, USize, bool, f32, f64, i128, i16, i256, i32, i64, i8, isize, u128, u16, u256, u32, u64, u8, usize } from '@polkadot/types-codec';
+import type { BitVec, Bool, Bytes, F32, F64, I128, I16, I256, I32, I64, I8, Json, Null, OptionBool, Raw, Text, Type, U128, U16, U256, U32, U64, U8, USize, bool, f32, f64, i128, i16, i256, i32, i64, i8, u128, u16, u256, u32, u64, u8, usize } from '@polkadot/types-codec';
 import type { AssetApproval, AssetApprovalKey, AssetBalance, AssetDestroyWitness, AssetDetails, AssetMetadata, TAssetBalance, TAssetDepositBalance } from '@polkadot/types/interfaces/assets';
 import type { BlockAttestations, IncludedBlocks, MoreAttestations } from '@polkadot/types/interfaces/attestations';
 import type { RawAuraPreDigest } from '@polkadot/types/interfaces/aura';
@@ -34,20 +34,19 @@ import type { CreatedBlock, ImportedAux } from '@polkadot/types/interfaces/engin
 import type { BlockV0, BlockV1, BlockV2, EIP1559Transaction, EIP2930Transaction, EthAccessList, EthAccessListItem, EthAccount, EthAddress, EthBlock, EthBloom, EthCallRequest, EthFeeHistory, EthFilter, EthFilterAddress, EthFilterChanges, EthFilterTopic, EthFilterTopicEntry, EthFilterTopicInner, EthHeader, EthLog, EthReceipt, EthReceiptV0, EthReceiptV3, EthRichBlock, EthRichHeader, EthStorageProof, EthSubKind, EthSubParams, EthSubResult, EthSyncInfo, EthSyncStatus, EthTransaction, EthTransactionAction, EthTransactionCondition, EthTransactionRequest, EthTransactionSignature, EthTransactionStatus, EthWork, EthereumAccountId, EthereumAddress, EthereumLookupSource, EthereumSignature, LegacyTransaction, TransactionV0, TransactionV1, TransactionV2 } from '@polkadot/types/interfaces/eth';
 import type { EvmAccount, EvmCallInfo, EvmCreateInfo, EvmLog, EvmVicinity, ExitError, ExitFatal, ExitReason, ExitRevert, ExitSucceed } from '@polkadot/types/interfaces/evm';
 import type { AnySignature, EcdsaSignature, Ed25519Signature, Era, Extrinsic, ExtrinsicEra, ExtrinsicPayload, ExtrinsicPayloadUnknown, ExtrinsicPayloadV4, ExtrinsicSignature, ExtrinsicSignatureV4, ExtrinsicUnknown, ExtrinsicV4, ImmortalEra, MortalEra, MultiSignature, Signature, SignerPayload, Sr25519Signature } from '@polkadot/types/interfaces/extrinsics';
-import type { FungiblesAccessError } from '@polkadot/types/interfaces/fungibles';
 import type { AssetOptions, Owner, PermissionLatest, PermissionVersions, PermissionsV1 } from '@polkadot/types/interfaces/genericAsset';
 import type { ActiveGilt, ActiveGiltsTotal, ActiveIndex, GiltBid } from '@polkadot/types/interfaces/gilt';
 import type { AuthorityIndex, AuthorityList, AuthoritySet, AuthoritySetChange, AuthoritySetChanges, AuthorityWeight, DelayKind, DelayKindBest, EncodedFinalityProofs, ForkTreePendingChange, ForkTreePendingChangeNode, GrandpaCommit, GrandpaEquivocation, GrandpaEquivocationProof, GrandpaEquivocationValue, GrandpaJustification, GrandpaPrecommit, GrandpaPrevote, GrandpaSignedPrecommit, JustificationNotification, KeyOwnerProof, NextAuthority, PendingChange, PendingPause, PendingResume, Precommits, Prevotes, ReportedRoundStates, RoundState, SetId, StoredPendingChange, StoredState } from '@polkadot/types/interfaces/grandpa';
 import type { IdentityFields, IdentityInfo, IdentityInfoAdditional, IdentityInfoTo198, IdentityJudgement, RegistrarIndex, RegistrarInfo, Registration, RegistrationJudgement, RegistrationTo198 } from '@polkadot/types/interfaces/identity';
 import type { AuthIndex, AuthoritySignature, Heartbeat, HeartbeatTo244, OpaqueMultiaddr, OpaqueNetworkState, OpaquePeerId } from '@polkadot/types/interfaces/imOnline';
 import type { CallIndex, LotteryConfig } from '@polkadot/types/interfaces/lottery';
-import type { ErrorMetadataLatest, ErrorMetadataV10, ErrorMetadataV11, ErrorMetadataV12, ErrorMetadataV13, ErrorMetadataV14, ErrorMetadataV9, EventMetadataLatest, EventMetadataV10, EventMetadataV11, EventMetadataV12, EventMetadataV13, EventMetadataV14, EventMetadataV9, ExtrinsicMetadataLatest, ExtrinsicMetadataV11, ExtrinsicMetadataV12, ExtrinsicMetadataV13, ExtrinsicMetadataV14, FunctionArgumentMetadataLatest, FunctionArgumentMetadataV10, FunctionArgumentMetadataV11, FunctionArgumentMetadataV12, FunctionArgumentMetadataV13, FunctionArgumentMetadataV14, FunctionArgumentMetadataV9, FunctionMetadataLatest, FunctionMetadataV10, FunctionMetadataV11, FunctionMetadataV12, FunctionMetadataV13, FunctionMetadataV14, FunctionMetadataV9, MetadataAll, MetadataLatest, MetadataV10, MetadataV11, MetadataV12, MetadataV13, MetadataV14, MetadataV15, MetadataV9, ModuleConstantMetadataV10, ModuleConstantMetadataV11, ModuleConstantMetadataV12, ModuleConstantMetadataV13, ModuleConstantMetadataV9, ModuleMetadataV10, ModuleMetadataV11, ModuleMetadataV12, ModuleMetadataV13, ModuleMeta [...]

2024-04-03 13:28 UTC, dobertRowneySr commented on runtime-modules/project-token/src/lib.rs
> +                MinRevenueSplitDuration::<T>::put(new_min_revenue_split_time_to_start);
good catch

2024-04-03 20:32 UTC, mnaamani approved these changes

2024-04-03 20:32 UTC, merged