fix: :bug: amm and revenue shares cannot be concurrent
Joystream/joystream pull request #5125
Opened 2024-04-04 15:32 UTC by ignazio-bovo

### Goals
1. Amm cannot be activate when a revenue share is active
2. Revenue Share cannot be issued when Amm is active

### Changes
- Added unit test for constraint 1
- Added unit test for constraint 2
- Added logic to the code to satisfy constraints above
- Added extra test to highlight that a token sale can still be issued during revenue share
- regenerate metadata and types

2024-04-04 16:09 UTC, ignazio-bovo commented
Update also the preconditions comment...

2024-04-04 23:06 UTC, mnaamani requested changes
Minor update to comments, otherwise looks good to go.

2024-04-04 23:06 UTC, mnaamani commented on runtime-modules/project-token/src/lib.rs
> +        ensure!(
please add this precondition to the code comments

2024-04-04 23:06 UTC, mnaamani commented on runtime-modules/project-token/src/lib.rs
> +        token_data.ensure_can_modify_supply::<T>()?;
Please add this pre-condition to the code comments as well.

2024-04-04 23:06 UTC, mnaamani commented
> Update also the preconditions comment...

did you forget to push this change maybe?

2024-04-05 22:17 UTC, mnaamani commented
This solution works but "it would force creators to open and close their AMMs frequently which is not a good idea"
So replaced by https://github.com/Joystream/joystream/pull/5127

2024-04-05 22:17 UTC, closed without merging