colossus s3 api
Joystream/joystream pull request #5150
Opened 2024-05-16 10:31 UTC by ignazio-bovo

The implementation is the same as suggested here:
#4981 (last comment by Mokhtar)

Instead of utilising a package in order to handle different types of cloud provider I have created a provider agnostic interface which integrates in the colossus logic

I believe this will allow us to easily add support for other providers in the future, by using their official sdk.
The files `localCache` has been enhanced in order to keep track of which files are on the bucket and which files are on the local volume.
Only "accepted" data objects are stored on the bucket

2024-08-23 23:16 UTC, mnaamani requested changes
This is a good start.

The awsConnectionHandler implementation needs to be fixed to properly do uploading to the s3 storage.

The integration bash scripts and docker-compose files to run tests need some changes to get them working. I have made local changes on my machine to get tests working. I can open a PR to your branch if you like.

One jest unit test is failing.

Some limitations I see in the current implementation is that only a single object store can be configured at a time. I think that is fine since object stores are more easily scalable and operator should not need to frequently change which bucket to use. It might be practical from an organizational point of view perhaps to be able to specify a subfolder in the s3 bucket to use for storing the dataobjects.

2024-08-23 23:16 UTC, mnaamani commented on .env
> +CLOUD_STORAGE_PROVIDER_NAME=aws
`ENABLE_STORAGE_PROVIDER` and `CLOUD_STORAGE_PROVIDER_NAME` probably make more sense as command line arguments.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/package.json
> +    "test:integration:cloudProvider": "jest --detectOpenHandles './src/services/storageProviders/tests/**/syncService.test.ts'",
running the test I got one failed test:

```
Mokhtars-MBP:storage-node mokhtar$ yarn test:integration:cloudProvider
yarn run v1.22.19
$ jest --detectOpenHandles './src/services/storageProviders/tests/**/syncService.test.ts'
  Invalid testPattern ./src/services/storageProviders/tests/**/syncService.test.ts supplied. Running all tests instead.
  Invalid testPattern ./src/services/storageProviders/tests/**/syncService.test.ts supplied. Running all tests instead.
 PASS  src/services/storageProviders/tests/integration/setupLocalCache.test.ts (13.784 s)
 PASS  src/services/storageProviders/tests/integration/acceptObject.test.ts
 FAIL  src/services/storageProviders/tests/integration/acceptObjectService.test.ts
  ● accept pending object flow test suite › accept pending object happy path › should call accept objects/maxTxBatchSize times

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 2
    Received number of calls: 0

      70 |
      71 |       expect(acceptPendingDataObjectsBatch).toHaveBeenCalledTimes(2)
    > 72 |       expect(acceptObject).toHaveBeenCalledTimes(2)
         |                            ^
      73 |       expect(addDataObjectIdToCache).toHaveBeenCalledTimes(2)
      74 |     })
      75 |   })

      at Object.<anonymous> (src/services/storageProviders/tests/integration/acceptObjectService.test.ts:72:28)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 23 passed, 24 total
```

2024-08-23 23:16 UTC, mnaamani commented on .env
> +AWS_SECRET_ACCESS_KEY=test-secret
```suggestion
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test
```

To enable the creation of pre-signed URLs for S3 buckets, please set both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to the value `“test”` Our pre-signed URL signature verification algorithm validates the pre-signed URL and its expiration. - note from https://docs.localstack.cloud/user-guide/integrations/aws-cli/#localstack-aws-cli-awslocal

2024-08-23 23:16 UTC, mnaamani commented on docker-compose.localstack.yml
> +      - LOCALSTACK_ENDPOINT=${LOCALSTACK_ENDPOINT}
Looking at https://docs.localstack.cloud/references/configuration/
default_region is deprecated, there are no key configuration, localstack just ignores secret and key ids for now.

2024-08-23 23:16 UTC, mnaamani commented on tests/network-tests/run-tests.sh
> +  docker-compose -f ../../docker-compose.localstack.yml down -v
```suggestion
    docker-compose -f ../../docker-compose.storage-squid.yml down -v
    docker-compose -f ../../docker-compose.localstack.yml down -v
  fi

  docker-compose -f ../../docker-compose.yml down -v
```

We can only stop localstack if we started it.

2024-08-23 23:16 UTC, mnaamani commented on tests/network-tests/run-tests.sh
> +RUNTIME_PROFILE=TESTING ../../scripts/runtime-code-shasum.sh
The refactoring here is not correct. The integration tests will not work with production runtime, so this should be reverted.
This is why the CI checks running tests are failing?

What was the intention here?

2024-08-23 23:16 UTC, mnaamani commented on tests/network-tests/start-storage.sh
> +THIS_DIR=$(dirname $TMP)
The back tick is better, so the script exits with error if the invoked command errors. 
With the `$()` any errors are hidden and the script continues, with the variable assiged being empty, which most times is not the behavior we want.

2024-08-23 23:16 UTC, mnaamani commented on tests/network-tests/start-storage.sh
> +awslocal s3api create-bucket --bucket $AWS_BUCKET_NAME --endpoint http://localhost:4566
We probably want to confirm bucket creation is successful, perhaps localstack didn't come up successfully.

Currently it does indeed fail `aws: error: argument --bucket: expected one argument` if the `AWS_BUCKET_NAME` env variable is not set. It is not loaded from .env file for example and is also the case in the github workflow `run-network-tests.yml` which is an additional reason why the checks would be failing.

awslocal is most likely not installed on the machine, so we need to either install it as part of setup.sh, at least in the github workflow. Other approach, since we have aws-sdk npm package installed maybe have a simple typescript script to create the bucket.

storage and distributor nodes should be started after localstack, not before.

Single bucket is not enough, the integration tests run two storage-nodes so we want to have two separate buckets one for each node.

2024-08-23 23:16 UTC, mnaamani commented on docker-compose.localstack.yml
> +    image: localstack/localstack
```suggestion
    image: localstack/localstack:3
```
Perhaps better to specify the major version number.

2024-08-23 23:16 UTC, mnaamani commented on .env
> +AWS_BUCKET_NAME=sample-bucket
One bucket name is not sufficient, since the tests and when running playgrounds we could have multiple storage nodes.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/commands/server.ts
> +// Global variable for storage provider connection, initialised by server, then readonly
I don't think this is the best place to store these values.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/commands/util/types.ts
> +export type Maybe<T> = T | undefined
I don't see this used anywhere.

2024-08-23 23:16 UTC, mnaamani commented on cli/src/Api.ts
> +  protected workingGroupApiQuery<T extends WorkingGroups>(group: T): ApiPromise['query'][(typeof apiModuleByGroup)[T]] {
Please checkout any code changes to cli, they all seem to be code style changes and best to be in a different PR.
Let keep changes in the PR focused on storage-node

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/storageProviders/IConnectionHandler.ts
> + */
There are two descriptions of the interface. 

I have to say if this is an abstract interface it has a lot of specific naming for s3 storage. The methods and their parameters have confusing and inconsistent names. A file is referred to as filename, key, object. The term RemoteBucket is used but not defined. Even the name of the interface could be improved.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/storageProviders/awsConnectionHandler.ts
> +      Body: filePath,
You are sending the file path string as the "content" of the object. That is not correct.

In my testing I found the storage node uploaded data object with content "/data/pending/0" as confirmation.

According to the AWS sdk docs the [Body](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Interface/PutObjectCommandInput/) needs to be a `StreamingBlobPayloadInputTypes`.  In [nodejs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-types/TypeAlias/NodeJsRuntimeStreamingBlobPayloadInputTypes/) this is `string | Uint8Array | Buffer | Readable` 

Ideally we want to use a readable stream, but the doc says "in Node.js a Readable stream is not signable by the default signer." I'm not sure if that is a problem. Otherwise we have to fallback to using `Buffer`, but that would mean loading entire files into memory which is definitively a bad idea.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/storageProviders/awsConnectionHandler.ts
> +    let input: ListObjectsCommandInput = {
Are we sure we ignore folders, incase there are folders on the bucket?

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/storageProviders/awsConnectionHandler.ts
> +      files.push(...response.Contents.filter((file) => file.Key).map((file) => file.Key!))
Just a reminder
Array.push(...array) is okay as long as array size is small. Otherwise we could get stack overflow.
Seeing the default max keys in response is 1000 we are okay.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/storageProviders/mockConnectionHandler.ts
> +// create a mock implementation of IConnectionHandler
The mock class could be useful, but is not used in the tests. Drop it?

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/helpers/acceptObject.ts
> +  addDataObjectIdToCache(filename)
Missing the second argument to indicate where object is stored.
```suggestion
  addDataObjectIdToCache(filename, toBeAcceptedOnLocalVolume)
```

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/storageProviders/utils.ts
> +export async function parseConfigOptionAndBuildConnection(): Promise<IConnectionHandler | undefined> {
This does not need to be an async function.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/storageProviders/IConnectionHandler.ts
> +  uploadFileToRemoteBucket(filename: string, filePath: string): Promise<any>
We should define how to handle case when an key already exists on the store.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/webApi/controllers/filesApi.ts
> +  const unpin = _.once(async () => {
```suggestion
  const unpin = _.once(() => {
```
Why are you making this async? The underlying call are not async.

2024-08-23 23:16 UTC, mnaamani commented on tests/network-tests/start-storage.sh
> +export LOCALSTACK_ENABLED=true
LOCALSTACK_ENABLED is not passed to colossus-1 and colossus-2 in the docker-compose.yml file so they are not using the localstack, and instead public aws. So they fail to access s3 bucket.

2024-08-23 23:16 UTC, mnaamani commented on storage-node/src/services/helpers/acceptObject.ts
> +  addDataObjectIdToCache(filename)
For both moveFile and uploadToRemoteBucket should we explicitly handle case if destination object already exists?

2024-08-24 07:07 UTC, mnaamani commented on .env
> +CLOUD_STORAGE_PROVIDER_NAME=aws
Also we can reduce from two params to just one, the provider name. If not empty string it means we want to use a cloud storage provider.

2024-08-24 07:22 UTC, mnaamani commented on docker-compose.localstack.yml
> +      - LOCALSTACK_ENDPOINT=${LOCALSTACK_ENDPOINT}
And here I think you meant to configure LOCALSTACK_HOST. LOCALSTACK_ENDPOINT is not a configuration option for localstack anymore

2024-08-27 05:33 UTC, ignazio-bovo commented on tests/network-tests/run-tests.sh
> +RUNTIME_PROFILE=TESTING ../../scripts/runtime-code-shasum.sh
I was not working on my machine

2025-02-13 13:40 UTC, closed without merging