Forum thread editable by author
Joystream/joystream pull request #871
Opened 2020-07-02 16:58 UTC by ondratra

Solves subtask of #766:
- Make thread title editable by author.

To minimize merge conflict potential, this PR assumes #867 will be merged first.

2020-07-02 17:01 UTC, ondratra commented
There is an inconsistency between editing the post's text and thread's title. Post saves a history of changes to the text while thread does not. How will we unite this behavior?

2020-07-02 17:18 UTC, bedeho commented
Neither should store history of any kind, just compute and store hash commitment of most recent text.

2020-07-02 17:34 UTC, ondratra commented
Ok, history was removed.

2020-07-02 18:23 UTC, bedeho requested changes
Looks like post edit history was dropped properly, just a minor tweak.

2020-07-02 18:23 UTC, bedeho commented on runtime-modules/forum/src/lib.rs
>                  let text_hash = T::calculate_hash(&new_text);
Seeing that this was already done before but in general, computation should not be done inside the `mutation` call if possible, only updating the value should be done in the closure.

2020-07-03 12:22 UTC, bedeho approved these changes

2020-07-03 12:23 UTC, merged