Restore storage-node CLI commands.
Joystream/joystream pull request #935
Opened 2020-07-13 14:09 UTC by shamil-gadelshin

Changes:
- convert CLI package to TypeScript
- rewrite upload, download, head commands
- refactor commands
- introduce parameter validation
- rewrite usage

2020-07-14 13:53 UTC, mnaamani requested changes

2020-07-14 13:53 UTC, mnaamani commented on package.json
> +    "postinstall": "yarn workspace @joystream/types build && yarn workspace storage-node run build",
Just leaving anote here, this will get long, so we can do `yarn workspaces run build` which will run the `build` npm script in all workspaces  sequentially. However the order is important because storage-node depends on types. For this we need to start using lerna soon.

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/package.json
> +    "lint": "eslint 'paths/**/*.js' 'lib/**/*.js'",
shouldn't we be linting the `*.ts` files instead ?

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/cli.ts
> +#!/usr/bin/env node
Shouldn't this hashbang go in `packages/cli/bin/cli.js` instead ?

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/cli.ts
> +  // Shows asset information derived from request headers.
```suggestion
  // Shows asset information derived from response headers.
```

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/cli.ts
> +  upload: async (api: any, filePath: string, dataObjectTypeId: string, keyFile: string, passPhrase: string, memberId: string) => {
perhaps make keyFile and passPhrase to be the last two arguments so we leave possibility to make them optional, but not being entered on the command line.

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/cli.ts
> +    upload            Upload a file to a Colossus storage node. Requires a
```suggestion
    upload            Upload a file to the Joystream network. Requires a
```

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/cli.ts
> +    upload            Upload a file to a Colossus storage node. Requires a
and update order of arguments to match with suggestion below.

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/commands/download.ts
> +    private readonly filePath: string;
```suggestion
    private readonly outputFilePath: string;
```

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +            contentId: ContentId.generate().encode(),
do not `.encode()` here. We store the raw bytes in the runtime as a `H256` not a "string/text".
We used the encoded form, in URLs, and in the versioned-store only.

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +        return stats.size;
command should fail (maybe not right here) if file size exceeds MAX_CONTENT_LENGTH

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +            && this.passPhrase && this.passPhrase !== ""
we should allow for possibility that keyfile is not locked, as well as no keyfile being supplied, in which case we could have the development account `//Alice` be loaded as the "default" key.

We can determine if we are on a development chain by interrogating `await api.rpc.system.chain()` is equal to  `Development`

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +        debug(`Decoded CID: ${ContentId.decode(addContentParams.contentId).toString()}`);
see my earlier comment about how content id is stored in runtime.

```suggestion
        debug(`Decoded CID: ${addContentParams.contentId.encode()}`);
```

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +    contentId: string,
```suggestion
    contentId: ContentId,
```

2020-07-14 13:53 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +                'maxContentLength': MAX_CONTENT_LENGTH,
As far as I know, this is the max length of the response, so it doesn't really make sense to have this option here. It is the storage node that will determine how much data it will accept :).

2020-07-14 14:17 UTC, mnaamani commented
Just a suggestion to also update the storage-node/package.json `checks` script to:

`"checks": "yarn lint && prettier ./ --check && tsc --noEmit --pretty",`

I noticed some formatting was missing, so you probably only did linter fixes, but not prettier formatting?

on a side note: I noticed different behavior between `prettier . --write` and `prettier ./ --write`

2020-07-14 15:25 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/cli.ts
> +  // Shows asset information derived from request headers.
Sure.

2020-07-14 15:27 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/cli.ts
> +  upload: async (api: any, filePath: string, dataObjectTypeId: string, keyFile: string, passPhrase: string, memberId: string) => {
Sure

2020-07-14 15:29 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/cli.ts
> +    upload            Upload a file to a Colossus storage node. Requires a
Ok.

2020-07-14 15:30 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/download.ts
> +    private readonly filePath: string;
Ok.

2020-07-14 15:39 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/upload.ts
> +                'maxContentLength': MAX_CONTENT_LENGTH,
Without it I ran into the default axios limit. I could set it 10GB if necessary.

2020-07-14 15:41 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/cli.ts
> +#!/usr/bin/env node
Sure. It was an artifact.

2020-07-14 17:33 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/upload.ts
> +            contentId: ContentId.generate().encode(),
Ok.

2020-07-14 17:33 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/upload.ts
> +        debug(`Decoded CID: ${ContentId.decode(addContentParams.contentId).toString()}`);
Ok

2020-07-14 17:34 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/upload.ts
> +            && this.passPhrase && this.passPhrase !== ""
Done.

2020-07-14 17:34 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/upload.ts
> +        return stats.size;
Yes, it is failing.

2020-07-14 17:34 UTC, shamil-gadelshin commented on package.json
> +    "postinstall": "yarn workspace @joystream/types build && yarn workspace storage-node run build",
Ok

2020-07-14 17:35 UTC, shamil-gadelshin commented on storage-node/packages/cli/package.json
> +    "lint": "eslint 'paths/**/*.js' 'lib/**/*.js'",
Fixed.

2020-07-14 17:35 UTC, shamil-gadelshin commented on storage-node/packages/cli/src/commands/upload.ts
> +    contentId: string,
Done

2020-07-15 03:12 UTC, mnaamani commented on storage-node/packages/cli/package.json
> +    "lint": "eslint --ext .js,.jsx,.ts,.tsx . && tsc --noEmit --pretty",
I would leave off the `&& tsc --noEmit --pretty` from the lint script, so you can add args to lint for fixing eg.

`yarn lint --fix`

I was trying to have a kind of common scripts for all packages:

lint: 'eslint ... ',
format: 'prettier . --write'
checks: 'yarn lint && prettier . --check && tsc --noEmit --pretty'

2020-07-15 03:43 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +                'maxContentLength': MAX_CONTENT_LENGTH,
But was the problem with the request (upload) or the response ?

2020-07-15 03:47 UTC, mnaamani commented on storage-node/packages/cli/src/commands/upload.ts
> +        return stats.size;
are you only depending on the axios maxContentLength header option for this check? Still not sure we are using that correctly. Let me check HTTP docs.

2020-07-15 05:19 UTC, mnaamani commented
>     * currently, the CLI package is based on the `meow` package which doesn't support subcommands - we should consider migration to the `oclif`. The current class-based implementation allows us to do that with less effort.

I agree, we are using it in the joystream-cli package currently.


Merging, minor issue with maxContentLength can be addressed later.

2020-07-15 05:20 UTC, merged